mapstruct/mapstruct

integrationtest/src/test/resources/simpleTest/src/test/java/org/mapstruct/itest/simple/ConversionTest.java, processor/src/main/java/org/mapstruct/ap/model/source/MethodMatcher.java, processor/src/test/java/org/mapstruct/ap/test/bool/BooleanMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/bool/PersonDto.java, processor/src/test/java/org/mapstruct/ap/test/bool/PersonMapper.java, processor/src/test/java/org/mapstruct/ap/test/bool/YesNo.java, processor/src/test/java/org/mapstruct/ap/test/bool/YesNoMapper.java
=> allow autoboxing for primitive return types of property mapping methods to non-primitive properties

core-common/src/main/java/org/mapstruct/BeanMapping.java, processor/src/main/java/org/mapstruct/ap/model/source/BeanMapping.java, processor/src/main/java/org/mapstruct/ap/model/source/IterableMapping.java, processor/src/main/java/org/mapstruct/ap/processor/creation/MappingResolverImpl.java, processor/src/main/resources/org.mapstruct.ap.model.GeneratedType.ftl, processor/src/test/java/org/mapstruct/ap/test/collection/erroneous/ErroneousCollectionMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/selection/qualifier/ErroneousMovieFactoryMapper.java, processor/src/test/java/org/mapstruct/ap/test/selection/qualifier/MovieFactoryMapper.java, processor/src/test/java/org/mapstruct/ap/test/selection/qualifier/QualifierTest.java, processor/src/test/java/org/mapstruct/ap/test/selection/qualifier/annotation/CreateGermanRelease.java, processor/src/test/java/org/mapstruct/ap/test/selection/qualifier/bean/ReleaseFactory.java
* Aligning `@BeanMapping` with other mapping types.
* Small improvement on templates (removing empty lines from fields)
=> #432 Selection of factory method based on Qualifier

processor/src/main/java/org/mapstruct/ap/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/selection/resulttype/ErroneousFruitMapper2.java, processor/src/test/java/org/mapstruct/ap/test/selection/resulttype/InheritanceSelectionTest.java, processor/src/test/java/org/mapstruct/ap/test/selection/resulttype/ResultTypeConstructingFruitMapper.java, processor/src/test/java/org/mapstruct/ap/test/selection/resulttype/ResultTypeSelectingFruitMapper.java
Based on PR for issue #433. Check that one first.
=> #434 construct resultType based on @BeanMaping#resultType when no factory methods selected

processor/src/main/java/org/mapstruct/ap/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/collection/erroneous/ErroneousCollectionMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/collection/erroneous/ErroneousCollectionNoElementMappingFound.java, processor/src/test/java/org/mapstruct/ap/test/collection/erroneous/ErroneousCollectionNoKeyMappingFound.java, processor/src/test/java/org/mapstruct/ap/test/collection/erroneous/ErroneousCollectionNoValueMappingFound.java
should speak for itself :smile:
=> #459 error message parameter forgotten

processor/src/main/java/org/mapstruct/ap/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/model/assignment/ArrayCopyWrapper.java
Bring `existingVariableNames` to `ArrayCopyWrapper`. Problem / Solution is straightforward
=> #485 ArrayCopyWrapper local var possibly not safe

processor/src/main/java/org/mapstruct/ap/conversion/AbstractJodaTypeToStringConversion.java, processor/src/test/java/org/mapstruct/ap/test/conversion/jodatime/JodaConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/jodatime/SourceTargetMapper.java
I fixed this, but I'm not an expert on JodaTime. I'm a bit worried on the terminating spaces on 111 and 113 on `JodaConversionTest`
=> #320 fixing JodaTime unit test

processor/src/main/java/org/mapstruct/ap/model/common/Type.java, processor/src/test/java/org/mapstruct/ap/test/collection/map/MapMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/collection/map/Source.java, processor/src/test/java/org/mapstruct/ap/test/collection/map/other/ImportedType.java
=> Add missing imports for a collection/map implementation and the parameter types

.gitignore, core-common/src/main/java/org/mapstruct/InheritConfiguration.java, core/src/main/java/org/mapstruct/Mapping.java, parent/pom.xml, processor/src/main/java/org/mapstruct/ap/conversion/AbstractJodaTypeToStringConversion.java, processor/src/main/java/org/mapstruct/ap/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/model/MappingMethod.java, processor/src/main/java/org/mapstruct/ap/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/model/assignment/Assignment.java, processor/src/main/java/org/mapstruct/ap/model/common/Type.java, processor/src/main/java/org/mapstruct/ap/model/common/TypeFactory.java, processor/src/main/java/org/mapstruct/ap/model/dependency/GraphAnalyzer.java, processor/src/main/java/org/mapstruct/ap/model/source/EnumMapping.java, processor/src/main/java/org/mapstruct/ap/model/source/Mapping.java, processor/src/main/java/org/mapstruct/ap/model/source/Method.java, processor/src/main/java/org/mapstruct/ap/model/source/MethodMatcher.java, processor/src/main/java/org/mapstruct/ap/model/source/SourceReference.java, processor/src/main/java/org/mapstruct/ap/model/source/builtin/BuiltInMethod.java, processor/src/main/java/org/mapstruct/ap/model/source/selector/XmlElementDeclSelector.java, processor/src/main/java/org/mapstruct/ap/prism/NullValueMappingStrategyPrism.java, processor/src/main/java/org/mapstruct/ap/processor/creation/MappingResolverImpl.java, processor/src/main/java/org/mapstruct/ap/util/Executables.java, processor/src/main/java/org/mapstruct/ap/util/Nouns.java, processor/src/main/java/org/mapstruct/ap/writer/Writable.java
So we'll have feedback on errors / warnings during our local builds and on Jenkins.
If I only knew what I got into... I had to fix a whole bunch of errors as well. :wink:
=> Generate Javadocs during mvn install

.gitignore, parent/pom.xml
=> #553, add Netbeans files to .gitignore and exlude from license check

processor/src/main/java/org/mapstruct/ap/internal/processor/MapperServiceProcessor.java, processor/src/test/java/org/mapstruct/ap/test/destination/AbstractDestinationClassNameMapper.java, processor/src/test/java/org/mapstruct/ap/test/destination/AbstractDestinationPackageNameMapper.java, processor/src/test/java/org/mapstruct/ap/test/destination/DestinationClassNameTest.java
=> #660 Fix custom package / implementation name with abstract classes

processor/src/main/java/org/mapstruct/ap/internal/conversion/JavaLocalDateTimeToDateConversion.java, processor/src/test/java/org/mapstruct/ap/test/conversion/java8time/Java8TimeConversionTest.java
@agudian, @sjaakd: A quick one :)
=> #681 Using UTC for Date/JavaLocalDate conversion in both directions

processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/test/java/org/mapstruct/ap/test/defaultvalue/CountryDts.java, processor/src/test/java/org/mapstruct/ap/test/defaultvalue/CountryEntity.java, processor/src/test/java/org/mapstruct/ap/test/defaultvalue/CountryMapper.java, processor/src/test/java/org/mapstruct/ap/test/defaultvalue/DefaultValueTest.java, processor/src/test/java/org/mapstruct/ap/test/defaultvalue/other/Continent.java
=> #698 Fix missing import for enums in case of default values.

integrationtest/src/test/java/org/mapstruct/itest/testutil/runner/ProcessorSuite.java, integrationtest/src/test/resources/pom.xml, parent/pom.xml, processor/src/main/java/org/mapstruct/ap/internal/model/Decorator.java, processor/src/main/java/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/Assignment.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Accessibility.java, processor/src/main/java/org/mapstruct/ap/internal/model/dependency/Node.java, processor/src/main/java/org/mapstruct/ap/internal/option/ReportingPolicy.java, processor/src/main/java/org/mapstruct/ap/internal/writer/FreeMarkerModelElementWriter.java, processor/src/main/resources/org/mapstruct/ap/internal/model/BeanMappingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/DelegatingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/IterableMappingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/MapMappingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/MethodReference.ftl, processor/src/test/java/org/mapstruct/ap/test/array/ArrayMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/builtin/BuiltInTest.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/ongeneratedmethods/MappingResultPostprocessorTest.java, processor/src/test/java/org/mapstruct/ap/test/collection/forged/CollectionMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/nestedmethodcall/NestedMappingMethodInvocationTest.java, processor/src/test/java/org/mapstruct/ap/test/selection/qualifier/QualifierTest.java, processor/src/test/java/org/mapstruct/ap/test/source/expressions/java/JavaExpressionTest.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/UpdateMethodsTest.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/selection/ExternalHandWrittenMapper.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/ModifiableURLClassLoader.java
Update checkstyle version and fix several previously undetected issues in our code (mostly missing whitespaces and redundant modifiers) and in the generated code (superflous whitespaces before commas)
Requrires update of guava and cdi-weld do to dependency convergence.
=> #701 Update checkstyle version and fix several previously undetected issues

processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java, processor/src/test/java/org/mapstruct/ap/test/collection/erroneous/ErroneousCollectionMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/collection/erroneous/ErroneousCollectionToPrimitivePropertyMapper.java, processor/src/test/java/org/mapstruct/ap/test/collection/erroneous/Source.java, processor/src/test/java/org/mapstruct/ap/test/collection/erroneous/Target.java
I have prepared a fix for the NullPointerException. The fix itself was not that hard. But for an dedicated unit test I need some help. The test-framework is quite complicated.
=> #729 Fix trying to resolving constructor on primitive types

documentation/pom.xml
@gunnarmorling / @sjaakd anyone interested in reviewing? Otherwise I'll just push it to master. I tried it locally and it did what's expected to do... :)
=> #842 Use project.version as MapStruct version in the documentation

readme.md
Adjusts the thing of #787 that I find most annoying. :grin:
=> #787 Enhance readme to use maven-compiler-plugin and add some badges.

processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/EnumConstantWrapper.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/EnumConstantWrapper.ftl, processor/src/test/java/org/mapstruct/ap/test/source/constants/CountryEnum.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/ErroneousMapper1.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/ErroneousMapper3.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/ErroneousMapper4.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/ErroneousMapper5.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/SourceConstantsTest.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/SourceTargetMapper.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/Target.java
There's still #871 as small spin of to be taken care of..
=> #700 Fixing enum constants and adding unit test.

processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_843/Commit.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_843/GitlabTag.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_843/Issue843Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_843/TagInfo.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_843/TagMapper.java
I can't really make a reproducer for this one. You can't test for ineffective code. So I'm wandering whether the UT makes sense.
=> #843 reproducer and solution

processor/src/main/java/org/mapstruct/ap/internal/model/assignment/SetterWrapperForCollectionsAndMaps.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/ForgedMethod.java, processor/src/main/java/org/mapstruct/ap/internal/util/Strings.java, processor/src/main/resources/org/mapstruct/ap/internal/model/IterableMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_895/Issue895Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_895/MultiArrayMapper.java
=> #895 Fix generating forged iterable methods for mapping multi-dimensional Array types

processor/src/test/java/org/mapstruct/ap/testutil/runner/CompilingStatement.java
Helps when stepping through generated codes in tests :)
=> #915 Adding debug information to class files created during tests

processor/src/main/resources/org/mapstruct/ap/internal/model/MapMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/collection/CollectionMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/collection/SourceTargetMapper.java, processor/src/test/java/org/mapstruct/ap/test/collection/StringHolder.java, processor/src/test/java/org/mapstruct/ap/test/collection/StringHolderArrayList.java, processor/src/test/java/org/mapstruct/ap/test/collection/StringHolderToLongMap.java, processor/src/test/java/org/mapstruct/ap/test/collection/Target.java
This fixes #919.
@gunnarmorling / @sjaakd could one of you please take a look?
=> #919 Fix compilation error in map-mapping methods with non-generic maps as source

processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/SetterWrapperForCollectionsAndMaps.ftl
Should be an easy one to review :smile:
=> #968 removing strange enters and spaces in formatting.

processor/src/main/java/org/mapstruct/ap/internal/model/IterableMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/MapMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/MappingBuilderContext.java, processor/src/main/java/org/mapstruct/ap/internal/model/MethodReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/SourceRHS.java, processor/src/main/java/org/mapstruct/ap/internal/model/TypeConversion.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/AdderWrapper.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/Assignment.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/AssignmentWrapper.java, processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java, processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/AdderWrapper.ftl
As first step in refactoring wrappers, stream lining the source side of the assignment.
Ok.. I'm wondering how many times I can make mistakes in commit names when creating a simple pull request. :sad: But here it is again.
=> #899 refactoring adder wrapper.

processor/src/main/java/org/mapstruct/ap/internal/util/Strings.java, processor/src/test/java/org/mapstruct/ap/internal/util/StringsTest.java, processor/src/test/java/org/mapstruct/ap/test/nestedproperties/simple/SimpleMapper.java
If the name contains dots, then split it and join and camelize the parts
=> #978 make sure that the safe variable name does not contain dots in it

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/EnumMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/IterableMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/LifecycleCallbackFactory.java, processor/src/main/java/org/mapstruct/ap/internal/model/LifecycleCallbackMethodReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/MapMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/ValueMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MethodRetrievalProcessor.java, processor/src/main/resources/org/mapstruct/ap/internal/model/LifecycleCallbackMethodReference.ftl, processor/src/test/java/org/mapstruct/ap/test/callbacks/returning/Attribute.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/returning/AttributeDTO.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/returning/CallbacksWithReturnValuesTest.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/returning/Node.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/returning/NodeDTO.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/returning/NodeMapperContext.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/returning/NodeMapperDefault.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/returning/NodeMapperWithContext.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/returning/Number.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/returning/NumberMapperContext.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/returning/NumberMapperDefault.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/returning/NumberMapperWithContext.java
=> #469 Mapping Object Graphs with Cycles

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc
This is a separate PR for the documentation for the new field mappings ability introduced in #928
=> #557 Add documentation about using fields as read/write accessors

processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java, processor/src/main/java/org/mapstruct/ap/internal/util/accessor/Accessor.java
I forgot to add the Javadoc to the `Accessor` during the main PR. So this one is just for that one 😄
=> #557 add Javadoc for the Accessor

processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java, processor/src/test/java/org/mapstruct/ap/test/array/ArrayMappingTest.java
This shouldn't be too complicated 😄
=> #999 make sure that the qualifiedName of the class is trimmed before doing any comparisons for import check

processor/src/test/java/org/mapstruct/ap/test/bugs/_913/Issue913SetterMapperForCollectionsTest.java, processor/src/test/java/org/mapstruct/ap/test/collection/adder/AdderTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/string/StringConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/UpdateMethodsTest.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/selection/ExternalSelectionTest.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithNcvsAlwaysMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithNvmsDefaultMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithNvmsNullMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithPresenceCheckMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/collection/adder/Source2Target2MapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/collection/adder/SourceTargetMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/collection/adder/SourceTargetMapperStrategyDefaultImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/collection/adder/SourceTargetMapperStrategySetterPreferredImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/conversion/string/SourceTargetMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/updatemethods/CompanyMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/updatemethods/OrganizationMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/updatemethods/selection/DepartmentMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/updatemethods/selection/ExternalMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/updatemethods/selection/OrganizationMapper1Impl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/updatemethods/selection/OrganizationMapper2Impl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/updatemethods/selection/OrganizationMapper3Impl.java
This are all the tests which are in #1007. Do we need to add more tests?
=> #1007 additional generated code tests

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1029/ErroneousIssue1029Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1029/Issue1029Test.java, processor/src/test/java/org/mapstruct/ap/test/ignore/ErroneousTargetHasNoWriteAccessorMapper.java, processor/src/test/java/org/mapstruct/ap/test/ignore/IgnorePropertyTest.java, processor/src/test/java/org/mapstruct/ap/test/ignore/Preditor.java, processor/src/test/java/org/mapstruct/ap/test/ignore/PreditorDto.java
=> #1029 Don't show an error when explicitly ignoring read-only properties

processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Parameter.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/ForgedMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/NestedSimpleBeansMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/UserDtoUpdateMapperSmart.java
=> #1001 auto mapping support for update methods

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1005/AbstractEntity.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1005/HasKey.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1005/HasPrimaryKey.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1005/Issue1005ErroneousAbstractResultTypeMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1005/Issue1005ErroneousAbstractReturnTypeMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1005/Issue1005ErroneousInterfaceResultTypeMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1005/Issue1005ErroneousInterfaceReturnTypeMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1005/Issue1005Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1005/Order.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1005/OrderDto.java, processor/src/test/java/org/mapstruct/ap/test/selection/qualifier/QualifierTest.java, processor/src/test/java/org/mapstruct/ap/test/selection/resulttype/InheritanceSelectionTest.java
=> #1005 Report an error if the resulting type in the BeanMappingMethod is abstract

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/NestedTargetPropertyMappingHolder.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java
In order to clean up the #1072 PR we need to extract the generation of the groupings into a separate class. After this one is resolved, then we can more easily do the clean up
=> Wrap mapping options groupings

processor/src/main/resources/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.ftl, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedsourceproperties/ArtistToChartEntryImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedtargetproperties/ChartEntryToArtistImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedtargetproperties/FishTankMapperImpl.java
Fixes #1082. It is really simple 😄
=> #1082 Do not generate an empty line after method start for NestedPropertyMappingMethod

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc
Is this enough or we need to write more?
=> #1001 Update documentation for the new automapping

documentation/src/main/asciidoc/controlling-nested-bean-mappings.asciidoc, documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc
Missing: I need to look what kind of formatting I should use if I use references to method signatures in-line.
Missing: example. Need to bring fishtank example to example repository as soon as we agree on #1057.
=> #1057 documentation for Controlling forged name based bean mapping from root level with @Mapping

processor/src/test/java/org/mapstruct/ap/test/value/SpecialOrderMapper.java
It is a bit strange how there was no error in #1094. This fixes the build
=> Fix checkstyle error

processor/src/main/java/org/mapstruct/ap/internal/model/AbstractBaseBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/AbstractMappingMethodBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/ValueMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingMethodUtils.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/main/resources/org/mapstruct/ap/internal/model/ValueMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/DottedErrorMessageTest.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/ExternalRoofType.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/NestedSimpleBeansMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/Roof.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/RoofDto.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/RoofType.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/UserDtoMapperClassic.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/erroneous/ExternalRoofType.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/erroneous/Roof.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/erroneous/RoofDto.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/erroneous/RoofType.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/erroneous/RoofTypeMapper.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/erroneous/UnmappableCollectionElementPropertyMapper.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/erroneous/UnmappableDeepListMapper.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/erroneous/UnmappableDeepMapValueMapper.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/erroneous/UnmappableDeepNestingMapper.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/erroneous/UnmappableEnumMapper.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/erroneous/UnmappableValuePropertyMapper.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedbeans/UserDtoMapperClassicImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedbeans/UserDtoMapperSmartImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedbeans/UserDtoUpdateMapperSmartImpl.java
Fixes #1102 
Maybe we need to do the same that it is done in `MapperCreationProccessor.getMappingMethods()`
=> #1102 Add support for Auto forging of Enum properties

processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/TypeSelector.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1130/Issue1130Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1130/Issue1130Test.java
=> #1130 Consider the right target type for object factory methods

processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1155/Entity.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1155/Issue1155Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1155/Issue1155Test.java
=> #1155 Field accessors should be considered when resolving nested target properties

parent/pom.xml, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/NestedSimpleBeansMappingTest.java
Just a small bump of AssertJ and switch to using a new dedicated method in AssertJ instead of our own
=> Update assertj and used dedicated method in tests

core-common/src/main/java/org/mapstruct/NullValueCheckStrategy.java, parent/pom.xml, processor/src/main/java/org/mapstruct/ap/internal/conversion/BigDecimalToStringConversion.java, processor/src/main/java/org/mapstruct/ap/internal/conversion/BigIntegerToStringConversion.java, processor/src/main/java/org/mapstruct/ap/internal/model/IterableCreation.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/ImplementationType.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/BeanMapper.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/WildCardTest.java
* #122 Use util methods when possible
* Fix some warnings in Javadoc generation
* Don't use raw classes when not needed
* Add .yml, binding.xjb and .asciidoc files to license check exclusion
=> General code cleanups:

processor/src/main/java/org/mapstruct/ap/internal/model/AbstractBaseBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/PropertyEntry.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1148/Entity.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1148/Issue1148Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1148/Issue1148Test.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedbeans/mixed/FishTankMapperImpl.java
=> #1148 Always add the generated MappingMethod if the MappingOptions are restricted to the defined mappings

etc/forbidden-apis.txt, parent/pom.xml, processor/pom.xml, processor/src/main/java/org/mapstruct/ap/internal/model/EnumMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/ValueMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/BeanMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/IterableMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MapMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/Mapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MethodMatcher.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SelectionParameters.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MethodRetrievalProcessor.java, processor/src/test/java/org/mapstruct/ap/internal/model/source/SelectionParametersTest.java
=> #1129 Do not use equals and hashCode from TypeMirror

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc
=> #1219 Mention ability to turn of automatic sub-mapping generation in documentation

processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/main/resources/org/mapstruct/ap/internal/model/common/Type.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_543/Issue543Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_543/Issue543Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_543/SourceUtil.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_543/dto/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_543/dto/Target.java
=> #543 Make sure that the bound type is imported if the type is wildcard

core-jdk8/pom.xml, core/pom.xml, parent/pom.xml, processor/pom.xml
Fixes #1231
We could also add the generated HTML to some section on our website
=> #1231 Add japicmp for the MapStruct API

.travis.yml, etc/travis-settings.xml, parent/pom.xml
Fixes #1251.
Merge only after the `SONATYPE_USERNAME` and `SONATYPE_PASSWORD` have been added on Travis. [Here](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings) can be seen how to do them. I can do it as well, we just need to agree how we are going to do it (add a new mapstruct-ci user to sonatype, or somehow different).
=> #1251 Deploy SNAPSHOTS from Travis CI

build-config/pom.xml, core-common/pom.xml, integrationtest/pom.xml, parent/pom.xml, pom.xml
=> #1281 Do not depend on deprecated sonatype parent

CONTRIBUTING.md
=> Add IntelliJ Formatter to CONTRIBUTING.md

readme.md
=> Change MapStruct Version in README to latest 1.2.0.Final

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc
Fixes #1314 
If you have additional information to put there or find a typo, let me know.
=> Injection Strategy docs

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/conversion/Conversions.java, processor/src/main/java/org/mapstruct/ap/internal/conversion/CurrencyToStringConversion.java, processor/src/test/java/org/mapstruct/ap/test/conversion/currency/CurrencyConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/currency/CurrencyMapper.java, processor/src/test/java/org/mapstruct/ap/test/conversion/currency/CurrencySource.java, processor/src/test/java/org/mapstruct/ap/test/conversion/currency/CurrencyTarget.java
- Registered implicit conversions between java.util.Currency and String in Conversions class
- Added unit test cases
- Added necessary documentation under **Implicit type conversions** heading
=> #1355: Adds Implicit Conversion Between java.util.Currency <~> String

processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/MethodSelectors.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/XmlElementDeclSelector.java
Fixes #1378 (potentially)
We need to investigate whether this actually speeds things up before merging
=> #1378 Use Types instead of searching for type elements

processor/src/main/java/org/mapstruct/ap/spi/NoOpBuilderProvider.java, processor/src/test/java/org/mapstruct/ap/test/builder/noop/NoOpBuilderProviderTest.java, processor/src/test/java/org/mapstruct/ap/test/builder/noop/Person.java, processor/src/test/java/org/mapstruct/ap/test/builder/noop/PersonDto.java, processor/src/test/java/org/mapstruct/ap/test/builder/noop/PersonMapper.java
=> #1418 Add support for NoOp BuilderProvider for turning off using of builders

processor/src/main/java/org/mapstruct/ap/internal/processor/MapperRenderingProcessor.java
Fixes #1414 
I was thinking to add a test with Mockito. However, that would require to perform a lot of mocking just to validate that we are passing the mapper element to the API. 
If you think it is worth it, I can add it
=> #1414 Pass originating mapper element to the Filer API

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc, integrationtest/src/test/resources/immutablesBuilderTest/extras/src/main/java/org/mapstruct/itest/immutables/extras/ImmutablesBuilderProvider.java
=> #1417 Add documentation about the builder support

readme.md
Hello: this README was easy to read and understand. Good work! A few suggestions you may or may not take:
— Project roadmap: Do you have one? It might make sense to take a few of the top-priority Issues in the tracker and list them in a section, to show others what you're aiming for next.
— Do you have any user testimonials or success stories from people using the project? Some quotes/stories in the documentation set might be useful to prospective users.
— A note to contributors (maybe in the Contributing.md instead of the README) stating average response time would be helpful, along with a Maintainers file in case requests to the community channel go unanswered.
Thanks for submitting to FMRM!
=> Feedmereadmes edit

processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceReference.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/main/java/org/mapstruct/ap/internal/util/Strings.java, processor/src/test/java/org/mapstruct/ap/test/severalsources/ErroneousSourceTargetMapper2.java, processor/src/test/java/org/mapstruct/ap/test/severalsources/SeveralSourceParametersTest.java
=> Improve error message when unknown source parameter is used in @Mapping

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java, processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java, processor/src/main/java/org/mapstruct/ap/internal/util/NativeTypes.java, processor/src/test/java/org/mapstruct/ap/internal/model/common/DateFormatValidatorFactoryTest.java, processor/src/test/java/org/mapstruct/ap/internal/model/common/DefaultConversionContextTest.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/ConstantOptimizingTest.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/ErroneousMapper1.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/ErroneousMapper3.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/ErroneousMapper5.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/ErroneousMapper6.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/SourceConstantsTest.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/SourceTargetMapper.java
I think I got all checks covered. The examples from the JLS work. Minimum, maximum works. Added a bunch of tests. So, apart from the discussion on whether there are problems to be foreseen that we cannot handle in the release notes, this should be ready to go.
=> #1401 performance improvements when assigning constants

core-common/src/main/java/org/mapstruct/BeanMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/BeanMapping.java, processor/src/test/java/org/mapstruct/ap/test/source/ignore/IgnoreUnmappedSourceMapper.java, processor/src/test/java/org/mapstruct/ap/test/source/ignore/IgnoreUnmappedSourcePropertiesTest.java, processor/src/test/java/org/mapstruct/ap/test/source/ignore/Person.java, processor/src/test/java/org/mapstruct/ap/test/source/ignore/PersonDto.java
This property has only effect on the unmapped source properties report
Fixes #1317
=> #1317 Add support for ignoring unmapped source properties

processor/src/main/java/org/mapstruct/ap/spi/DefaultAccessorNamingStrategy.java, processor/src/test/java/org/mapstruct/ap/test/builder/simple/ErroneousSimpleBuilderMapper.java, processor/src/test/java/org/mapstruct/ap/test/builder/simple/SimpleBuilderMapper.java, processor/src/test/java/org/mapstruct/ap/test/builder/simple/SimpleImmutableBuilderTest.java, processor/src/test/java/org/mapstruct/ap/test/builder/simple/SimpleImmutablePerson.java, processor/src/test/java/org/mapstruct/ap/test/builder/simple/SimpleMutablePerson.java
=> #1449 Adders should not be considered as builder setter methods

processor/src/main/java/org/mapstruct/ap/internal/util/AnnotationProcessorContext.java
=> #1473 Make sure that the SPIs are lazy initialized in the AnnotationProcessorContext

processor/src/main/java/org/mapstruct/ap/internal/model/assignment/AdderWrapper.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/SourceRHS.java, processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/AdderWrapper.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_1338/Issue1338Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1338/Issue1338Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1338/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1338/Target.java
=> #1338 Using an adder with non generic source collection should work

processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1453/Auction.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1453/AuctionDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1453/Issue1453Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1453/Issue1453Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1453/Payment.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1453/PaymentDto.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_1453/Issue1453MapperImpl.java
When generating collection mapping methods make sure that the created variable is from the bound type
Fixes #1453
=> #1453 Make sure that we always create non bound collection

processor/pom.xml, processor/src/test/java/org/mapstruct/ap/test/bugs/_537/Issue537Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_537/Issue537MapperConfig.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_537/Issue537Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_537/ReferenceMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_537/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_537/Target.java
Issue #537 was most likely fixed in the meantime, but here is a test-case for the reported issue to improve the test-suite.
=> #537 ambiguous mapping when same method twice

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1552/Issue1552Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1552/Issue1552Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1552/Target.java
=> #1552 Stop processing source parameters for unprocessed defined properties when a mapping is found

processor/src/main/java/org/mapstruct/ap/spi/DefaultAccessorNamingStrategy.java, processor/src/main/java/org/mapstruct/ap/spi/ImmutablesAccessorNamingStrategy.java
=> #1578 Rename isBuilderSetter to isFluentSetter in the DefaultAccessorNamingStrategy

processor/src/main/java/org/mapstruct/ap/internal/model/assignment/SetterWrapperForCollectionsAndMapsWithNullCheck.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1590/Book.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1590/BookMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1590/BookShelf.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1590/BookShelfMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1590/Issue1590Test.java
Just trying to reproduce the problem..
=> #1590 Missing ArrayList import in case of NVMS.RETURN_DEFAULT

copyright.txt, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/test/java/org/mapstruct/ap/test/source/presencecheck/spi/PresenceCheckNestedObjectsTest.java, processor/src/test/java/org/mapstruct/ap/test/source/presencecheck/spi/Referee.java, processor/src/test/java/org/mapstruct/ap/test/source/presencecheck/spi/SoccerTeamMapperNestedObjects.java, processor/src/test/java/org/mapstruct/ap/test/source/presencecheck/spi/SoccerTeamSource.java, processor/src/test/java/org/mapstruct/ap/test/source/presencecheck/spi/SoccerTeamTargetWithPresenceCheck.java
=> #1456 apply source presence tracking recursively (in nested source)

ISSUE_TEMPLATE.md
I rather had a dialogue before the user writes a new issue, but this is the best next...
=> Adding an issue template to streamline answers.

processor/src/main/java/org/mapstruct/ap/spi/DefaultAccessorNamingStrategy.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1608/Book.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1608/BookDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1608/Issue1608Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1608/Issue1608Test.java
=> #1608 Make sure that property names for fluent setters starting with is are handled properly

processor/src/test/java/org/mapstruct/ap/test/bugs/_1594/Issue1594Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1594/Issue1594Test.java
Fixes #1594 
There is nothing to fix. The test case is there only to show that it works correctly
=> #1594 Add test case to show that it has been fixed

processor/src/main/java/org/mapstruct/ap/internal/conversion/Conversions.java, processor/src/main/java/org/mapstruct/ap/internal/conversion/JavaLocalDateToSqlDateConversion.java, processor/src/main/java/org/mapstruct/ap/internal/conversion/JavaSqlDateToLocalDateConversion.java, processor/src/test/java/org/mapstruct/ap/test/conversion/java8time/Java8TimeConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/java8time/Source.java, processor/src/test/java/org/mapstruct/ap/test/conversion/java8time/Target.java
=> Add support for mapping java.time.LocalDate to java.sql.Date

processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java, processor/src/main/java/org/mapstruct/ap/internal/util/AnnotationProcessorContext.java, processor/src/main/java/org/mapstruct/ap/spi/BuilderProvider.java, processor/src/main/java/org/mapstruct/ap/spi/DefaultBuilderProvider.java, processor/src/main/java/org/mapstruct/ap/spi/ImmutablesBuilderProvider.java, processor/src/main/java/org/mapstruct/ap/spi/NoOpBuilderProvider.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1596/Issue1569BuilderProvider.java
Used for initializing the Elements and Types
Fixes #1640
=> #1640 Add init method with MapStructProcessingEnvironment to the BuilderProvider

documentation/src/main/asciidoc/controlling-nested-bean-mappings.asciidoc, documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc
Cleanups in the reference documentation to use Repeteable `@Mapping` annotation. 
Related to #1645
=> #1645 Use Repeatable Mapping annotation in the reference documentation

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1648/Issue1648Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1648/Issue1648Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1648/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1648/Target.java
=> #1648 Source properties defined in Mapping should not be reported as unmapped

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1681/Issue1681Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1681/Issue1681Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1681/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1681/Target.java
=> #1681 Do not use finalizer method when using update method and result type and return type match

core/src/main/java/org/mapstruct/NullValuePropertyMappingStrategy.java, documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/main/resources/org/mapstruct/ap/internal/model/macro/CommonMacros.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_1685/UserMapper.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_1685/UserMapperImpl.java
@filiphr .. can't get the javadoc to work.. Perhaps you spot the issue?
Ok.. Its the maven build that is a bit unclear. I spelt `{@Code xyz}` iso `{@code xyz}`
=> #1699 add sensible defaults to NullValuePropertyMapping.SET_TO_DEFAULT

processor/src/main/resources/org/mapstruct/ap/internal/model/StreamMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_1707/Converter.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1707/Issue1707Test.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_1707/ConverterImpl.java
@filiphr  The solution is adapting the template.. But a lot happens in the template. I first tried to update the `needVarDefine` itself  but then a lot of tests start to fail. It feels not entirely right to do it only on this spot, so please feel free to adapt / add.
=> #1707 fix for not defining local variable in stream-iterable mapping

readme.md
Hi there!
I thought you might be interested in adding these LGTM [code quality badges](https://lgtm.com/projects/g/mapstruct/mapstruct/ci/#badges) to your project. They indicate how you care about code quality and encourage your future contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/mapstruct/mapstruct).
N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.
=> Add LGTM code quality badges

processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceReference.java
=> #1075 refactoring source reference

processor/src/main/java/org/mapstruct/ap/MappingProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/conversion/DateToStringConversion.java, processor/src/main/java/org/mapstruct/ap/internal/model/Annotation.java, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/LifecycleMethodResolver.java, processor/src/main/java/org/mapstruct/ap/internal/model/MethodReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SelectionParameters.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceReference.java, processor/src/main/java/org/mapstruct/ap/internal/util/AnnotationProcessorContext.java, processor/src/main/java/org/mapstruct/ap/internal/util/Fields.java, processor/src/main/java/org/mapstruct/ap/internal/util/MapperConfiguration.java
Remove unnecessary generic type in Collections.empty*,
replace "for" on Stream API,
replace anonymous classes on lambda
I'm sorry, but I have added "dist: trusty" in travis.yml . I can't pass checks without it. I'll remove it if you will help me to pass checks without it.
=> Fix minor warnings

processor/src/test/java/org/mapstruct/ap/test/collection/CollectionMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/collection/StringHolder.java, processor/src/test/java/org/mapstruct/ap/test/collection/Target.java, processor/src/test/java/org/mapstruct/ap/test/collection/adder/AdderTest.java, processor/src/test/java/org/mapstruct/ap/test/collection/adder/PetMapper.java, processor/src/test/java/org/mapstruct/ap/test/collection/adder/_target/Target.java, processor/src/test/java/org/mapstruct/ap/test/collection/adder/_target/TargetDali.java, processor/src/test/java/org/mapstruct/ap/test/collection/adder/_target/TargetHuman.java, processor/src/test/java/org/mapstruct/ap/test/collection/adder/_target/TargetOnlyGetter.java, processor/src/test/java/org/mapstruct/ap/test/collection/adder/_target/TargetViaTargetType.java, processor/src/test/java/org/mapstruct/ap/test/collection/adder/_target/TargetWithoutSetter.java, processor/src/test/java/org/mapstruct/ap/test/collection/defaultimplementation/DefaultCollectionImplementationTest.java, processor/src/test/java/org/mapstruct/ap/test/collection/defaultimplementation/NoSetterCollectionMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/collection/defaultimplementation/Target.java, processor/src/test/java/org/mapstruct/ap/test/collection/defaultimplementation/TargetFoo.java, processor/src/test/java/org/mapstruct/ap/test/collection/immutabletarget/ImmutableProductTest.java, processor/src/test/java/org/mapstruct/ap/test/collection/map/MapMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/BeanMapper.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/WildCardTest.java
Fix minor warnings in package test.collection:
remove unnecessary generic-type in collections,
remove unnecessary exception from signature,
replace months numbers on Calendar constants
=> Fix minor warnings in package test.collection

processor/src/test/java/org/mapstruct/ap/internal/model/source/SelectionParametersTest.java, processor/src/test/java/org/mapstruct/ap/internal/util/NativeTypesTest.java, processor/src/test/java/org/mapstruct/ap/internal/util/StringsTest.java, processor/src/test/java/org/mapstruct/ap/spi/util/IntrospectorUtilsTest.java, processor/src/test/java/org/mapstruct/ap/test/abstractclass/AbstractReferencedMapper.java, processor/src/test/java/org/mapstruct/ap/test/abstractclass/Source.java, processor/src/test/java/org/mapstruct/ap/test/array/ArrayMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/builtin/BuiltInTest.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/CallbackMethodTest.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/Invocation.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/Source.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/Target.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/ongeneratedmethods/CompanyMapperPostProcessing.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/ongeneratedmethods/MappingResultPostprocessorTest.java, processor/src/test/java/org/mapstruct/ap/test/callbacks/returning/CallbacksWithReturnValuesTest.java, processor/src/test/java/org/mapstruct/ap/test/complex/CarMapperTest.java, processor/src/test/java/org/mapstruct/ap/test/context/Node.java, processor/src/test/java/org/mapstruct/ap/test/context/SelfContainingCycleContext.java, processor/src/test/java/org/mapstruct/ap/test/conversion/date/DateConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/nativetypes/CharConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/decorator/DecoratorTest.java, processor/src/test/java/org/mapstruct/ap/test/decorator/jsr330/Jsr330DecoratorTest.java, processor/src/test/java/org/mapstruct/ap/test/decorator/spring/constructor/SpringDecoratorTest.java, processor/src/test/java/org/mapstruct/ap/test/decorator/spring/field/SpringDecoratorTest.java
Fix minor warnings in tests, packages internal, spi and some others packages:
remove unnecessary generic-type in collections, simplify conditions,
remove unnecessary exception from signature,
replace months numbers on Calendar constants
=> Fix minor warnings in tests, packages internal, spi and some others packages

processor/src/main/java/org/mapstruct/ap/internal/conversion/Conversions.java, processor/src/main/java/org/mapstruct/ap/internal/model/ContainerMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/Field.java, processor/src/main/java/org/mapstruct/ap/internal/model/MappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/NestedTargetPropertyMappingHolder.java, processor/src/main/java/org/mapstruct/ap/internal/model/SupportingConstructorFragment.java, processor/src/main/java/org/mapstruct/ap/internal/model/SupportingField.java, processor/src/main/java/org/mapstruct/ap/internal/model/SupportingMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/dependency/Node.java, processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java, processor/src/main/java/org/mapstruct/ap/internal/util/workarounds/EclipseAsMemberOfWorkaround.java
Simplify conditions in package org.mapstruct.ap.internal.model 
and classes: Conversions.java, MappingResolverImpl.java,  
EclipseAsMemberOfWorkaround.java
=> Simplify conditions in package org.mapstruct.ap.internal.model and other classes

processor/src/main/java/org/mapstruct/ap/internal/model/dependency/GraphAnalyzer.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/BeanMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/Mapping.java
Simplify consistent checks in class Mapping
=> Simplify consistent checks in class Mapping

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/AbstractReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/MappingReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/MappingReferences.java, processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/SourceReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/TargetReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/Mapping.java, processor/src/test/java/org/mapstruct/ap/test/dependency/OrderingTest.java, processor/src/test/java/org/mapstruct/ap/test/namesuggestion/SuggestMostSimilarNameTest.java, processor/src/test/java/org/mapstruct/ap/test/namesuggestion/erroneous/PersonGarageWrongSourceMapper.java
This PR is some general cleanup and refactoring I did as part of #1406, but is not really part of the business of 1406. So I split it off to make it more manageable.
=> Refactoring of BeanMapping and Source/TargetReferences (common base class)

processor/src/main/java/org/mapstruct/ap/internal/model/ForgedMethod.java
@sjaakd have done this refactoring in https://github.com/mapstruct/mapstruct/pull/1868 . I fixed only minor warning in this PR.
=> #1088 Refactor constructor ForgedMethod

core/src/main/java/org/mapstruct/DecoratedWith.java, documentation/src/main/asciidoc/chapter-12-customizing-mapping.asciidoc
I didn't find other lines about this experimental feature
Fixes #1773
=> #1773 Update documentation: componentModel=jsr330 with @DecoratedWith not longer experimental

processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java
=>  #1914 Remove unused method Type.isAnnotatedWith

processor/src/main/java/org/mapstruct/ap/spi/DefaultAccessorNamingStrategy.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1799/Issue1799Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1799/Issue1799Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1799/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1799/Target.java
=> #1799 Fluent setters starting with set should work properly

processor/src/main/java/org/mapstruct/ap/internal/model/AbstractMappingMethodBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/BuilderFinisherMethodResolver.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/TargetReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/BeanMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/util/MapperConfiguration.java
=>  #1911 Change return type MapperConfiguration.getBuilderPrism from Optional<BuilderPrism> to BuilderPrism

core/src/main/java/org/mapstruct/BeanMapping.java, core/src/main/java/org/mapstruct/Builder.java, core/src/main/java/org/mapstruct/InheritInverseConfiguration.java, core/src/main/java/org/mapstruct/IterableMapping.java, core/src/main/java/org/mapstruct/MapMapping.java, core/src/main/java/org/mapstruct/Mapper.java, core/src/main/java/org/mapstruct/MapperConfig.java, core/src/main/java/org/mapstruct/Mapping.java, core/src/main/java/org/mapstruct/MappingTarget.java, core/src/main/java/org/mapstruct/Mappings.java, core/src/main/java/org/mapstruct/Qualifier.java, core/src/main/java/org/mapstruct/TargetType.java, core/src/main/java/org/mapstruct/ValueMappings.java
Fixes https://github.com/mapstruct/mapstruct/issues/166
=> #166 Add code-examples to Javadoc of org.mapstruct.* annotations

documentation/src/main/asciidoc/chapter-3-defining-a-mapper.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/MappingReferences.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/Mapping.java, processor/src/test/java/org/mapstruct/ap/test/targetthis/ConfictsResolvedNestedMapper.java, processor/src/test/java/org/mapstruct/ap/test/targetthis/CustomerDTO.java, processor/src/test/java/org/mapstruct/ap/test/targetthis/CustomerItem.java, processor/src/test/java/org/mapstruct/ap/test/targetthis/ErroneousNestedMapper.java, processor/src/test/java/org/mapstruct/ap/test/targetthis/FlatteningMapper.java, processor/src/test/java/org/mapstruct/ap/test/targetthis/ItemDTO.java, processor/src/test/java/org/mapstruct/ap/test/targetthis/NestedMapper.java, processor/src/test/java/org/mapstruct/ap/test/targetthis/OrderDTO.java, processor/src/test/java/org/mapstruct/ap/test/targetthis/OrderItem.java, processor/src/test/java/org/mapstruct/ap/test/targetthis/SimpleMapper.java, processor/src/test/java/org/mapstruct/ap/test/targetthis/SimpleMapperWithIgnore.java, processor/src/test/java/org/mapstruct/ap/test/targetthis/TargetThisMappingTest.java
I'll probably need to add more properties to make a bit more realistic
=> #1918 multiple target this mappings

processor/src/test/java/org/mapstruct/ap/testutil/assertions/JavaFileAssert.java, processor/src/test/java/org/mapstruct/ap/testutil/compilation/model/CompilationOutcomeDescriptor.java, processor/src/test/java/org/mapstruct/ap/testutil/compilation/model/DiagnosticDescriptor.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/AnnotationProcessorTestRunner.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/CompilingStatement.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/FilteringParentClassLoader.java
=> #1921 Fix minor warnings in testutil

processor/src/test/java/org/mapstruct/ap/test/bugs/_1742/Issue1742Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1742/Issue1742Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1742/NestedSource.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1742/NestedTarget.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1742/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1742/Target.java
Mostly to make the backport of the fix easier
=> #1742 Add test case

processor/src/main/java/org/mapstruct/ap/internal/model/NestedTargetPropertyMappingHolder.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1828/CompleteAddress.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1828/Employee.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1828/FirstMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1828/GeneralAddress.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1828/Issue1828Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1828/Person.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1828/SpecialAddress.java
Fixes #1828 for the 1.3.1 release
=> #1828 Use update method when nested property of target is populated with multiple nested properties of source

processor/src/main/java/org/mapstruct/ap/internal/model/source/BeanMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SelectionParameters.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1821/Issue1821Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1821/Issue1821Test.java
(cherry picked from commit ade4f4d7e2ab87b2e0f113221d3fc9a6729f78cc)
=> #1821 nullpointer due to @BeanMapping via inheritance (#1822)

processor/src/main/java/org/mapstruct/ap/internal/util/JavaStreamConstants.java
=> #1944 Remove unused constants in JavaStreamConstants

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/LifecycleCallbackMethodReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/ObjectFactoryMethodResolver.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/ParameterProvidedMethods.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java, processor/src/main/java/org/mapstruct/ap/internal/util/workarounds/EclipseAsMemberOfWorkaround.java
=> #1948 Fix minor warnings with using collection in package model and util

processor/src/main/java/org/mapstruct/ap/internal/model/MethodReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Parameter.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SelectionParameters.java
=> #1946 Simplify conditions in classes: Parameter, SelectionParameters, MethodReference, PropertyMapping

processor/src/main/java/org/mapstruct/ap/internal/model/NestedTargetPropertyMappingHolder.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java
=> #1951 Use Map.computeIfAbsent in NestedTargetPropertyMappingHolder

integrationtest/src/test/resources/java8Test/src/main/java/org/mapstruct/ap/test/bugs/_636/SourceTargetBaseMapper.java, integrationtest/src/test/resources/java8Test/src/main/java/org/mapstruct/ap/test/bugs/_636/SourceTargetMapper.java, integrationtest/src/test/resources/lombokBuilderTest/src/main/java/org/mapstruct/itest/lombok/Person.java, integrationtest/src/test/resources/lombokBuilderTest/src/test/java/org/mapstruct/itest/lombok/LombokMapperTest.java, processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/CarMapper.java, processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/NullValueMappingTest.java
=> #1953 Fix TODO items in integration test

core/src/main/java/org/mapstruct/Mapping.java, core/src/main/java/org/mapstruct/Mappings.java, documentation/src/main/asciidoc/chapter-3-defining-a-mapper.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/source/Mapping.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MethodRetrievalProcessor.java, processor/src/test/java/org/mapstruct/ap/test/mappingcomposition/BoxDto.java, processor/src/test/java/org/mapstruct/ap/test/mappingcomposition/BoxEntity.java, processor/src/test/java/org/mapstruct/ap/test/mappingcomposition/CompositionTest.java, processor/src/test/java/org/mapstruct/ap/test/mappingcomposition/ShelveDto.java, processor/src/test/java/org/mapstruct/ap/test/mappingcomposition/ShelveEntity.java, processor/src/test/java/org/mapstruct/ap/test/mappingcomposition/StorageMapper.java, processor/src/test/java/org/mapstruct/ap/test/mappingcomposition/ToEntity.java
As much as possible used existing functionality. Recur though nested meta-annotations, excluding already found ones. Exclude also our own and java annotations (`@Documented` and the likes).
=> #807 meta annotations and duck typing

readme.md
Not the most productive of PRs, but hope it prevents someone bumping into the bug in 1.3.0 to do with field names that start with the three letters 'set'. Thanks for building a great tool.
=> Updated versions on readme.md to 1.3.1.Final

processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java
and fix some smaller Javadoc typos.
=> Fix Javadoc of resolveViaMethodAndConversion

.travis.yml, integrationtest/src/test/java/org/mapstruct/itest/tests/MavenIntegrationTest.java, integrationtest/src/test/resources/recordsTest/pom.xml, integrationtest/src/test/resources/recordsTest/src/main/java/org/mapstruct/itest/records/CustomerDto.java, integrationtest/src/test/resources/recordsTest/src/main/java/org/mapstruct/itest/records/CustomerEntity.java, integrationtest/src/test/resources/recordsTest/src/main/java/org/mapstruct/itest/records/CustomerMapper.java, integrationtest/src/test/resources/recordsTest/src/test/java/org/mapstruct/itest/records/RecordsTest.java, parent/pom.xml, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/main/java/org/mapstruct/ap/internal/util/Filters.java
=> #2014 Add support for mapping from Java 14 records

integrationtest/src/test/java/org/mapstruct/itest/tests/MavenIntegrationTest.java, integrationtest/src/test/resources/moduleInfoTest/pom.xml, integrationtest/src/test/resources/moduleInfoTest/src/main/java/module-info.java, integrationtest/src/test/resources/moduleInfoTest/src/main/java/org/mapstruct/itest/modules/CustomerDto.java, integrationtest/src/test/resources/moduleInfoTest/src/main/java/org/mapstruct/itest/modules/CustomerEntity.java, integrationtest/src/test/resources/moduleInfoTest/src/main/java/org/mapstruct/itest/modules/CustomerMapper.java, integrationtest/src/test/resources/moduleInfoTest/src/test/java/org/mapstruct/itest/modules/ModulesTest.java, processor/src/main/java/org/mapstruct/ap/internal/conversion/Conversions.java
=> #2060: MapStruct should work properly on the module path

integrationtest/src/test/java/org/mapstruct/itest/tests/MavenIntegrationTest.java, integrationtest/src/test/resources/faultyAstModifyingAnnotationProcessorTest/generator/pom.xml, integrationtest/src/test/resources/faultyAstModifyingAnnotationProcessorTest/generator/src/main/java/org/mapstruct/itest/faultyAstModifyingProcessor/AstModifyingProcessorSaysYes.java, integrationtest/src/test/resources/faultyAstModifyingAnnotationProcessorTest/generator/src/main/java/org/mapstruct/itest/faultyAstModifyingProcessor/FaultyAstModifyingProcessor.java, integrationtest/src/test/resources/faultyAstModifyingAnnotationProcessorTest/generator/src/main/java/org/mapstruct/itest/faultyAstModifyingProcessor/FaultyStaticAstModifyingProcessor.java, integrationtest/src/test/resources/faultyAstModifyingAnnotationProcessorTest/generator/src/main/resources/META-INF/services/org.mapstruct.ap.spi.AstModifyingAnnotationProcessor, integrationtest/src/test/resources/faultyAstModifyingAnnotationProcessorTest/pom.xml, integrationtest/src/test/resources/faultyAstModifyingAnnotationProcessorTest/usage/pom.xml, integrationtest/src/test/resources/faultyAstModifyingAnnotationProcessorTest/usage/src/main/java/org/mapstruct/itest/faultyAstModifyingProcessor/usage/Order.java, integrationtest/src/test/resources/faultyAstModifyingAnnotationProcessorTest/usage/src/main/java/org/mapstruct/itest/faultyAstModifyingProcessor/usage/OrderDto.java, integrationtest/src/test/resources/faultyAstModifyingAnnotationProcessorTest/usage/src/main/java/org/mapstruct/itest/faultyAstModifyingProcessor/usage/OrderMapper.java, integrationtest/src/test/resources/faultyAstModifyingAnnotationProcessorTest/usage/src/test/java/org/mapstruct/itest/faultyAstModifyingProcessor/usage/FaultyAstModifyingTestTest.java, processor/src/main/java/org/mapstruct/ap/internal/util/AnnotationProcessorContext.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1159/FaultyAstModifyingAnnotationProcessor.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1159/Issue1159Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1159/Issue1159Test.java
=> #1159: Do not fail loading AnnotationProcessorContext if loading AstModifyingAnnotationProcessor fails

processor/src/main/resources/org/mapstruct/ap/internal/model/BeanMappingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/ArrayCopyWrapper.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/SetterWrapperForCollectionsAndMapsWithNullCheck.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_2109/Issue2109Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2109/Issue2109Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2109/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2109/Target.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/constructor/nestedsource/ArtistToChartEntryImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/constructor/nestedtarget/ChartEntryToArtistImpl.java
=> #2109 Generate correct array assignment for constructor parameter mapping

processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingMethodOptions.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2101/Issue2101AdditionalMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2101/Issue2101Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2101/Issue2101Test.java
Possibly need to add some unit test.. Although quite some testcases failed when I implemented it wrong 😄
=> #2101 inherited properties need to be analysed against redefined properties when inheriting mappings

processor/src/main/java/org/mapstruct/ap/internal/model/ForgedMethod.java, processor/src/main/java/org/mapstruct/ap/internal/util/Strings.java, processor/src/test/java/org/mapstruct/ap/internal/util/StringsTest.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2142/Issue2142Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2142/Issue2142Test.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_2142/Issue2142MapperImpl.java
=> Strip leading underscores when sanitizing identifiers

processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingMethodOptions.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2149/Erroneous2149Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2149/Issue2149Test.java, processor/src/test/java/org/mapstruct/ap/test/ignore/inherit/IgnorePropertyTest.java, processor/src/test/java/org/mapstruct/ap/test/ignore/inherit/ToolMapper.java
This fixes an ArrayIndexOutOfBoundsException when they were used together
Fixes #2149
=> #2149 Do not allow using BeanMapping(ignoreByDefault = true) in combination with Mapping(target = ".")

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2170/Issue2170Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2170/dto/AddressDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2170/dto/PersonDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2170/entity/Address.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2170/entity/Person.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2170/mapper/AddressMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2170/mapper/EntityMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2170/mapper/PersonMapper.java
=> #2170 Make sure that an import is created for constructor mapping defined variables

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2174/Issue2174Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2174/UserMapper.java
=> #2174 Forged methods should inherit all thrown exceptions from their property mappings

integrationtest/src/test/resources/recordsTest/src/main/java/org/mapstruct/itest/records/CustomerMapper.java, integrationtest/src/test/resources/recordsTest/src/main/java/org/mapstruct/itest/records/GenericRecord.java, integrationtest/src/test/resources/recordsTest/src/test/java/org/mapstruct/itest/records/RecordsTest.java, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/util/accessor/ParameterElementAccessor.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2177/Issue2177Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2177/Issue2177Test.java
=> #2177 Mapping into a generic class with a typed constructor argument should work

processor/src/main/java/org/mapstruct/ap/internal/processor/DefaultVersionInformation.java
Starting from IntelliJ 2020.3 (Build 203.4203.26) the ProcessingEnvironment is wrapped in a Proxy class by IntelliJ.
MapStruct should gracefully handle that and not throw an NPE.
Additionally, we should do best effort to put the used compiler in the generated annotation info
Fixes #2215
=> #2215: Avoid NPE in IntelliJ EAP 2020.3

processor/src/main/java/org/mapstruct/ap/internal/conversion/ConversionUtils.java, processor/src/main/java/org/mapstruct/ap/internal/conversion/Conversions.java, processor/src/main/java/org/mapstruct/ap/internal/conversion/StringBuilderToStringConversion.java, processor/src/test/java/org/mapstruct/ap/test/conversion/string/Source.java, processor/src/test/java/org/mapstruct/ap/test/conversion/string/StringConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/string/Target.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/conversion/string/SourceTargetMapperImpl.java
Hi, let me know if there is anything wrong. Thanks.
Fixes #597
=> #597 Built-In conversion between String and StringBuilder

processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2245/Issue2245Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2245/TestMapper.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_2245/TestMapperImpl.java
=> #2245 Local variable should be created when using default value

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2251/Issue2251Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2251/Issue2251Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2251/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2251/Target.java
=> #2251 Fix incorrect code generated for constructor mapping from implicit source parameter matching

processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2263/Erroneous2263Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2263/Issue2263Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2263/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2263/Target.java
=> #2263 Fix IndexOutOfBoundsException when resolving TypeVar to a Type

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2253/Issue2253Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2253/TestMapper.java
=> #2253 remove unmapped source properties when source parameter is directly mapped

processor/src/main/java/org/mapstruct/ap/internal/model/ValueMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/value/string2enum/StringToEnumMappingTest.java
=> #2350 Generate core string to enum mapping when AnyRemaining or AnyUnmapped is not used

documentation/src/main/asciidoc/chapter-10-advanced-mapping-options.asciidoc, documentation/src/main/asciidoc/chapter-6-mapping-collections.asciidoc, documentation/src/main/asciidoc/chapter-7-mapping-streams.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_1453/Issue1453MapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_1707/ConverterImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithNcvsAlwaysMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithNvmsDefaultMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithNvmsNullMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithPresenceCheckMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/collection/defaultimplementation/SourceTargetMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/updatemethods/CompanyMapper1Impl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/updatemethods/selection/DepartmentMapperImpl.java
=> #2303 Generated code should use iteration order preserving LinkedHash(Map|Set) instead of Hash(Map|Set)

.github/workflows/java-ea.yml, integrationtest/src/test/java/org/mapstruct/itest/tests/MavenIntegrationTest.java, integrationtest/src/test/resources/recordsCrossModuleTest/api/pom.xml, integrationtest/src/test/resources/recordsCrossModuleTest/api/src/main/java/org/mapstruct/itest/records/api/CustomerDto.java, integrationtest/src/test/resources/recordsCrossModuleTest/mapper/pom.xml, integrationtest/src/test/resources/recordsCrossModuleTest/mapper/src/main/java/org/mapstruct/itest/records/mapper/CustomerEntity.java, integrationtest/src/test/resources/recordsCrossModuleTest/mapper/src/main/java/org/mapstruct/itest/records/mapper/CustomerMapper.java, integrationtest/src/test/resources/recordsCrossModuleTest/mapper/test/java/org/mapstruct/itest/records/mapper/RecordsTest.java, integrationtest/src/test/resources/recordsCrossModuleTest/pom.xml
=> #2375 Add records cross module integration test

documentation/pom.xml, documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc
=> #2483: Update Asciidoctor to latest versions

processor/src/main/java/org/mapstruct/ap/internal/model/ForgedMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2478/Issue2478Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2478/Issue2478Test.java
=> #2478 Make sure that forged methods do not generate duplicate method parameters

processor/src/test/java/org/mapstruct/ap/test/bugs/_2501/Issue2501Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2501/Issue2501Test.java
Add test case related to #2501
=> #2501 Add test case

documentation/src/main/asciidoc/chapter-3-defining-a-mapper.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/SourceReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/presence/SourceReferenceContainsKeyPresenceCheck.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/main/java/org/mapstruct/ap/internal/util/ValueProvider.java, processor/src/main/java/org/mapstruct/ap/internal/util/accessor/AccessorType.java, processor/src/main/java/org/mapstruct/ap/internal/util/accessor/MapValueAccessor.java, processor/src/main/java/org/mapstruct/ap/internal/util/accessor/MapValuePresenceChecker.java, processor/src/main/resources/org/mapstruct/ap/internal/model/presence/SourceReferenceContainsKeyPresenceCheck.ftl, processor/src/test/java/org/mapstruct/ap/test/frommap/FromMapMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/frommap/MapToBeanDefinedMapper.java, processor/src/test/java/org/mapstruct/ap/test/frommap/MapToBeanFromMapAndNestedMap.java, processor/src/test/java/org/mapstruct/ap/test/frommap/MapToBeanFromMapAndNestedSource.java, processor/src/test/java/org/mapstruct/ap/test/frommap/MapToBeanFromMultipleSources.java, processor/src/test/java/org/mapstruct/ap/test/frommap/MapToBeanImplicitMapper.java, processor/src/test/java/org/mapstruct/ap/test/frommap/MapToBeanImplicitUnmappedSourcePolicyMapper.java, processor/src/test/java/org/mapstruct/ap/test/frommap/MapToBeanNonStringMapAsMultiSourceMapper.java, processor/src/test/java/org/mapstruct/ap/test/frommap/MapToBeanRawMapMapper.java, processor/src/test/java/org/mapstruct/ap/test/frommap/MapToBeanTypeCheckMapper.java, processor/src/test/java/org/mapstruct/ap/test/frommap/MapToBeanUpdateImplicitMapper.java, processor/src/test/java/org/mapstruct/ap/test/frommap/MapToBeanUsingMappingMethodMapper.java, processor/src/test/java/org/mapstruct/ap/test/frommap/MapToBeanWithDefaultMapper.java, processor/src/test/java/org/mapstruct/ap/test/frommap/ObjectMapToBeanWithQualifierMapper.java, processor/src/test/java/org/mapstruct/ap/test/frommap/StringMapToBeanMapper.java, processor/src/test/java/org/mapstruct/ap/test/frommap/StringMapToBeanWithCustomPresenceCheckMapper.java
This supersedes #2317. @ckosmowski did an amazing job, I only polished it a bit and fixed the merge conflicts.
@ckosmowski let me know if you don't agree with some of my changes.
Fixes #1075
Open points:
=> Mapping from map to bean

processor/src/main/java/org/mapstruct/ap/spi/CaseEnumTransformationStrategy.java, processor/src/test/java/org/mapstruct/ap/test/value/nametransformation/EnumNameTransformationStrategyTest.java
=> #2525 add available transformations to CaseEnumTransformationStrategy exception

processor/src/main/java/org/mapstruct/ap/internal/conversion/ReverseConversion.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2530/Issue2530Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2530/Issue2530Test.java
=> #2530: bugfix for ReverseConversion with SupportingFields.

processor/src/main/java/org/mapstruct/ap/internal/conversion/ReverseConversion.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2544/Issue2544Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2544/Issue2544Test.java
=> #2544: ReverseConversion now also passes HelperMethods on.

processor/src/test/java/org/mapstruct/ap/test/bugs/_2544/Issue2544Test.java
=> Add locale to test

documentation/src/main/asciidoc/chapter-2-set-up.asciidoc, processor/src/main/java/org/mapstruct/ap/MappingProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/DefaultOptions.java, processor/src/main/java/org/mapstruct/ap/internal/option/Options.java, processor/src/test/java/org/mapstruct/ap/test/unmappedsource/SourceTargetMapperWithoutMapperConfig.java, processor/src/test/java/org/mapstruct/ap/test/unmappedsource/UnmappedSourceTest.java
Hello! I added unmappedSourcePolicy as an annotation processor argument. Please let me know if I missed something.
Resolves #2555
=> #2555 Add unmappedSourcePolicy annotation processor argument

processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2541/Issue2541Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2541/Issue2541Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2541/Nullable.java
=> #2541 fix incorrect name for TypeVar with ElementType.TYPE_USE for javac-with-errorprone

integrationtest/src/test/resources/recordsTest/src/main/java/org/mapstruct/itest/records/Car.java, integrationtest/src/test/resources/recordsTest/src/main/java/org/mapstruct/itest/records/CarAndWheelMapper.java, integrationtest/src/test/resources/recordsTest/src/main/java/org/mapstruct/itest/records/CarDto.java, integrationtest/src/test/resources/recordsTest/src/main/java/org/mapstruct/itest/records/WheelPosition.java, integrationtest/src/test/resources/recordsTest/src/test/java/org/mapstruct/itest/records/RecordsTest.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java
=> #2554 Records should not treat collections as alternative target accessors

processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2624/Issue2624Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2624/Issue2624Test.java
=> #2624 Nested target methods should be inherited for forged Map to Bean methods

processor/src/main/resources/org/mapstruct/ap/internal/model/BeanMappingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/IterableMappingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/MapMappingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/StreamMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/array/ArrayMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_374/Issue374Test.java, processor/src/test/java/org/mapstruct/ap/test/builder/mappingTarget/simple/BuilderInfoTargetTest.java, processor/src/test/java/org/mapstruct/ap/test/collection/defaultimplementation/DefaultCollectionImplementationTest.java, processor/src/test/java/org/mapstruct/ap/test/collection/map/MapMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/inheritance/InheritanceTest.java, processor/src/test/java/org/mapstruct/ap/test/java8stream/defaultimplementation/DefaultStreamImplementationTest.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/array/ScienceMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithNcvsAlwaysMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithNvmsNullMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithPresenceCheckMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/collection/defaultimplementation/SourceTargetMapperImpl.java
=> #1752 Always return mapping target when using update methods with return

core/src/main/java/org/mapstruct/Mapper.java, core/src/main/java/org/mapstruct/MapperConfig.java, processor/src/main/java/org/mapstruct/ap/internal/model/Decorator.java, processor/src/main/java/org/mapstruct/ap/internal/model/GeneratedType.java, processor/src/main/java/org/mapstruct/ap/internal/model/Mapper.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/DefaultOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/DelegatingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MapperConfigOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MapperOptions.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java, processor/src/test/java/org/mapstruct/ap/test/versioninfo/SuppressTimestampViaMapper.java, processor/src/test/java/org/mapstruct/ap/test/versioninfo/SuppressTimestampViaMapperConfig.java, processor/src/test/java/org/mapstruct/ap/test/versioninfo/VersionInfoTest.java
=> #2225 Add support for suppressing the generation of the timestamp through Mapper and MapperConfig

processor/src/main/java/org/mapstruct/ap/internal/processor/MethodRetrievalProcessor.java, processor/src/test/java/org/mapstruct/ap/test/multisource/MultiSourceMapper.java, processor/src/test/java/org/mapstruct/ap/test/multisource/MultiSourceMapperTest.java
=> #2005 Parameter type should only be checked if we are mapping from a single argument source

processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/test/java/org/mapstruct/ap/test/conditional/expression/ConditionalExpressionTest.java, processor/src/test/java/org/mapstruct/ap/test/conditional/expression/ConditionalWithSourceToTargetExpressionMapper.java, processor/src/test/java/org/mapstruct/ap/test/conditional/qualifier/ConditionalMethodWithSourceToTargetMapper.java, processor/src/test/java/org/mapstruct/ap/test/conditional/qualifier/ConditionalQualifierTest.java
=> #2666 Presence Check should be applied to source parameters when used in `@Mapping`

processor/src/main/java/org/mapstruct/ap/internal/model/source/MethodMatcher.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2673/Issue2673Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2673/Issue2673Test.java
There is a special case where the getCandidates method incorrectly returned true.
Fixes #2673
=> #2673: the getCandidates method now correctly returns false.

documentation/src/main/asciidoc/chapter-10-advanced-mapping-options.asciidoc
=> #2689: documentation: fix example title.

processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/EnumConstantWrapper.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_2704/Issue2704Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2704/TestMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2704/TopLevel.java
=> Fix broken reference to constants within nested enums

documentation/src/main/asciidoc/chapter-10-advanced-mapping-options.asciidoc
=> #2687 Add documentation for NullValueMappingStrategy for collections and maps

documentation/src/main/asciidoc/chapter-4-retrieving-a-mapper.asciidoc
=> #2686 Add documentation about when mappers are injected

documentation/src/main/asciidoc/chapter-3-defining-a-mapper.asciidoc
=> #2719: additional note at builders documentation about before-/aftermapping impact.

documentation/src/main/asciidoc/chapter-10-advanced-mapping-options.asciidoc
=> 2709 Corrected description for example demonstrating default expression

.github/workflows/java-ea.yml, parent/pom.xml
=> #2725 Update tools-gem to 1.0.0.Alpha3 and run GitHub Action with Java 19-ea

integrationtest/src/test/java/org/mapstruct/itest/tests/MavenIntegrationTest.java, integrationtest/src/test/resources/cdiTest/pom.xml, integrationtest/src/test/resources/cdiTest/src/test/java/org/mapstruct/itest/cdi/CdiBasedMapperTest.java, parent/pom.xml
=> #2468 Update needed dependencies for running CDI tests on Java 16+

documentation/src/main/asciidoc/chapter-2-set-up.asciidoc, documentation/src/main/asciidoc/chapter-3-defining-a-mapper.asciidoc, processor/src/main/java/org/mapstruct/ap/MappingProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/option/Options.java, processor/src/main/java/org/mapstruct/ap/internal/util/AnnotationProcessorContext.java, processor/src/test/java/org/mapstruct/ap/test/builder/off/SimpleNotRealyImmutableBuilderTest.java, processor/src/test/java/org/mapstruct/ap/test/builder/off/SimpleWithBuilderMapper.java
=> #1661 Add support for globally disabling builders

processor/src/main/java/org/mapstruct/ap/internal/model/MethodReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/ObjectFactoryMethodResolver.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/resources/org/mapstruct/ap/internal/model/MethodReference.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_1997/Car.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1997/CarDetail.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1997/CarInsurance.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1997/CarInsuranceMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1997/Issue1997Test.java
=> #1997 Use builders to construct empty objects in update wrapper

documentation/src/main/asciidoc/chapter-10-advanced-mapping-options.asciidoc
=> #2715: Updated documentation to reflect impact of nullValuePropertyMappingStrategy on conditions.

processor/src/main/resources/org/mapstruct/ap/internal/model/MethodReference.ftl, processor/src/test/java/org/mapstruct/ap/test/selection/generics/GenericMapperBase.java, processor/src/test/java/org/mapstruct/ap/test/selection/generics/GenericMapperBaseTest.java
=> #2755: use raw Type when called a static method.

processor/src/main/java/org/mapstruct/ap/internal/model/MappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2807/Issue2807Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2807/SpringLifeCycleMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2807/after/AfterMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2807/before/BeforeMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2807/beforewithtarget/BeforeWithTarget.java
=> #2807: Include LifeCycleMethod importTypes in the list of importTypes.

documentation/src/main/asciidoc/chapter-14-third-party-api-integration.asciidoc
the modification about issue #2858
=> Doc: correct the annotation processor version

readme.md
=> #2851 Fix typo in readme

parent/pom.xml
=> #2835 Upgrade jacoco-maven-plugin to latest 0.8.8 to support Java 17

documentation/src/main/asciidoc/chapter-13-using-mapstruct-spi.asciidoc
=> #2739: documentation enhancement on explaining SPI usage.

processor/src/test/java/org/mapstruct/ap/test/conversion/string/StringConversionTest.java
=> #2846 add testcase

processor/src/main/java/org/mapstruct/ap/internal/processor/MapperAnnotatedFormattingMessenger.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2867/Issue2867BaseMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2867/Issue2867Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2867/Issue2867Test.java
=> #2867 Fix NPE when reporting message on parent mappers

.github/workflows/main.yml
=> #2870 Use codecov action v2

.github/workflows/java-ea.yml, .github/workflows/main.yml
Run tests with Java 18
Change actions/checkout to v3
Change actions/setup-java to v3
=> Update GitHub actions

processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2880/Issue2880Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2880/Issue2880Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2880/Outer.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2880/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2880/Target.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2880/TargetData.java
=> Fix missing import for array mapping methods

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2891/Issue2891Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2891/Issue2891Test.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_2891/Issue2891MapperImpl.java
Fixes https://github.com/mapstruct/mapstruct/issues/2891
=> #2891 Fix subclass mapping while superclass has non-empty constructor

integrationtest/src/test/resources/protobufBuilderTest/pom.xml, parent/pom.xml
=> #2922 Fix protobuf tests for M1 Macs

documentation/src/main/asciidoc/chapter-3-defining-a-mapper.asciidoc
=> #2929 Improve documentation for `BeanMapping#ignoreByDefault`

processor/src/main/resources/org/mapstruct/ap/internal/model/macro/CommonMacros.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_2901/ConditionWithTargetTypeOnCollectionMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2901/Issue2901Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2901/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2901/Target.java
=> #2901: fix for TargetType annotation on a Condition annotated method for a Collection value.

processor/src/main/java/org/mapstruct/ap/internal/model/ForgedMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2839/Car.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2839/CarDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2839/CarMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2839/Id.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2839/Issue2839Exception.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2839/Issue2839Test.java
=> #2839 keep thrown types when creating a new ForgedMethod with the same arguments

processor/src/main/java/org/mapstruct/ap/internal/model/source/BeanMappingOptions.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2949/Issue2949Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2949/Issue2949Test.java
=> #2949 Do not inverse inherit BeanMapping#ignoreUnmappedSourceProperties

core/src/main/java/org/mapstruct/MappingConstants.java, integrationtest/src/test/resources/fullFeatureTest/pom.xml, parent/pom.xml, processor/pom.xml, processor/src/main/java/org/mapstruct/ap/internal/gem/MappingConstantsGem.java, processor/src/main/java/org/mapstruct/ap/internal/processor/CdiComponentProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/processor/JakartaCdiComponentProcessor.java, processor/src/main/resources/META-INF/services/org.mapstruct.ap.internal.processor.ModelElementProcessor, processor/src/test/java/org/mapstruct/ap/test/gem/ConstantTest.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/cdi/_default/CdiDefaultCompileOptionFieldMapperTest.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/cdi/_default/CustomerCdiDefaultCompileOptionFieldMapper.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/cdi/_default/GenderCdiDefaultCompileOptionFieldMapper.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/cdi/jakarta/CustomerCdiDefaultCompileOptionFieldMapper.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/cdi/jakarta/GenderCdiDefaultCompileOptionFieldMapper.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/cdi/jakarta/JakartaCdiAndCdiDefaultCompileOptionFieldMapperTest.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/cdi/jakarta/JakartaCdiCdiDefaultCompileOptionFieldMapperTest.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/jakarta_cdi/_default/CustomerJakartaCdiDefaultCompileOptionFieldMapper.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/jakarta_cdi/_default/GenderJakartaCdiDefaultCompileOptionFieldMapper.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/jakarta_cdi/_default/JakartaCdiAndCdiDefaultCompileOptionFieldMapperTest.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/jakarta_cdi/_default/JakartaCdiDefaultCompileOptionFieldMapperTest.java, processor/src/test/java/org/mapstruct/ap/testutil/WithCdi.java, processor/src/test/java/org/mapstruct/ap/testutil/WithJakartaCdi.java
=> Add support for Jakarta CDI

documentation/src/main/asciidoc/chapter-2-set-up.asciidoc
=> #2928 Add IntelliJ and Eclipse plugin information

processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2897/Issue2897Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2897/Issue2897Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2897/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2897/Target.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2897/util/Util.java
=> #2897 Always import types defined in `Mapper#imports`

processor/src/main/resources/org/mapstruct/ap/internal/model/MethodReference.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/MethodReferencePresenceCheck.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/common/SourceRHS.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_2937/Issue2937Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2937/Issue2937Test.java
=> #2937 Fix conditional check for collections with adders

processor/src/main/java/org/mapstruct/ap/internal/model/GeneratedType.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2907/Issue2907Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2907/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2907/SourceNested.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2907/Target.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2907/mapper/Issue2907Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2945/Issue2945Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2945/Issue2945Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2945/_target/EnumHolder.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2945/_target/Target.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2945/source/Source.java
Make sure that GeneratedType always gets the imported types
from a Type before adding them
Fixes #2945 
Fixes #2907
=> #2945 Stabilise top level imports

processor/src/main/resources/org/mapstruct/ap/internal/model/Annotation.ftl, processor/src/test/java/org/mapstruct/ap/test/annotatewith/AnnotateWithTest.java, processor/src/test/java/org/mapstruct/ap/test/annotatewith/CustomNamedMapper.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/annotatewith/CustomNamedMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/annotatewith/MultipleArrayValuesMapperImpl.java
Fixes #2895 
This is a try at improving the generated annotations as explained in the issue.
What do you think @Zegveld?
=> #2895 Generate more readable annotations

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/DeepCloneMapper.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/DeepCloneMethodMapper.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/SubclassMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/mappables/Car.java
=> #3018: subclassmapping now correctly applies mappingcontrol configuration.

processor/src/main/java/org/mapstruct/ap/internal/model/source/BeanMappingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingMethodOptions.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2743/Issue2743Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2743/Issue2743Test.java
=> #2743 BeanMappingOptions should not be inherited for forged methods

integrationtest/src/test/java/org/mapstruct/itest/tests/FullFeatureCompilationExclusionCliEnhancer.java, integrationtest/src/test/resources/fullFeatureTest/pom.xml, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MethodMatcher.java, processor/src/test/java/org/mapstruct/ap/test/selection/methodgenerics/wildcards/LifecycleIntersectionMapper.java, processor/src/test/java/org/mapstruct/ap/test/selection/methodgenerics/wildcards/WildCardTest.java
=> #3036 Fix compile errors when intersection types are used in lifecycle methods

distribution/pom.xml, distribution/src/main/assembly/dist.xml, parent/pom.xml
=> #3039 Upgrade FreeMarker to 2.3.31

processor/src/main/java/org/mapstruct/ap/internal/model/AbstractMappingMethodBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/ValueMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3015/Issue3015Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3015/Issue3015Test.java
=> #3015 No need to pass annotations to the forge method

core/src/main/java/org/mapstruct/CollectionMappingStrategy.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2952/Issue2952Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2952/Issue2952Test.java, processor/src/test/java/org/mapstruct/ap/test/collection/immutabletarget/CupboardEntityOnlyGetter.java, processor/src/test/java/org/mapstruct/ap/test/collection/immutabletarget/CupboardNoSetterMapper.java, processor/src/test/java/org/mapstruct/ap/test/collection/immutabletarget/ImmutableProductTest.java
=> #2952 Do not treat a getter as an alternative write accessor when using CollectionMappingStrategy#TARGET_IMMUTABLE

processor/src/test/java/org/mapstruct/ap/test/bugs/_3077/Issue3077Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3077/Issue3077MapperTest.java
Fixes #3077 
I've added a test case for #3077 as it is slightly different scenario than the fix for #3057 (even though the fix is fixing the same problem)
=> #3077 Add test case

documentation/src/main/asciidoc/chapter-2-set-up.asciidoc, processor/src/main/java/org/mapstruct/ap/MappingProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/DefaultOptions.java, processor/src/main/java/org/mapstruct/ap/internal/option/Options.java, processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/CarListMapper.java, processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/CarListMapperSettingOnMapper.java, processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/CarMapMapper.java, processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/CarMapMapperSettingOnMapper.java, processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/NullValueIterableMappingStrategyTest.java, processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/NullValueMapMappingStrategyTest.java
=> Add support for globally defining nullValueMapMappingStrategy and nullValueIterableMappingStrategy

processor/src/main/resources/org/mapstruct/ap/internal/model/ValueMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_3110/Issue3110Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3110/Issue3110MapperTest.java
Fix #3110 
I was working on something else when i stumbled upon this bug.
I don't know if this is the right way to do a test about something like this or there is a better way.
=> #3110 Fix throws declaration for ValueMapping annotated methods

processor/src/main/java/org/mapstruct/ap/internal/model/source/BeanMappingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingMethodOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SelectionParameters.java, processor/src/test/java/org/mapstruct/ap/test/mappingcontrol/CloningBeanMappingMapper.java, processor/src/test/java/org/mapstruct/ap/test/mappingcontrol/MappingControlTest.java
=> #3135 BeanMapping#mappingControl should be inherited by forged methods

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3142/Issue3142Exception.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3142/Issue3142Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3142/Issue3142WithAfterMappingExceptionMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3142/Issue3142WithBeforeMappingExceptionMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3142/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3142/Target.java
=> #3142 Nested forged methods should declare throws from lifecycle methods

core/src/main/java/org/mapstruct/Mapper.java, core/src/main/java/org/mapstruct/MapperConfig.java, core/src/main/java/org/mapstruct/package-info.java, distribution/pom.xml, parent/pom.xml, readme.md
This PR polishes links in docs.
=> Polish links in docs

documentation/src/main/asciidoc/chapter-2-set-up.asciidoc
=> #3236 Add missing jakarta-cdi to the documentation

processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java, processor/src/test/java/org/mapstruct/ap/test/mappingcontrol/ErroneousBuiltInAndBuiltInMapper.java, processor/src/test/java/org/mapstruct/ap/test/mappingcontrol/ErroneousBuiltInAndMethodMapper.java, processor/src/test/java/org/mapstruct/ap/test/mappingcontrol/ErroneousConversionAndMethodMapper.java, processor/src/test/java/org/mapstruct/ap/test/mappingcontrol/ErroneousMethodAndBuiltInMapper.java, processor/src/test/java/org/mapstruct/ap/test/mappingcontrol/ErroneousMethodAndConversionMapper.java, processor/src/test/java/org/mapstruct/ap/test/mappingcontrol/MappingControlTest.java, processor/src/test/java/org/mapstruct/ap/test/mappingcontrol/NoConversion.java
=> #3186 Do not use conversions in 2-step mapping when they are disabled

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2149/Issue2149Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3158/Issue3158Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3158/Issue3158Test.java
=> #3158 BeanMapping#ignoreByDefault should work properly for constructor properties

processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3159/Issue3159Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3159/Issue3159Test.java
=> #3159 Do null value check for collections with default expression

processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/AdderWrapper.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/SourceRHS.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3165/Issue3165Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3165/Issue3165MapperTest.java
This PR offers a potential fix for the problem that I described in #3165 .
Fixes #3165 
Fixes #3129
=> #3165: support for array to collection with adder preferred

processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3238/ErroneousIssue3238Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3238/Issue3238Test.java
=> #3238 Compile error instead of null pointer exception for invalid ignore with target this

integrationtest/src/test/resources/recordsTest/src/main/java/org/mapstruct/itest/records/Default.java, integrationtest/src/test/resources/recordsTest/src/main/java/org/mapstruct/itest/records/Task.java, integrationtest/src/test/resources/recordsTest/src/main/java/org/mapstruct/itest/records/TaskDto.java, integrationtest/src/test/resources/recordsTest/src/main/java/org/mapstruct/itest/records/TaskMapper.java, integrationtest/src/test/resources/recordsTest/src/test/java/org/mapstruct/itest/records/RecordsTest.java, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java
Hi, this is a small change. Maybe this could make it into 1.6.0. 🙂
=> #3231 prefer record constructor annotated with @Default

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/MappingReferences.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3126/Issue3126Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3126/Issue3126Test.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedbeans/mixed/FishTankMapperImpl.java
=> #3126 Apply target this references in the BeanMappingMethod

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/NestedTargetPropertyMappingHolder.java, processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/SourceReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3144/Issue3144Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3144/Issue3144Test.java, processor/src/test/java/org/mapstruct/ap/test/frommap/MapToBeanUsingMappingMethodMapper.java
=> #3144 Map to Bean should only be possible for single source mappings and if explicitly used in multi source mappings

processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3310/Issue3310Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3310/Issue3310Test.java
=> #3310 Make sure that adders work properly when they are in a generic class

distribution/pom.xml
=> #3340 Update tarLongFileMode to use POSIX

core/src/main/java/org/mapstruct/InjectionStrategy.java, documentation/src/main/asciidoc/chapter-4-retrieving-a-mapper.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/gem/InjectionStrategyGem.java, processor/src/main/java/org/mapstruct/ap/internal/model/AnnotatedSetter.java, processor/src/main/java/org/mapstruct/ap/internal/model/GeneratedType.java, processor/src/main/java/org/mapstruct/ap/internal/model/GeneratedTypeMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/MappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/processor/AnnotationBasedComponentModelProcessor.java, processor/src/main/resources/org/mapstruct/ap/internal/model/AnnotatedSetter.ftl, processor/src/test/java/org/mapstruct/ap/test/decorator/spring/setter/PersonMapper.java, processor/src/test/java/org/mapstruct/ap/test/decorator/spring/setter/PersonMapperDecorator.java, processor/src/test/java/org/mapstruct/ap/test/decorator/spring/setter/SpringDecoratorTest.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/jakarta/setter/CustomerJakartaSetterMapper.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/jakarta/setter/GenderJakartaSetterMapper.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/jakarta/setter/JakartaSetterMapperTest.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/jakarta/setter/SetterJakartaConfig.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/jsr330/setter/CustomerJsr330SetterMapper.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/jsr330/setter/GenderJsr330SetterMapper.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/jsr330/setter/Jsr330SetterMapperTest.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/jsr330/setter/SetterJsr330Config.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/spring/setter/CustomerRecordSpringSetterMapper.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/spring/setter/CustomerSpringSetterMapper.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/spring/setter/GenderSpringSetterMapper.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/spring/setter/SetterSpringConfig.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/spring/setter/SpringSetterMapperTest.java
This is my work in progress for #3229. So far I have been unable to add a new method on the generated mapper. I think everything else is atleast well prepared. For the last bits I could use some support.
=> #3229: Implement InjectionStrategy.SETTER

processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3163/Issue3163Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3163/Issue3163Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3163/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3163/Target.java
=> #3163: Strip wild card when checking for type assignability

documentation/src/main/asciidoc/chapter-14-third-party-api-integration.asciidoc
I have completed a documentation bit about the Lombok compatibility. See https://github.com/mapstruct/mapstruct/issues/3374.
=> #3374 Lombok compatibility documentation

readme.md
=> change master to main branch and fix CI status badge

copyright.txt, processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3413/Erroneous3413Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3413/Issue3413Test.java
=> Expression or condition 

.github/workflows/java-ea.yml, .github/workflows/main.yml, parent/pom.xml, processor/src/test/java/org/mapstruct/ap/test/conversion/jodatime/JodaConversionTest.java
Fix tests not running green on Java 21
Update Spring to run correctly on Java 21
Closes #3473
=> #3473 Add Java 21 and EA to build matrix

processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3462/Issue3462Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3462/Issue3462Test.java
=> #3462 Stream getters should not be treated as alternative setter

processor/src/main/java/org/mapstruct/ap/spi/DefaultBuilderProvider.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3463/EntityBuilder.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3463/Issue3463Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3463/Issue3463Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3463/Person.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3463/PersonDto.java
=> #3463 DefaultBuilderProvider should be able to handle methods in parent interfaces

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3331/Issue3331Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3331/Issue3331Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3331/Vehicle.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3331/VehicleDto.java
=> #3331 Do not handle defined mappings if the result type is abstract due to runtime exception subclass exhaustive strategy

processor/src/test/java/org/mapstruct/ap/test/bugs/_3485/Issue3485Test.java
Thanks to @KENNYSOFT for finding this in #3540.
=> Correct issue key for Issue3485Test

processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3565/Issue3565Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3565/Issue3565Test.java
=> #3565 Presence check methods should not be considered as valid mapping candidates

processor/src/test/java/org/mapstruct/ap/test/bugs/_3561/Issue3561Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3561/Issue3561Test.java
Fixes #3561 
This is only a test case, the fix was done as part of #3543
=> #3561 Add test case

documentation/src/main/asciidoc/chapter-2-set-up.asciidoc
PR to address https://github.com/mapstruct/mapstruct/issues/3635
=> Fix documentation of unmappedSourcePolicy default

build-config/src/main/resources/build-config/checkstyle.xml, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/conversion/_enum/EnumToIntegerConversionTest.java
@thunderhook found in mapstruct/mapstruct-idea#200 that enhanced for loops are currently not check for whitespaces. I enable the check and also applied the formatting.
=> disable ignoreEnhancedForColon in checkstyle

documentation/src/main/asciidoc/chapter-3-defining-a-mapper.asciidoc
=> #3639 fix documentation link

processor/src/main/java/org/mapstruct/ap/spi/EnumMappingStrategy.java, processor/src/main/java/org/mapstruct/ap/spi/EnumTransformationStrategy.java, processor/src/main/java/org/mapstruct/ap/spi/MappingExclusionProvider.java
=> #3634 fix typo in experimental note

processor/src/main/java/org/mapstruct/ap/internal/model/ForgedMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/BeanMappingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingMethodOptions.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3609/Issue3609Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3609/Issue3609Test.java
=> #3609 Add test case for issue 3609

documentation/src/main/asciidoc/chapter-5-data-type-conversions.asciidoc
=> #3504 Add example classes for the passing target type documentation

core/src/main/java/org/mapstruct/Mapping.java, documentation/src/main/asciidoc/chapter-8-mapping-values.asciidoc
=> #3638 Remove deprecation note of enum mapping via @Mapping

processor/src/test/java/org/mapstruct/ap/internal/util/NativeTypesTest.java, processor/src/test/java/org/mapstruct/ap/test/accessibility/AccessibilityTest.java, processor/src/test/java/org/mapstruct/ap/test/accessibility/DefaultSourceTargetMapperIfc.java
I found method name typo and then fix it. Please review PR
=> fix method name typo

integrationtest/src/test/resources/recordsTest/src/main/java/org/mapstruct/itest/records/nested/Address.java, integrationtest/src/test/resources/recordsTest/src/main/java/org/mapstruct/itest/records/nested/CareProvider.java, integrationtest/src/test/resources/recordsTest/src/main/java/org/mapstruct/itest/records/nested/CareProviderDto.java, integrationtest/src/test/resources/recordsTest/src/main/java/org/mapstruct/itest/records/nested/CareProviderMapper.java, integrationtest/src/test/resources/recordsTest/src/test/java/org/mapstruct/itest/records/nested/NestedRecordsTest.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java
=> #3717 Fix ClassCastException when getting thrown types for a record accessor

processor/src/main/resources/org/mapstruct/ap/internal/model/BeanMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_3747/Issue3747Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3747/Issue3747Test.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_3747/Issue3747MapperImpl.java
=> #3747 Do not generate redundant if condition with constructor mapping and RETURN_DEFAULT null value mapping strategy

processor/src/main/java/org/mapstruct/ap/internal/conversion/JavaLocalDateTimeToLocalDateConversion.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3732/Issue3732Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3732/Issue3732Test.java
=> #3732 Do not generate obsolete imports for LocalDateTime <-> LocalDate conversion

readme.md
=> #3751 Improve readme to include support for Java 16+ records

distribution/pom.xml, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/MappingBuilderContext.java, processor/src/main/java/org/mapstruct/ap/internal/model/NestedTargetPropertyMappingHolder.java, processor/src/main/java/org/mapstruct/ap/internal/model/ValueMappingMethod.java, processor/src/main/java/org/mapstruct/ap/spi/AccessorNamingStrategy.java
I fixed typos in the comments👩🏻‍💻
=> Fix typos in comments

processor/src/test/java/org/mapstruct/ap/test/accessibility/referenced/AbstractSourceTargetMapperPrivate.java, processor/src/test/java/org/mapstruct/ap/test/accessibility/referenced/AbstractSourceTargetMapperProtected.java, processor/src/test/java/org/mapstruct/ap/test/accessibility/referenced/ReferencedAccessibilityTest.java, processor/src/test/java/org/mapstruct/ap/test/accessibility/referenced/SourceTargetMapperPrivateBase.java, processor/src/test/java/org/mapstruct/ap/test/accessibility/referenced/SourceTargetMapperProtectedBase.java
Refactor: Standardize Class Names to PascalCase
=> Refactor: Standardize Class Names to PascalCase

readme.md
Consistent with the [reference documentation](https://mapstruct.org/documentation/reference-guide/) "latest stable ..".
=> Align README with v1.6.3 release

core/src/main/java/org/mapstruct/BeanMapping.java, core/src/main/java/org/mapstruct/Mapper.java, core/src/main/java/org/mapstruct/MapperConfig.java, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/BeanMappingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/DefaultOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/DelegatingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MapperConfigOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MapperOptions.java, processor/src/main/resources/org/mapstruct/ap/internal/model/BeanMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/abstractsuperclass/CustomExceptionSubclassMapper.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/abstractsuperclass/CustomSubclassMappingException.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/abstractsuperclass/CustomSubclassMappingExceptionTest.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/abstractsuperclass/MapperConfigSubclassMapper.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/abstractsuperclass/MapperSubclassMapper.java
close [issue#3821]( https://github.com/mapstruct/mapstruct/issues/3821)
I implemented subclassExhaustiveException with reference to subclassExhaustiveStrategy, so this custom exception supports configuration on mapper, mapperConfig, and BeanMapping. 
plz review @filiphr
=> #3821 feat: add support for custom exception in subclass mapping

processor/src/main/java/org/mapstruct/ap/internal/model/Decorator.java, processor/src/main/java/org/mapstruct/ap/internal/processor/AnnotationBasedComponentModelProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/processor/JakartaComponentProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/processor/Jsr330ComponentProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/processor/SpringComponentProcessor.java, processor/src/test/java/org/mapstruct/ap/test/decorator/AnnotatedMapper.java, processor/src/test/java/org/mapstruct/ap/test/decorator/AnnotatedMapperDecorator.java, processor/src/test/java/org/mapstruct/ap/test/decorator/DecoratedWithAnnotatedWithTest.java, processor/src/test/java/org/mapstruct/ap/test/decorator/TestAnnotation.java, processor/src/test/java/org/mapstruct/ap/test/decorator/jakarta/annotatewith/JakartaAnnotateWithMapper.java, processor/src/test/java/org/mapstruct/ap/test/decorator/jakarta/annotatewith/JakartaAnnotateWithWithMapperDecorator.java, processor/src/test/java/org/mapstruct/ap/test/decorator/jakarta/annotatewith/JakartaDecoratorAnnotateWithTest.java, processor/src/test/java/org/mapstruct/ap/test/decorator/jsr330/annotatewith/Jsr330AnnotateWithMapper.java, processor/src/test/java/org/mapstruct/ap/test/decorator/jsr330/annotatewith/Jsr330AnnotateWithMapperDecorator.java, processor/src/test/java/org/mapstruct/ap/test/decorator/jsr330/annotatewith/Jsr330DecoratorAnnotateWithTest.java, processor/src/test/java/org/mapstruct/ap/test/decorator/spring/annotatewith/AnnotateMapper.java, processor/src/test/java/org/mapstruct/ap/test/decorator/spring/annotatewith/AnnotateMapperDecorator.java, processor/src/test/java/org/mapstruct/ap/test/decorator/spring/annotatewith/CustomAnnotateMapper.java, processor/src/test/java/org/mapstruct/ap/test/decorator/spring/annotatewith/CustomAnnotateMapperDecorator.java, processor/src/test/java/org/mapstruct/ap/test/decorator/spring/annotatewith/CustomComponent.java, processor/src/test/java/org/mapstruct/ap/test/decorator/spring/annotatewith/CustomPrimary.java, processor/src/test/java/org/mapstruct/ap/test/decorator/spring/annotatewith/SpringDecoratorAnnotateWithTest.java
close: https://github.com/mapstruct/mapstruct/issues/3659
=> feat: Support @AnnotatedWith on class specified by @DecoratedWith

processor/src/main/java/org/mapstruct/ap/MappingProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/DefaultOptions.java, processor/src/main/java/org/mapstruct/ap/internal/option/MappingOption.java, processor/src/main/java/org/mapstruct/ap/internal/option/Options.java
This makes it easier to add new options
=> Refactor options and add an enum

processor/src/main/java/org/mapstruct/ap/internal/model/AbstractMappingMethodBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/NormalTypeMappingMethod.java, processor/src/main/resources/org/mapstruct/ap/internal/model/BeanMappingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/IterableMappingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/MapMappingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/StreamMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_3905/Issue3905Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3905/Issue3905Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3905/Override.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3905/OverrideDto.java
=> #3905: Using custom class Override should compile
