mapstruct/mapstruct

processor/pom.xml, processor/src/main/java/org/mapstruct/ap/model/GeneratedType.java, processor/src/main/resources/org.mapstruct.ap.model.GeneratedType.ftl
I've realized this feature by adding a manifest entry in the MANIFEST.MF file by means of the maven-jar-plugin. This is read by the annotation processor and included in the generated code.
Simple and effective :smile:
The full maven coordinates are added (groupId:artifactId:version).
One more remark: the `@Generated#comments` does not show up in the unit test (because the maven-jar-plugin is active at the end of the build).
=> #390 included maven coordinates as comments in generated code

core-common/src/main/java/org/mapstruct/BeanMapping.java, processor/src/main/java/org/mapstruct/ap/model/AssignmentFactory.java, processor/src/main/java/org/mapstruct/ap/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/model/IterableMappingMethod.java, processor/src/main/java/org/mapstruct/ap/model/MapMappingMethod.java, processor/src/main/java/org/mapstruct/ap/model/MappingBuilderContext.java, processor/src/main/java/org/mapstruct/ap/model/source/selector/InheritanceSelector.java, processor/src/main/java/org/mapstruct/ap/model/source/selector/MethodSelector.java, processor/src/main/java/org/mapstruct/ap/model/source/selector/MethodSelectors.java, processor/src/main/java/org/mapstruct/ap/model/source/selector/QualifierSelector.java, processor/src/main/java/org/mapstruct/ap/model/source/selector/SelectionCriteria.java, processor/src/main/java/org/mapstruct/ap/model/source/selector/TargetTypeSelector.java, processor/src/main/java/org/mapstruct/ap/model/source/selector/TypeSelector.java, processor/src/main/java/org/mapstruct/ap/model/source/selector/XmlElementDeclSelector.java, processor/src/main/java/org/mapstruct/ap/prism/PrismGenerator.java, processor/src/main/java/org/mapstruct/ap/processor/creation/MappingResolverImpl.java, processor/src/test/java/org/mapstruct/ap/test/erroneous/ambiguousfactorymethod/FactoryTest.java, processor/src/test/java/org/mapstruct/ap/test/selection/inheritance/Apple.java, processor/src/test/java/org/mapstruct/ap/test/selection/inheritance/AppleDto.java, processor/src/test/java/org/mapstruct/ap/test/selection/inheritance/Banana.java, processor/src/test/java/org/mapstruct/ap/test/selection/inheritance/BananaDto.java, processor/src/test/java/org/mapstruct/ap/test/selection/inheritance/ConflictingFruitFactory.java, processor/src/test/java/org/mapstruct/ap/test/selection/inheritance/ErroneousFruitMapper.java, processor/src/test/java/org/mapstruct/ap/test/selection/inheritance/Fruit.java, processor/src/test/java/org/mapstruct/ap/test/selection/inheritance/FruitDto.java, processor/src/test/java/org/mapstruct/ap/test/selection/inheritance/InheritanceSelectionTest.java, processor/src/test/java/org/mapstruct/ap/test/selection/inheritance/TargetTypeSelectingFruitMapper.java
* General improvement, factories and mapping method selection make use of the same (selector) mechanism.
* For the source-type, the fit was not applied in two directions. For that purpose the absolute (type) distance is used iso distance.
* There was no target-type inheritance implemented.
=> #385 Inheritance selection on best fit source- and target type 

processor/src/main/java/org/mapstruct/ap/util/MapperConfig.java
ordered as given in @...Mapper#uses and then @MapperConfig#uses, omitting duplicates.
I'm cleaning out stuff from my GlobalMapping PR and this code block was there to fix #323 (before I even created that issue). I've now finally pulled out that little piece - as I guess I'll have to throw away most of the other PR anyway now (I'll start with that soon-ish).
=> #323 make order of fields for used mappers stable

processor/src/main/java/org/mapstruct/ap/conversion/Conversions.java, processor/src/main/java/org/mapstruct/ap/model/common/TypeFactory.java, processor/src/main/java/org/mapstruct/ap/model/source/builtin/BuiltInMappingMethods.java, processor/src/main/java/org/mapstruct/ap/util/NativeTypes.java
... but on the classpath of the sources.
Unfortunately, I was not able to create a mvn build that could be used to reproduce the issue in an integration test. Perhaps you guys find a way for that... ?
Anyway, I tested that the issue is fixed by running the processor within the Eclipse build for a JDK 6 project, whereas Eclipse was started using JRE 8.
=> #454 Do not check the existence of types in the classloader of the processor

core-jdk8/src/main/java/org/mapstruct/Mapping.java, core/src/main/java/org/mapstruct/Mapping.java, processor/src/main/java/org/mapstruct/ap/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/model/dependency/GraphAnalyzer.java, processor/src/main/java/org/mapstruct/ap/model/dependency/Node.java, processor/src/main/java/org/mapstruct/ap/model/source/Mapping.java, processor/src/main/java/org/mapstruct/ap/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/dependency/Address.java, processor/src/test/java/org/mapstruct/ap/test/dependency/AddressDto.java, processor/src/test/java/org/mapstruct/ap/test/dependency/AddressMapper.java, processor/src/test/java/org/mapstruct/ap/test/dependency/AddressMapperWithCyclicDependency.java, processor/src/test/java/org/mapstruct/ap/test/dependency/AddressMapperWithUnknownPropertyInDependsOn.java, processor/src/test/java/org/mapstruct/ap/test/dependency/GraphAnalyzerTest.java, processor/src/test/java/org/mapstruct/ap/test/dependency/OrderingTest.java, processor/src/test/java/org/mapstruct/ap/test/dependency/Person.java, processor/src/test/java/org/mapstruct/ap/test/dependency/PersonDto.java
This change allows to specify an order for invoking the setters of bean mapping result types.
I went for the approach of allowing to specify the properties upon which a given property depends as it's more convinient to handle than simple numeric orderings (e.g. when inserting a new element at the middle of a dependency relationship).
=> #304: Ordering of property mappings

processor/src/main/java/org/mapstruct/ap/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/model/assignment/GetterWrapperForCollectionsAndMaps.java, processor/src/main/java/org/mapstruct/ap/model/common/TypeFactory.java, processor/src/main/resources/org.mapstruct.ap.model.assignment.GetterWrapperForCollectionsAndMaps.ftl, processor/src/test/java/org/mapstruct/ap/test/collection/Source.java, processor/src/test/java/org/mapstruct/ap/test/collection/SourceTargetMapper.java, processor/src/test/java/org/mapstruct/ap/test/collection/Target.java
This only fixes that one spot described in issue #523, but my guess is that we could have a similar problem in other assignments with local vars as well.
=> #523 fix type of assignment in GetterWrapperForCollectionsAndMaps

processor/src/main/java/org/mapstruct/ap/model/PropertyMapping.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_516/Issue516Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_516/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_516/SourceTargetMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_516/Target.java
Wraps a call to an add method on the target object in an null check + reproducer
=> #516 Add NP check on adder property mapping including reproducer

processor/src/main/java/org/mapstruct/ap/conversion/EnumStringConversion.java
Reason for change:
name() is safer than toString() because it always returns the enum name exactly as declared, whereas toString() can be overridden and may return any value.
=> #540 use name() instead of toString() for enum to String conversion

integrationtest/src/test/resources/simpleTest/src/main/java/org/mapstruct/itest/simple/ReferencedCustomMapper.java, integrationtest/src/test/resources/simpleTest/src/main/java/org/mapstruct/itest/simple/Source.java, integrationtest/src/test/resources/simpleTest/src/main/java/org/mapstruct/itest/simple/SourceTargetAbstractMapper.java, integrationtest/src/test/resources/simpleTest/src/main/java/org/mapstruct/itest/simple/SourceTargetMapper.java, integrationtest/src/test/resources/simpleTest/src/main/java/org/mapstruct/itest/simple/Target.java, integrationtest/src/test/resources/simpleTest/src/main/java/org/mapstruct/itest/simple/YetAnotherType.java, processor/src/main/java/org/mapstruct/ap/model/IterableMappingMethod.java, processor/src/main/java/org/mapstruct/ap/model/MapMappingMethod.java, processor/src/main/java/org/mapstruct/ap/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/model/common/Type.java, processor/src/main/java/org/mapstruct/ap/model/common/TypeFactory.java, processor/src/main/java/org/mapstruct/ap/processor/MethodRetrievalProcessor.java, processor/src/main/java/org/mapstruct/ap/util/Message.java, processor/src/main/resources/org.mapstruct.ap.model.MapMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/BeanMapper.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/CunningPlan.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/ExtendsBoundSource.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/ExtendsBoundSourceTargetMapper.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/GoodIdea.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/Idea.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/IterableExtendsBoundTargetMapper.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/IterableSuperBoundSourceMapper.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/IterableTypeVarBoundMapperOnMapper.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/IterableTypeVarBoundMapperOnMethod.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/Plan.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/Source.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/SourceSuperBoundTargetMapper.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/SuperBoundTarget.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/Target.java, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/WildCardTest.java
The solution introduces a fix for supporting wildcard extends bounds on the source side and wildcard super bounds on the target side.
Next to this, error handling is introduced for the reverse case and for all typevar cases.
Selection of wildcard methods needs to be revisited (see #527). I'll open a new issue for this as soon as this one is completed.
=> Solution for #527

processor/src/main/java/org/mapstruct/ap/writer/IndentationCorrectingWriter.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_515/Issue515Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_515/Issue515Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_515/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_515/Target.java
In expressions (and presumably also in contstants) its possible to create Strings definitions in the generated code. Indentation should therefore not be increased / decreased when braces (curly or round) are encountered inside a String definition (so between " "). 
Decreasing due to an unbalanced round brace inside a String definition led to the problem above.
Likewise, escaped '"' should be ignored.
The enum-state pattern (one of my favourites :+1: ) has been updated with a couple of extra states to handle this.
=> 515 Negative array index in indentation writer

processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/UpdateWrapper.java, processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/UpdateWrapper.ftl, processor/src/test/java/org/mapstruct/ap/test/updatemethods/CompanyMapper.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/DepartmentDto.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/EmployeeDto.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/EmployeeEntity.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/ErroneousOrganizationMapper1.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/ErroneousOrganizationMapper2.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/OrganizationMapper.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/SecretaryDto.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/SecretaryEntity.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/UpdateMethodsTest.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/selection/DepartmentMapper.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/selection/ExternalHandWrittenMapper.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/selection/ExternalMapper.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/selection/ExternalSelectionTest.java
This is the first step for #487, making iterable- and map mappings selectable.
I noticed I had to add an implementation type to the `UpdateMappingWrapper` to construct a ` new ArrayList()`. This could be wrong in `BeanMapping` as well. Need to investigate further.
=> #487 iterable and map update method selection

processor/src/main/java/org/mapstruct/ap/internal/model/IterableMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_577/Issue577Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_577/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_577/SourceTargetMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_577/Target.java
Hello,
I'm not sure if issue 577 reported recently should be fixed in IterableMappingMethod:equals() method. Maybe getTypeParameters() should never be empty and fix is needed elsewhere. But if it is indeed just missing check for empty collection, then I prepared fix for this issue.
=> Fix IndexOutOfBounds exception during mapping two arrays to collections.

processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java, processor/src/test/java/org/mapstruct/ap/internal/model/common/TypeFactoryTest.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_581/Issue581Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_581/SourceTargetMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_581/_target/Car.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_581/source/Car.java
Hello,
As discussed in bug ticket, I've finalized fix for #581 issue.
Few topics you might want to review, since I don't know yet, if you accept few code conventions I usually follow.
1. I consider good practice to not modify method parameters, to consider it final. Therefore when I need to modify it, I usually introduce new local variable and use it from there. That's the reason for adding *String trimmedName* in *isImported()* and use it instead of method parameter.
2. I moved code responsible for handling array brackets in simple class names to separate utility class, so I could add unit tests for it.
=> #581 Prevent multiple imports of similar simple class name from different packages

core-common/src/main/java/org/mapstruct/BeanMapping.java, core-common/src/main/java/org/mapstruct/CollectionMappingStrategy.java, core-common/src/main/java/org/mapstruct/IterableMapping.java, core-common/src/main/java/org/mapstruct/MapMapping.java, core-common/src/main/java/org/mapstruct/Mapper.java, core-common/src/main/java/org/mapstruct/MappingInheritanceStrategy.java, core-common/src/main/java/org/mapstruct/NullValueMappingStrategy.java, core-common/src/main/java/org/mapstruct/ReportingPolicy.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/BeanMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/IterableMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MapMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/Mapping.java, processor/src/main/java/org/mapstruct/ap/internal/option/ReportingPolicy.java, processor/src/main/java/org/mapstruct/ap/internal/prism/CollectionMappingStrategyPrism.java, processor/src/main/java/org/mapstruct/ap/internal/prism/MappingInheritanceStrategyPrism.java, processor/src/main/java/org/mapstruct/ap/internal/prism/NullValueMappingStrategyPrism.java, processor/src/main/java/org/mapstruct/ap/internal/util/MapperConfiguration.java, processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/CarMapperSettingOnConfig.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/ErroneousMapper1.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/ErroneousMapper3.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/ErroneousMapper4.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/SourceConstantsTest.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/SourceTargetMapper.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/Target.java
This fixes #618 and #588 (and the duplicate #622).
#602 (configurable destination packages and implementations) should be aligned to this solution as well. See examples in MapperConfiguration: https://github.com/mapstruct/mapstruct/pull/623/files#diff-edd112063ebfe5afe8f83d4a0ad78377L81
=> Detect unspecified annotation attributes

processor/src/main/java/org/mapstruct/ap/internal/writer/IndentationCorrectingWriter.java, processor/src/test/resources/checkstyle-for-generated-sources.xml
Removing the doubled blank lines was easy enough. For the unecessary newlines before closing brackets, I have no idea how to fix that in a simple way.
@gunnarmorling, perhaps you have an idea? :wink:
=> #626 Remove doubled blank lines on Windows

core-common/src/main/java/org/mapstruct/DecoratedWith.java
Apperently, I wasn't able to write that javadoc without grammar errors. I really should have pushed that to the other PR-branch for your review first. Sorry.
This commit fixes two of the things I found and adds a piece of missing information to the JSR 330 part.
Could you please check if there is anything else fishy? The doc-update for mapstruct.org that I'm preparing looks very similar, so I'll wait for feedback on this before I commit that other doc-update to the cr2-branch.
=> #592 Improve @DecoratedWith javadoc

processor/src/main/java/org/mapstruct/ap/internal/processor/MethodRetrievalProcessor.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_631/Base1.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_631/Base2.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_631/Issue631Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_631/SourceTargetMapper.java
Hi guys,
I'm not sure this is the way forward, so this one needs some more tests. What I've done is work with the type bound iso the type itself (in Parameter, MappingMethod). Its a bit crude. We should perhaps (if this is the way forward) these model elements in this way in stead of putting it on the getter. 
I also would like to add some test case in which the type bounds are coming from another package (make sure imports are handled correctly).
But first.. Is this the way forward? I'll extend the solution if we agree..
Cheers,
Sjaak
=> #631 fix for parameterized source / target types

integrationtest/src/test/java/org/mapstruct/itest/testutil/runner/ProcessorSuite.java, integrationtest/src/test/java/org/mapstruct/itest/testutil/runner/ProcessorSuiteRunner.java, integrationtest/src/test/java/org/mapstruct/itest/testutil/runner/Toolchain.java, integrationtest/src/test/java/org/mapstruct/itest/testutil/runner/xml/Toolchains.java, processor/src/test/java/org/mapstruct/ap/test/conversion/jodatime/JodaConversionTest.java
This fixes #642 and makes the handling of the toolchains-file a bit better. No need to activate the JDK 9 tests by using a VM-parameter anymore... :wink:
Also, I had to change one of the Joda-Tests, as it fails now on my machine (no idea if it's due to Windows 10 or JDK 1.8.0_60 or both...).
=> Autodetect toolchain conf

parent/pom.xml, processor/src/test/java/org/mapstruct/ap/test/conversion/jodatime/JodaConversionTest.java
... and revert changes to JodaConversionTest from commit feb5e2f13b0eea3027000cc7f03d6b63690505c5, as described in #684.
=> #684 Update joda-time to fix an incompatibility with JDK 1.8.0_60 and later

integrationtest/src/test/resources/jaxbTest/pom.xml, integrationtest/src/test/resources/jaxbTest/src/main/java/org/mapstruct/itest/jaxb/SourceTargetMapper.java, integrationtest/src/test/resources/jaxbTest/src/main/java/org/mapstruct/itest/jaxb/SubTypeDto.java, integrationtest/src/test/resources/jaxbTest/src/main/java/org/mapstruct/itest/jaxb/SuperTypeDto.java, integrationtest/src/test/resources/jaxbTest/src/main/resources/schema/underscores.xsd, integrationtest/src/test/resources/jaxbTest/src/test/java/org/mapstruct/itest/jaxb/JaxbBasedMapperTest.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/MethodSelectors.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/XmlElementDeclSelector.java, processor/src/main/java/org/mapstruct/ap/internal/prism/PrismGenerator.java, processor/src/test/java/org/mapstruct/ap/test/selection/jaxb/UnderscoreSelectionTest.java, processor/src/test/java/org/mapstruct/ap/test/selection/jaxb/underscores/ObjectFactory.java, processor/src/test/java/org/mapstruct/ap/test/selection/jaxb/underscores/SubType.java, processor/src/test/java/org/mapstruct/ap/test/selection/jaxb/underscores/SuperType.java, processor/src/test/java/org/mapstruct/ap/test/selection/jaxb/underscores/UnderscoreMapper.java, processor/src/test/java/org/mapstruct/ap/test/selection/jaxb/underscores/UnderscoreType.java
Hi,
since I have only been working with jaxb, xml schemas and soap for about 2 weeks there is a lot I still don't know about the problem I "solved" in this PR.
I have a wsdl of a third party soap service. Some of the elements have names using underscores instead of camel case like this:
```xml
<element name="planet_name" type="string"/>
```
which is perfectly ok.
When generating code from that wsdl with the "cxf-codegen-plugin" I get Code mit mostly "javaified" names (camel case with no underscores)
In the "ObjectFactory" the factory methods have @XmlElementDecl annotations that use the underscore names to set their "name" properties. Which might look like this:
```java
@XmlElementDecl(namespace = "http://foo.bar", name = "planet_name", scope = TypeName.class)
public …
```
=> jaxb underscores in schema element names

core-common/src/main/java/org/mapstruct/DecoratedWith.java, core-common/src/main/java/org/mapstruct/MapMapping.java, core-common/src/main/java/org/mapstruct/Mapper.java, core-common/src/main/java/org/mapstruct/MapperConfig.java
Ok. A small one.. Just to avoid mis-interpretation. 
Perhaps we should do this for all external annotations..
=> #761 using fully qualified names in javadoc for conflicting annotations

processor/src/main/java/org/mapstruct/ap/internal/model/Mapper.java, processor/src/main/java/org/mapstruct/ap/internal/model/MappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/CreateOrUpdateSelector.java, processor/src/main/java/org/mapstruct/ap/internal/util/TypeHierarchyErroneousException.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/AnnotationProcessorTestRunner.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/WithSingleCompiler.java
* Also fixes some compiler warnings that I got in Eclipse.
To use it, just add `@WithSingleCompiler(Compiler.JDK)` or `@WithSingleCompiler(Compiler.ECLIPSE)`  to the test class. And remove it again before committing. :grin:
=> Allow to select only one compiler in a processor test class

processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MethodMatcher.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_775/IterableContainer.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_775/IterableWithBoundedElementTypeTest.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_775/ListContainer.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_775/MapperWithCustomListMapping.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_775/MapperWithForgedIterableMapping.java
#775 actually uncovers two problems, I tried to fix them in two separate commits. The creation of the forged method for Iterables is straight forward I guess, but the lower-bound matching is a bit voodooish... I didn't get it to break though while trying around a bit. We still might have similar issues with upper-bounds, in case anyone wants to try that out in detail... :smirk:
=> Fix for #775: Iterable forged methods and lower bounds

core-jdk8/pom.xml, core-jdk8/src/main/java/org/mapstruct/ValueMapping.java, core/pom.xml, core/src/main/java/org/mapstruct/ValueMapping.java, parent/pom.xml
That's two small build related issues in one pull-request:
* #805 use basic ASCII chars in the javadoc ASCII art tables (I didn't find a proper way to get it to work otherwise...)
* #27 Add OSGi metadata to manifests of mapstruct.jar and mapstruct-jdk8.jar
=> Javadoc and OSGi

integrationtest/src/test/resources/fullFeatureTest/pom.xml, processor/src/test/java/org/mapstruct/ap/test/naming/spi/CustomAccessorNamingStrategy.java, processor/src/test/java/org/mapstruct/ap/test/naming/spi/CustomNamingStrategyTest.java, processor/src/test/java/org/mapstruct/ap/test/naming/spi/GolfPlayer.java, processor/src/test/java/org/mapstruct/ap/test/naming/spi/GolfPlayerDto.java, processor/src/test/java/org/mapstruct/ap/test/naming/spi/GolfPlayerMapper.java, processor/src/test/java/org/mapstruct/ap/testutil/WithServiceImplementation.java, processor/src/test/java/org/mapstruct/ap/testutil/WithServiceImplementations.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/CompilationRequest.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/CompilingStatement.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/EclipseCompilingStatement.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/FilteringParentClassLoader.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/InnerAnnotationProcessorRunner.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/JdkCompilingStatement.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/ModifiableURLClassLoader.java
I've also added the test case for the accessor naming strategy from the integration-tests module to the processor test to demonstrate the new feature. We should keep that one integration test, though.
Speaking of integration tests: our `FullFeatureCompilationTest` needs to ignore any test mappers that rely on special SPI implementations. Thus, let's put those tests in a package `.spi.` to allow the `FullFeatureCompilationTest` to ignore them.
@sjaakd: As you can see, this now works without having to modify something in the processor classes. If you revert everything in `org.mapstruct.ap.testutil.*` and `Services` and the related change in `Executables` on your branch, it should be rebasable to this. Well, plus the changed name of the annotations... :wink:
=> Add @WithServiceImplementation annotation in testutil to register SPI implementations in processor tests

processor/src/main/java/org/mapstruct/ap/internal/util/workarounds/EclipseAsMemberOfWorkaround.java, processor/src/main/java/org/mapstruct/ap/internal/util/workarounds/EclipseClassLoaderBridge.java, processor/src/main/java/org/mapstruct/ap/internal/util/workarounds/SpecificCompilerWorkarounds.java
I wasn't able to add a test for it, as there are no bundles of the new compiler version on Maven central, yet.
But I did test it locally with a fresh Eclipse Neon package and in Eclipse Mars (4.5.2).
=> #828 Fix NoClassDefFoundError when running in Eclipse Neon (4.6)

integrationtest/src/test/resources/namingStrategyTest/strategy/src/main/java/org/mapstruct/itest/naming/CustomAccessorNamingStrategy.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/util/Executables.java, processor/src/main/java/org/mapstruct/ap/spi/AccessorNamingStrategy.java, processor/src/main/java/org/mapstruct/ap/spi/DefaultAccessorNamingStrategy.java, processor/src/test/java/org/mapstruct/ap/test/naming/spi/CustomAccessorNamingStrategy.java
Seems not to be needed.. Why was it there in the first place?
=> #878 remove AcessorNamingStrategy#getCollectionGetterName from SPI

processor/src/main/java/org/mapstruct/ap/internal/model/common/Parameter.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_909/Issue909Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_909/ValuesMapper.java
Not really a fix, but a workaround for #909. I guess it might hit us at some other places as well.
I'll create an issue in the Freemarker issue tracker tomorrow or so.
=> #909 Avoid using 'values' as parameter name to work around a supsected issue in Freemarker

processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java
Have a more meaningful name. And add it to the set of existing variables (forgotten initially).
=> #921 Avoid generation of duplicate local variable name

processor/src/main/java/org/mapstruct/ap/internal/model/GeneratedType.java, processor/src/main/resources/org/mapstruct/ap/internal/model/GeneratedType.ftl
This allows the usage of MapStruct with JDK 9 Jigsaw without having to add `-addmods java.annotations.common` to javac if there is no other reason to do that.
Brushing up the integration tests to actually run with Jigsaw JDK 9 again is a bit icky and I'll do that later (requires `-addmods` for the JAXB tests, etc...).
=> #900 Use "@Generated" only when it's available on the classpath.

processor/src/main/java/org/mapstruct/ap/internal/model/IterableMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/MapMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/TypeConversion.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/Assignment.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/AssignmentWrapper.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/GetterWrapperForCollectionsAndMaps.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/SetterWrapperForCollectionsAndMaps.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/WrapperForCollectionsAndMaps.java, processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/GetterWrapperForCollectionsAndMaps.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/SetterWrapperForCollectionsAndMaps.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/macro/CommonMacros.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_289/Issue289Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_913/Domain.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_913/DomainDtoWithNvmsDefaultMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_913/DomainDtoWithNvmsNullMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_913/DomainDtoWithPresenceCheckMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_913/DomainWithoutSetter.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_913/DomainWithoutSetterDtoWithNvmsDefaultMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_913/DomainWithoutSetterDtoWithNvmsNullMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_913/DomainWithoutSetterDtoWithPresenceCheckMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_913/Dto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_913/DtoWithPresenceCheck.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_913/Helper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_913/Issue913GetterMapperForCollectionsTest.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_913/Issue913SetterMapperForCollectionsTest.java, processor/src/test/java/org/mapstruct/ap/test/collection/defaultimplementation/NoSetterCollectionMappingTest.java
The solution is twofold ( 1 & 2) but with some consequences ( 3 & 4):
1. It introduces the new ideas I have for templates. It uses the `<#nested>` in Freemarker to wrap statements in a null check or try-catch clause. The idea is to gradually phase out the other `xyzWrapper` and only keep an lefthandside (target) and righthandside (source), making stuff a lot simpeler.
2. Delegate the `NullValueMappingStrategy` to the forged Map/Iterable mapping methods and let them handle default situations. This requires that the user is warned for creating plausible null pointer situations. 
3. Choose (in case the user did not define a `NullValueMappingStrategy`  explicitly for forged methods the `NullValueMappingStrategy.RETURN_DEFAULT` iso  `NullValueMappingStrategy.RETURN_NULL`. This seems more in …
=> #913 uncompilable code generated in 1.1.0.CR1 for collection properties

processor/src/main/java/org/mapstruct/ap/internal/model/IterableMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/MapMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_971/CollectionSource.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_971/CollectionTarget.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_971/Issue971CollectionMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_971/Issue971MapMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_971/Issue971Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_971/MapSource.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_971/MapTarget.java
This one fixes #971. However, now we will generate a Mapping method for each of the types that we are converting for example there will be one method for each of: `Iterable`, `Collection`, `List` to a `List`. Where we could only use one method with a source parameter an `Iterable` that will do the mapping for the `Collection` and the `List` to a `List`.
Maybe we need to do some refactoring and for the `IterableMappingMethod` always use the most generic possible method.
Mapping any `Iterable`, `Collection` and/or `List` to a list in our case is exactly the same no matter what the parameter is.
=> #971 Make sure that an Iterable or Map MapingMethod are equal if their source parameters are from the same type

processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java, processor/src/test/java/org/mapstruct/ap/test/selection/resulttype/InheritanceSelectionTest.java, processor/src/test/java/org/mapstruct/ap/test/selection/resulttype/IsFruit.java, processor/src/test/java/org/mapstruct/ap/test/selection/resulttype/ResultTypeConstructingFruitInterfaceErroneousMapper.java, processor/src/test/java/org/mapstruct/ap/test/selection/resulttype/ResultTypeConstructingFruitInterfaceMapper.java
This PR basically makes sure that if the result type of the `BeanMappingMethod` is not an interface it can be considered that the methods has a "factory" method and therefore we do not need to report an error.
=> #657 Using bean mapping result types works when the map return type is not an interface

processor/src/main/java/org/mapstruct/ap/internal/model/MappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/AdderWrapper.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java, processor/src/main/java/org/mapstruct/ap/internal/util/Strings.java, processor/src/test/java/org/mapstruct/ap/internal/util/StringsTest.java
The following commits are in:
1. Fix. The problem was related to adding the parameter (argument) names too the set of existing variables. However, constructing of a MappingMethod was done on a clone but on the set of parameter names.
2. Next, as discussed in #941, the local variable naming strategy is adapted. 
3. Finally more logical names are sported for nested source properties and in the adder implementation. Have a look at the generated sources.
=> #941 fixing too many suffixes, naming strategy and logical variable names

processor/src/main/resources/org/mapstruct/ap/internal/model/common/Type.ftl, processor/src/test/java/org/mapstruct/ap/test/collection/wildcard/WildCardTest.java
The problem was that for extends/super bound `Type`(s) the name is `? extends/super java.lang.Integer`.
Do we need some more complex tests?
=> #1014 do not generate FQN for extends/super bound Types

processor/src/main/java/org/mapstruct/ap/internal/model/Field.java, processor/src/main/java/org/mapstruct/ap/internal/model/IterableMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/MapMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/MappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/MethodReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/XmlElementDeclSelector.java, processor/src/test/java/org/mapstruct/ap/test/selection/jaxb/OrderDto.java, processor/src/test/java/org/mapstruct/ap/test/selection/jaxb/OrderMapper.java, processor/src/test/java/org/mapstruct/ap/test/selection/jaxb/test1/ObjectFactory.java, processor/src/test/java/org/mapstruct/ap/test/selection/jaxb/test1/OrderType.java
XmlElementDeclSelector should receive its context from the calling property mapping. This is possible for forged methods. However for non-forged methods we should find another solution. Perhaps extend the annotation with jaxbCallingElemName or something along that lines.. Or leave it as is.
The equals methods needed to be implemented since which factory is called in a forged method is a discriminating element in its uniqueness.
=> #285 JAXB selection mechanism for List

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java, processor/src/test/java/org/mapstruct/ap/test/inheritfromconfig/CarMapperWithExplicitInheritance.java, processor/src/test/java/org/mapstruct/ap/test/inheritfromconfig/InheritFromConfigTest.java, processor/src/test/java/org/mapstruct/ap/test/inheritfromconfig/NotToBeUsedMapper.java
Currently MapStruct can refer to used mappers to inherit(reverse)configurations. However, it could be that these mappings are not available (for instance: the used mapper is part of another jar library or the concerning used mapper is not yet generated in the processor). I don't think we intended that so I explicitly disabled it.
=> #1027 do not consider Inherit(Inverse)Configuration in used mappers

core-common/src/main/java/org/mapstruct/AfterMapping.java, core-common/src/main/java/org/mapstruct/BeanMapping.java, core-common/src/main/java/org/mapstruct/BeforeMapping.java, core-common/src/main/java/org/mapstruct/Context.java, core-common/src/main/java/org/mapstruct/ObjectFactory.java, core-common/src/main/java/org/mapstruct/Qualifier.java, documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/AbstractBaseBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/AbstractMappingMethodBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/ContainerMappingMethodBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/HelperMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/IterableMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/LifecycleCallbackFactory.java, processor/src/main/java/org/mapstruct/ap/internal/model/LifecycleCallbackMethodReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/MethodReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/ForgedMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/Method.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/ParameterProvidedMethods.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/builtin/BuiltInMethod.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MethodRetrievalProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java, processor/src/main/resources/org/mapstruct/ap/internal/model/MethodReference.ftl, processor/src/test/java/org/mapstruct/ap/test/context/AutomappingNodeMapperWithSelfContainingContext.java, processor/src/test/java/org/mapstruct/ap/test/context/ContextParameterTest.java, processor/src/test/java/org/mapstruct/ap/test/context/CycleContextLifecycleMethods.java, processor/src/test/java/org/mapstruct/ap/test/context/FactoryContext.java, processor/src/test/java/org/mapstruct/ap/test/context/FactoryContextMethods.java, processor/src/test/java/org/mapstruct/ap/test/context/SelfContainingCycleContext.java
Only the last commit is new here, the first commits are identical to what's open in PR #1006.
I've already worked in the changes in the Javadoc of `Context` and `ObjectFactory`. I'll do the adaptation of `BeforeMapping` / `AfterMapping` seperately in a PR for #992, if that's okay.
The introduction of `@Context` in the ref-docs will be included in this PR later on (probably after christmas), but I wanted to show you how it's coming along. Code-wise, I'm finished with it so you could play around if you like.
=> #975 Part 2: Context params used as source for factory and lifecycle methods

processor/src/main/java/org/mapstruct/ap/internal/model/GeneratedType.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MapperRenderingProcessor.java, processor/src/main/resources/org/mapstruct/ap/internal/model/GeneratedType.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_1061/Issue1061Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1061/SourceTargetMapper.java
This PR makes sure that we generate a valid name for the Mappers that are created in the default package and that no `package` is added to the generated file.
=> #1061 Support for generating Mappers in the default package

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/ContainerMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/MapMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/NormalTypeMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/main/resources/org/mapstruct/ap/internal/model/IterableMappingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/StreamMappingMethod.ftl
I have created a new class for all the `MappingMethods` that have a factory method. There was a lot of duplication between all of the different methods.
Is it too much abstraction (with the new class)?
=> Cleanup duplicates in MappingMethods

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/MappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/NormalTypeMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/test/java/org/mapstruct/ap/test/nestedtargetproperties/NestedTargetPropertiesTest.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedtargetproperties/ChartEntryToArtistImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedtargetproperties/ChartEntryToArtistUpdateImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedtargetproperties/FishTankMapperImpl.java
This PR adds the ability to force `PropertyMappings` to create update methods, when the main method is not an update one.
If we do composite mapping (mapping with multiple source parameters), we need to make sure that they won't overwrite non-overlapping objects. Therefore we use update methods. However, by regular create methods with only one source parameter there is no need to create update methods.
=> #1060 Use update methods if there are multiple source parameters

processor/src/main/java/org/mapstruct/ap/internal/model/ValueMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/value/EnumToEnumMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/value/SpecialOrderMapper.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/value/DefaultOrderMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/value/OrderMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/value/SpecialOrderMapperImpl.java
Fixes #1091. 
`ValueMapping` defined like:
```java
@ValueMapping(source = MappingConstants.ANY_REMAINING, target = MappingConstants.NULL)
```
Should create compilable code and should map all remaining values to `null`.
=> #1091 Map ANY_REMAINING Enum source to null

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc
Fixes #1109.
Do we want to backport this to the already published documentation?
=> #1109 Add import for @Qualifier in the documentation

integrationtest/src/test/java/org/mapstruct/itest/tests/ExternalBeanJarTest.java, integrationtest/src/test/resources/externalbeanjar/beanjar/pom.xml, integrationtest/src/test/resources/externalbeanjar/beanjar/src/main/java/org/mapstruct/itest/externalbeanjar/Source.java, integrationtest/src/test/resources/externalbeanjar/beanjar/src/main/java/org/mapstruct/itest/externalbeanjar/Target.java, integrationtest/src/test/resources/externalbeanjar/mapper/pom.xml, integrationtest/src/test/resources/externalbeanjar/mapper/src/main/java/org/mapstruct/itest/externalbeanjar/Issue1121Mapper.java, integrationtest/src/test/resources/externalbeanjar/mapper/src/test/java/org/mapstruct/itest/externalbeanjar/ConversionTest.java, integrationtest/src/test/resources/externalbeanjar/pom.xml, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java
Creating a reproducer for this issue is a bit tricky. It requires a new jar containing the source and target for the mapping. Perhaps this is a good idea to have.
For the time being we'll have to do with the explanation in the `Type` class below.
=> #1121 TypeMirror should not be used as hashCode base for Type

processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1124/Issue1124Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1124/Issue1124Test.java
`NestedPropertyMappingMethod` currently can't handle lifecycle methods anyway, so we can skip adding the context parameters.
Fixes #1124.
@sjaakd, I guess once the `SourceRHS` is refactored, it might be easier to add handling of the actual source call (e.g. the property accessor invocation, or as in this case, a call to the nested property mapping method via `MethodReference`) - is that on your map as well?
Initially I just assumed that lifecycle methods are considered in nested property mapping methods, but adding that right now would require some icky code... I guess we should revisit that later on... :)
=> #1124 Don't pass context parameters to forged methods for nested property mapping methods

copyright.txt
Fixes #1092 
If we want to pursue the idea to have the github id next to the contributors names.
=> #1092 Add github id next to contributers

core-common/src/main/java/org/mapstruct/CollectionMappingStrategy.java, documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/SetterWrapperForCollectionsAndMaps.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/SetterWrapperForCollectionsAndMaps.ftl, processor/src/test/java/org/mapstruct/ap/test/collection/immutabletarget/CupboardDto.java, processor/src/test/java/org/mapstruct/ap/test/collection/immutabletarget/CupboardEntity.java, processor/src/test/java/org/mapstruct/ap/test/collection/immutabletarget/CupboardEntityOnlyGetter.java, processor/src/test/java/org/mapstruct/ap/test/collection/immutabletarget/CupboardMapper.java, processor/src/test/java/org/mapstruct/ap/test/collection/immutabletarget/ErroneousCupboardMapper.java, processor/src/test/java/org/mapstruct/ap/test/collection/immutabletarget/ImmutableTargetTest.java
A new `CollectionMappingStrategy.TARGET_IMMUTABLE` has been introduced. The solution does not call the clear/addAll on the target collection. Instead it uses the setter on the target.
Pending: while handling the nice table in the documentation: what do we do when we encounter conflicting situations: e.g. there's no setter? Probably we should generate an error. 
I'll add that scenario, when we agree in general on this approach.
=> #1126 adding the option to handle immutable collections in update methods

processor/src/main/java/org/mapstruct/ap/internal/model/ContainerMappingMethodBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/MapMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/MappingBuilderContext.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/DateFormatValidationResult.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/DefaultConversionContext.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/FormattingParameters.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/IterableMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MapMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/Mapping.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java, processor/src/test/java/org/mapstruct/ap/internal/model/common/DefaultConversionContextTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/erroneous/ErroneousFormatMapper.java, processor/src/test/java/org/mapstruct/ap/test/conversion/erroneous/InvalidDateFormatTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/erroneous/Source.java, processor/src/test/java/org/mapstruct/ap/test/conversion/erroneous/Target.java
Fixes #725 
I wanted to add the column number to our diagnostics. However, that does not work correctly :). 
* The eclipse compiler finds out the column. However, it is never used :). There might be a bug report, but I can't find it. I just looked at their sources
* As for javac it will work in JDK 9, see [JDK-6388543](https://bugs.openjdk.java.net/browse/JDK-6388543)
=> #725 Flag the Annotation element with the wrong dateFormat

processor/src/main/java/org/mapstruct/ap/internal/model/assignment/WrapperForCollectionsAndMaps.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1164/GenericHolder.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1164/Issue1164Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1164/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1164/SourceTargetMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1164/Target.java
=> #1164 Make sure that all import types of a Type are imported for the wrapper

.travis.yml, etc/toolchains-travis-jenkins.xml, parent/pom.xml
Fixes #1171.
This adds the travis.yml and the toolchains for the Travis build.
Someone with admin rights (@gunnarmorling, @agudian, @sjaakd) on the repository should activate Travis for it [here](https://travis-ci.org/profile/mapstruct). Best would be before merging this pull request so the merge of this would trigger the first build and activate it
=> #1171 Add Travis CI

core-common/src/main/java/org/mapstruct/Mapper.java, core-common/src/main/java/org/mapstruct/MapperConfig.java, processor/src/main/java/org/mapstruct/ap/internal/model/AbstractBaseBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/AbstractMappingMethodBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/ContainerMappingMethodBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/MapMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/util/MapperConfiguration.java, processor/src/test/java/org/mapstruct/ap/test/collection/erroneous/ErroneousCollectionMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/collection/erroneous/ErroneousCollectionNoElementMappingFoundDisabledAuto.java, processor/src/test/java/org/mapstruct/ap/test/collection/erroneous/ErroneousCollectionNoKeyMappingFoundDisabledAuto.java, processor/src/test/java/org/mapstruct/ap/test/collection/erroneous/ErroneousCollectionNoValueMappingFoundDisabledAuto.java, processor/src/test/java/org/mapstruct/ap/test/java8stream/erroneous/ErroneousListToStreamNoElementMappingFoundDisabledAuto.java, processor/src/test/java/org/mapstruct/ap/test/java8stream/erroneous/ErroneousStreamMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/java8stream/erroneous/ErroneousStreamToListNoElementMappingFoundDisabledAuto.java, processor/src/test/java/org/mapstruct/ap/test/java8stream/erroneous/ErroneousStreamToStreamNoElementMappingFoundDisabledAuto.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/DisableConfig.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/DisablingNestedSimpleBeansMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/ErroneousDisabledHouseMapper.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/ErroneousDisabledViaConfigHouseMapper.java
Fixes #993.
Please have a look at the field name in the API and the Javadoc. The field is a bit verbose, but I couldn't think of something else. I am open to ideas :)
=> #993 Add support for disabling the generation of forged mapping methods

processor/src/main/java/org/mapstruct/ap/internal/model/CollectionAssignmentBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/ExistingInstanceSetterWrapperForCollectionsAndMaps.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/GetterWrapperForCollectionsAndMaps.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/SetterWrapperForCollectionsAndMaps.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/SetterWrapperForCollectionsAndMapsWithNullCheck.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/WrapperForCollectionsAndMaps.java, processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/ExistingInstanceSetterWrapperForCollectionsAndMaps.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/GetterWrapperForCollectionsAndMaps.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/SetterWrapperForCollectionsAndMaps.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/SetterWrapperForCollectionsAndMapsWithNullCheck.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/macro/CommonMacros.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_913/Domain.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_913/Issue913SetterMapperForCollectionsTest.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithNcvsAlwaysMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithNvmsDefaultMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithNvmsNullMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithPresenceCheckMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/collection/adder/SourceTargetMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/collection/adder/SourceTargetMapperStrategyDefaultImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedbeans/UserDtoMapperClassicImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedbeans/UserDtoMapperSmartImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedtargetproperties/ChartEntryToArtistImpl.java
When using set in the SetterWrapperForCollections do null check only direct assignment or when the NullValueCheckStrategy is ALWAYS.
This one fixed the second part of #1164
=> #1164 Make sure we don't do a null check all the time for SetterWrapperForCollections

processor/src/main/java/org/mapstruct/ap/internal/model/ContainerMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/IterableCreation.java, processor/src/main/java/org/mapstruct/ap/internal/model/MapMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/ImplementationType.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java, processor/src/main/resources/org/mapstruct/ap/internal/model/IterableCreation.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/IterableMappingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/MapMappingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/StreamMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/collection/defaultimplementation/DefaultCollectionImplementationTest.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/array/ScienceMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithNcvsAlwaysMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithNvmsDefaultMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithNvmsNullMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithPresenceCheckMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/collection/defaultimplementation/SourceTargetMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedbeans/UserDtoMapperClassicImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedbeans/UserDtoMapperSmartImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedbeans/UserDtoUpdateMapperSmartImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/updatemethods/CompanyMapper1Impl.java
This one solves the first part of #777 (using the constructors with initial capacity) when instantiating the new Collections / Maps. For the second part we need to discuss.
This also improves the performance of the generated code. The performance is improved because there the underlying `Arrays` in the `Collection`s / `Map`s will not need to be increased during the mapping.
=> #777 Use initial capacity when creation new Collection / Map

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc
Uses `:sectanchors:` to add anchors to the sections. See [this](http://asciidoctor.org/docs/user-manual/#anchors) for more information.
And ads a small change to the authors :)
=> Use anchors for the sections

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/NestedTargetPropertyMappingHolder.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/Mapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1153/ErroneousIssue1153Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1153/Issue1153Test.java
* Move the error generation for the invalid TargetReference into the BuilderFromTargetMapping
* TargetReference will strip the first entry name in the following cases only if the first entry name matches the MappingTarget parameter, or for reverse mappings it matches the source parameter name
* Pass the reverse source parameter when initializing a reverse mapping
Fixes #1153.
This PR and #1168 are changing the same code.
=> #1153 Do not use invalid TargetReferences when creating nested target mappings

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/AbstractBaseBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/AbstractMappingMethodBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/ContainerMappingMethodBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/DefaultMappingExclusionProvider.java, processor/src/main/java/org/mapstruct/ap/internal/model/MapMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/MappingBuilderContext.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/spi/DefaultMappingExclusionProvider.java, processor/src/main/java/org/mapstruct/ap/spi/MappingExclusionProvider.java, processor/src/test/java/org/mapstruct/ap/test/NoProperties.java, processor/src/test/java/org/mapstruct/ap/test/WithProperties.java, processor/src/test/java/org/mapstruct/ap/test/collection/erroneous/ErroneousCollectionMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/collection/erroneous/ErroneousCollectionNoKeyMappingFound.java, processor/src/test/java/org/mapstruct/ap/test/collection/erroneous/ErroneousCollectionNoValueMappingFound.java, processor/src/test/java/org/mapstruct/ap/test/java8stream/erroneous/ErroneousListToStreamNoElementMappingFound.java, processor/src/test/java/org/mapstruct/ap/test/java8stream/erroneous/ErroneousStreamMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/java8stream/erroneous/ErroneousStreamToListNoElementMappingFound.java, processor/src/test/java/org/mapstruct/ap/test/java8stream/erroneous/ErroneousStreamToStreamNoElementMappingFound.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exclusions/ErroneousJavaInternalMapper.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exclusions/ErroneousJavaInternalTest.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exclusions/Source.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exclusions/Target.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exclusions/custom/CustomMappingExclusionProvider.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exclusions/custom/ErroneousCustomExclusionMapper.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exclusions/custom/ErroneousCustomExclusionTest.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exclusions/custom/Source.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exclusions/custom/Target.java, processor/src/test/java/org/mapstruct/ap/test/selection/generics/ConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/selection/generics/ErroneousSource6.java
Fixes #1154.
With this PR we are adding an SPI that can be used to exclude `TypeElement`(s) from the automapping, i.e. MapStruct will not try to generate an automatic sub-mapping method if a type is excluded.
The default implementation excludes packages from the `java` and `javax` sub-packages
=> #1154 Add SPI for excluding types/elements from automatic sub-mapping generation

.codecov.yml, .travis.yml, parent/pom.xml, readme.md
Fixes #1194 
I decided to integrate with [codecov.io](https://codecov.io/). I think that they have better integration with github and much better GUI. Also with them you can easily configure the bot to use our own bot. If we want to do that it can be configured like [this](https://docs.codecov.io/docs/team-bot)
=> Coverage analysis setup

processor/src/main/java/org/mapstruct/ap/internal/model/GeneratedType.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java, processor/src/main/resources/org/mapstruct/ap/internal/model/GeneratedType.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_1215/Issue1215Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1215/dto/EntityDTO.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1215/entity/AnotherTag.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1215/entity/Entity.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1215/entity/Tag.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1215/mapper/Issue1215Mapper.java
Fixes #1215.
This makes sure that a type is considered as an import event if if is of an array type. The array suffix `[]` is always stripped in the import name of the `Type`
=> #1215 Add import correctly for array types

processor/src/main/java/org/mapstruct/ap/internal/model/GeneratedType.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1227/Issue1227Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1227/Issue1227Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1227/ThreadDto.java
Fixes #1227.
I am not sure if we need to add the types from the other `java.lang` sub-packages. Like `java.lang.ref`, `java.lang.reflect` etc.
=> #1227 Make sure that only types belonging to java.lang are not imported

processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exclusions/ErroneousJavaInternalTest.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exclusions/Source.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exclusions/Target.java
Fixes #1150. I think that I have found a good way to display the mapping not found for deep nested properties
=> #1150 Improve error reporting for nested properties

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc
Fixes #1086.
Something similar would be included in the Release notes as well.
=> #1086 Mention the fact that prototype methods are not considered for automatic sub mapping methods

core-common/src/test/java/org/mapstruct/factory/MappersTest.java, core-common/src/test/java/org/mapstruct/test/model/SomeClass$FooImpl.java, core-common/src/test/java/org/mapstruct/test/model/SomeClass$NestedClass$FooImpl.java, core-common/src/test/java/org/mapstruct/test/model/SomeClass.java, processor/src/main/java/org/mapstruct/ap/internal/model/Decorator.java, processor/src/main/java/org/mapstruct/ap/internal/model/Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_611/Issue611Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_611/SomeClass.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_611/SomeOtherClass.java
Fixes #611.
The method name "getFlatName" is supposed to imply that it squashes/flattens several class names into one.
=> #611 Allow nested declaration of Mappers

processor/pom.xml
Fixes #1196.
This setup works on Netbeans (installed and tested by me). I think that it'll work on Travis.
Another possible solution would be the user to set an empty `argLine`,  or the `propertyName` that we would define for jacoco in their own `settings.xml`. We can write this on our website or even in our `README`
=> #1196 Fix build problems on Netbeans

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Parameter.java, processor/src/main/resources/org/mapstruct/ap/internal/model/BeanMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_1244/Issue1244Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1244/SizeMapper.java
FreeMarker has problems getting values from a map when the key
is "values" or "size" (there might be other cases, this are the ones we know).
Therefore, instead of using a Map, MapStruct will pass the Parameter to the
function and return List<PropertyMapping>
Fixes: #1244
I decided for a different approach in solving this, as there might be other cases where FreeMarker fails. It should be much safer like this. We just pass the `Parameter` to a function and we get back a `List<PropertyMapping>`.
=> #1244 Fix problems with special word for FreeMarker in some cases

processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/FactoryParameterSelector.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/MethodSelectors.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1242/ErroneousIssue1242MapperMultipleSources.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1242/Issue1242Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1242/Issue1242Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1242/SourceA.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1242/SourceB.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1242/TargetA.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1242/TargetB.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1242/TargetFactories.java
From the Javadoc of `@ObjectFactory`: If there are two factory methods, both serving the same type, one with no parameters and one taking sources as input, then the one with the source parameters is favored. If there are multiple such factories, an ambiguity error is shown.
Fixes #1242.
The test relies on #1237 being merged, so the PR will fail initially. I'll rebase after the review and after the other PR is merged.
=> #1242 Fix favoring of a single factory method with source params before others without source params.

processor/src/main/java/org/mapstruct/ap/internal/model/NestedTargetPropertyMappingHolder.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1247/DtoIn.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1247/DtoOut.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1247/InternalData.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1247/InternalDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1247/Issue1247Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1247/Issue1247Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1247/OtherDtoOut.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1247/OtherInternalData.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1247/OtherInternalDto.java
Fixes #1247
This one also clarifies #1085.  A valid `SourceReference` can have no property entries when the entire source parameter is mapped to some property.
=> #1247 Make sure that nested target mappings works correctly for multiple source parameters

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc
On line 14, changed "repostory" to "repository"
=> Fixed a minor typo

documentation/src/main/asciidoc/controlling-nested-bean-mappings.asciidoc, documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc, readme.md
This PR fixes a few typos, grammar issues and formatting issues in the reference guide and the readme.
Concerning the advantages of MapStruct I aligned `mapstruct-reference-guide.asciidoc` with `readme.md`. If this is not desired, just let me know.
=> Improvement to Reference Guide and Readme

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1242/Issue1242Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1283/ErroneousInverseTargetHasNoSuitableConstructorMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1283/ErroneousTargetHasNoSuitableConstructorMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1283/Issue1283Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1283/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1283/Target.java, processor/src/test/java/org/mapstruct/ap/test/erroneous/ambiguousannotatedfactorymethod/AmbiguousAnnotatedFactoryTest.java, processor/src/test/java/org/mapstruct/ap/test/erroneous/ambiguousfactorymethod/FactoryTest.java, processor/src/test/java/org/mapstruct/ap/test/nestedsourceproperties/NestedSourcePropertiesTest.java, processor/src/test/java/org/mapstruct/ap/test/selection/generics/ConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/selection/resulttype/ErroneousResultTypeNoEmptyConstructorMapper.java, processor/src/test/java/org/mapstruct/ap/test/selection/resulttype/InheritanceSelectionTest.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/UpdateMethodsTest.java
Fixes #1283.
This PR fixes #1283 by moving the no suitable empty constructor check during the `BeanMappingMethod` creation (only if there is no factory method). With this we additionally get the same check for non-reverse methods and `BeanMapping#resultType`
=> Handle no suitable empty constructor during BeanMappingMethod creation

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/ContainerMappingMethodBuilder.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exceptions/EntityFactory.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exceptions/MappingException.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exceptions/NestedMappingsWithExceptionTest.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exceptions/ProjectMapper.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exceptions/_target/DeveloperDto.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exceptions/_target/ProjectDto.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exceptions/source/Developer.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exceptions/source/Project.java
Fixes #1304.
Exceptions that can be thrown in assignments in nested methods are added to the throws clause to the generated nested methods as well
=> #1304 Add thrown exceptions to the generated nested mapping methods

core-common/src/main/java/org/mapstruct/Mapper.java, core-common/src/main/java/org/mapstruct/MapperConfig.java, documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc, processor/src/main/java/org/mapstruct/ap/MappingProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/option/Options.java, processor/src/main/java/org/mapstruct/ap/internal/util/MapperConfiguration.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/unmappedsource/Config.java, processor/src/test/java/org/mapstruct/ap/test/unmappedsource/ErroneousStrictSourceTargetMapper.java, processor/src/test/java/org/mapstruct/ap/test/unmappedsource/SourceTargetMapper.java, processor/src/test/java/org/mapstruct/ap/test/unmappedsource/UnmappedSourceTest.java, processor/src/test/java/org/mapstruct/ap/test/unmappedsource/UsesConfigFromAnnotationMapper.java
Just like the unmappedTargetPolicy feature, defaulting the new configuration to IGNORE for backwards compatibility.
=> #610 unmappedSourcePolicy

processor/src/main/java/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java, processor/src/main/resources/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/nestedsource/exceptions/Bucket.java, processor/src/test/java/org/mapstruct/ap/test/nestedsource/exceptions/NestedExceptionTest.java, processor/src/test/java/org/mapstruct/ap/test/nestedsource/exceptions/NoSuchUser.java, processor/src/test/java/org/mapstruct/ap/test/nestedsource/exceptions/Resource.java, processor/src/test/java/org/mapstruct/ap/test/nestedsource/exceptions/ResourceDto.java, processor/src/test/java/org/mapstruct/ap/test/nestedsource/exceptions/ResourceMapper.java, processor/src/test/java/org/mapstruct/ap/test/nestedsource/exceptions/User.java
Issue occurs when exceptions declared in nested source mapping, which would make compilation failures for unreported exceptions.
Reference to the testing case: https://github.com/chigix/mapstruct/tree/Exception_in_nested_mapping
Signed-off-by: RichardLea <chigix@zoho.com>
=> #1332 Fix exceptions declaration missing in nested mapping methods

processor/src/main/java/org/mapstruct/ap/internal/processor/MethodRetrievalProcessor.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1339/Callback.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1339/Issue1339Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1339/Issue1339Test.java
Fixes #1339 
Primitive context parameters should not be searched for lifecycle methods
=> Primitive Context parameters should be skipped when looking for lifecycle methods

processor/src/main/java/org/mapstruct/ap/internal/model/EnumMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/ValueMappingMethod.java, processor/src/main/resources/org/mapstruct/ap/internal/model/EnumMappingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/ValueMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_1340/Issue1340Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1340/Issue1340Test.java
Fixes #1340 
* The Value / Enum Mappings should copy all the parameters from the method that is being overriden
* The source parameter should be the first source parameter
=> Correctly use value mapping source parameters

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1320/Issue1320Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1320/Issue1320Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1320/Target.java
Create mappings for each unprocessed defined target based on their name and the mapping.
Fixes #1320.
@sjaakd guess what, the `Map<String, List<Mapping>>` hitting us again :). Really looking forward to 2.0.
=> #1320 Properly create additional options for unprocessed defined targets

processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1353/Issue1353Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1353/Issue1353Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1353/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1353/Target.java
Add a trim for source and target mappings, but throw a warning message if trimmed.
Fixes #1353
=> #1353 Add a trim for source and target mappings

processor/src/main/java/org/mapstruct/ap/internal/model/source/Mapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1242/Issue1242Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1283/Issue1283Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1345/Issue1345Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1345/Issue1345Test.java, processor/src/test/java/org/mapstruct/ap/test/erroneous/ambiguousannotatedfactorymethod/AmbiguousAnnotatedFactoryTest.java, processor/src/test/java/org/mapstruct/ap/test/erroneous/ambiguousfactorymethod/FactoryTest.java, processor/src/test/java/org/mapstruct/ap/test/nestedsourceproperties/NestedSourcePropertiesTest.java, processor/src/test/java/org/mapstruct/ap/test/selection/generics/ConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/selection/resulttype/InheritanceSelectionTest.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/UpdateMethodsTest.java
There seems to be functionality to deliberately do something with the fact that MapStruct cannot perform a reverse mapping when there's no target write accessor.
However there are no testcases for it.
There is however a test case failing when the solution is implemented, see #838. However, this is funny because now the fault message is actually covering #838 in stead of "unknown property". 
So: what should we do: 
1. should we indeed automatically ignore a reverse mapping if there's no write accessor in the reverse situation as is introduced with this PR? I personally think so.
2. if we agree on that, it most likely makes no sense to pass this `isReverse` boolean  to ` errorMessage.report( isReverse );` on line 175 in `TargetReference` and remove subsequent functionality in the message …
=> #1345 ignoring reversed mappings with no target accessor silently

processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1375/Issue1375Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1375/Issue1375Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1375/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1375/Target.java
Fixes #1375 
We can actually create a valid mapper when an intermediary read accessor is missing. Therefore I have removed that check (which actually was not reporting anything before)
=> #1375 Allow using target references when there is no intermediary read accessor

processor/src/main/java/org/mapstruct/ap/internal/processor/AnnotationBasedComponentModelProcessor.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1395/Issue1395Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1395/Issue1395Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1395/NotUsedService.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1395/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1395/Target.java
Fixes #1395.
Unused mappers should not be used in constructors of constructor injection
=> #1395 Unused mappers should not be used in constructor injection

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/inheritfromconfig/multiple/BaseDto.java, processor/src/test/java/org/mapstruct/ap/test/inheritfromconfig/multiple/BaseEntity.java, processor/src/test/java/org/mapstruct/ap/test/inheritfromconfig/multiple/Car2Dto.java, processor/src/test/java/org/mapstruct/ap/test/inheritfromconfig/multiple/Car2Entity.java, processor/src/test/java/org/mapstruct/ap/test/inheritfromconfig/multiple/CarDto.java, processor/src/test/java/org/mapstruct/ap/test/inheritfromconfig/multiple/CarEntity.java, processor/src/test/java/org/mapstruct/ap/test/inheritfromconfig/multiple/CarMapper.java, processor/src/test/java/org/mapstruct/ap/test/inheritfromconfig/multiple/CarMapper2.java, processor/src/test/java/org/mapstruct/ap/test/inheritfromconfig/multiple/CarMapperTest.java, processor/src/test/java/org/mapstruct/ap/test/inheritfromconfig/multiple/EntityToDtoMappingConfig.java
Fixes #1367 
Whereas its not possible to combine forward and reverse explicit configurations (you get a warning:  `Method cannot be annotated with both a @InheritConfiguration and @InheritInverseConfiguration`) it seems to be possible with the current auto-inheritance options. Here you have the possibilities: `AUTO_INHERIT_FROM_CONFIG`, `AUTO_INHERIT_REVERSE_FROM_CONFIG`, and **`AUTO_INHERIT_ALL_FROM_CONFIG`** .
This PR removes that restriction and aligns the strategy for auto inheritance. So it will be possible to define an `@InheritConfiguration` together with `@InheritReverseConfiguration` on  the same method.
Forward mappings (`@InheritConfiguration`) takes precedence over reverse mappings (`@InheritInverseConfiguration`)
=> #1367 aligning @InheritConfiguration and @InheritReverseConfiguration with AUTO_INHERIT_ALL_FROM_CONFIG.

processor/src/main/java/org/mapstruct/ap/internal/model/CollectionAssignmentBuilder.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1359/Issue1359Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1359/Issue1359Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1359/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1359/Target.java
Fixes #1359.
We need to consider a collection target as immutable if there is no read accessor for it
=> #1359 Collection target should be considered as immutable if there is no read accessor

processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1338/Issue1338Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1338/Issue1338Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1338/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1338/Target.java
If the Collection type is not actually generic it has no type parameters.
However, it's type argument can be determined.
One such list exists in protobuf (ProtocolStringList)
Fixes #1338
=> #1338 Always determine collection argument type when searching for adder

processor/src/main/java/org/mapstruct/ap/internal/model/source/Mapping.java, processor/src/test/java/org/mapstruct/ap/test/defaultvalue/DefaultValueTest.java, processor/src/test/java/org/mapstruct/ap/test/source/constants/SourceConstantsTest.java, processor/src/test/java/org/mapstruct/ap/test/source/defaultExpressions/java/JavaDefaultExpressionTest.java
This PR will change the line that is reported in an error message when an `@Mapping` annotation contains improper values. An example of this is:
```
@Mapper
public interface MyMapper {
@Mapping( target = "id", expression = "java(String.valueOf( \"123\" )), constant = "1234") // error should be reported here
Target map(Source source); // error report on this line
}
```
Before this PR, the error message would report an error on the Target. Now, the error message will report the line that the @Mapping annotation is on.
=> #1383 Report error on the @Mapping annotation when using invalid values

CONTRIBUTING.md, readme.md
Just a small PR that replaces the cloudbees links I found with travis-ci links.
I haven't found such a nice "built on" image that is shown for cloudbees for travis-ci, but I guess this is not so important as the build status is already available at the top of `readme.md`.
=> Remove cloudbees CI links and add travis-ci

core-common/src/main/java/org/mapstruct/BeanMapping.java, documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/source/BeanMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/Mapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java, processor/src/test/java/org/mapstruct/ap/test/ignore/IgnorePropertyTest.java, processor/src/test/java/org/mapstruct/ap/test/ignore/expand/ExpandedToolbox.java, processor/src/test/java/org/mapstruct/ap/test/ignore/expand/FlattenedToolBox.java, processor/src/test/java/org/mapstruct/ap/test/ignore/expand/Hammer.java, processor/src/test/java/org/mapstruct/ap/test/ignore/expand/IgnorePropertyTest.java, processor/src/test/java/org/mapstruct/ap/test/ignore/expand/ToolBoxMapper.java, processor/src/test/java/org/mapstruct/ap/test/ignore/expand/Wrench.java, processor/src/test/java/org/mapstruct/ap/test/ignore/inherit/BaseEntity.java, processor/src/test/java/org/mapstruct/ap/test/ignore/inherit/HammerDto.java, processor/src/test/java/org/mapstruct/ap/test/ignore/inherit/HammerEntity.java, processor/src/test/java/org/mapstruct/ap/test/ignore/inherit/IgnorePropertyTest.java, processor/src/test/java/org/mapstruct/ap/test/ignore/inherit/ToolDto.java, processor/src/test/java/org/mapstruct/ap/test/ignore/inherit/ToolEntity.java, processor/src/test/java/org/mapstruct/ap/test/ignore/inherit/ToolMapper.java, processor/src/test/java/org/mapstruct/ap/test/ignore/inherit/WorkBenchDto.java, processor/src/test/java/org/mapstruct/ap/test/ignore/inherit/WorkBenchEntity.java
The user can now control the mapping on `@BeanMapping` level. Especially when there only a few source properties and the target object has a large number of properties this comes in handy.
In stead of manually entering all the `@Mapping( target = "?", ignore=true ), this is now the default behaviour for this one method.
Note that this is different than disabling warnings (unmapped target policy). This leaves still implicit mappings to take care of.
See #1392 for more details.
=> #1392 add option to default ignoreAll mappings in a bean mapping method

integrationtest/src/test/java/org/mapstruct/itest/tests/FullFeatureCompilationTest.java, processor/src/main/java/org/mapstruct/ap/internal/model/VirtualMappingMethod.java, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/CalendarToXmlGregorianCalendar.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/CalendarToZonedDateTime.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/DateToXmlGregorianCalendar.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/JaxbElemToValue.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/JodaDateTimeToXmlGregorianCalendar.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/JodaLocalDateTimeToXmlGregorianCalendar.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/JodaLocalDateToXmlGregorianCalendar.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/JodaLocalTimeToXmlGregorianCalendar.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/LocalDateToXmlGregorianCalendar.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/StringToXmlGregorianCalendar.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/XmlGregorianCalendarToCalendar.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/XmlGregorianCalendarToDate.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/XmlGregorianCalendarToJodaDateTime.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/XmlGregorianCalendarToJodaLocalDate.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/XmlGregorianCalendarToJodaLocalDateTime.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/XmlGregorianCalendarToJodaLocalTime.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/XmlGregorianCalendarToLocalDate.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/XmlGregorianCalendarToString.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/ZonedDateTimeToCalendar.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_1425/Issue1425Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1425/Issue1425Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1425/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1425/Target.java
_(new PR, discussion started in #1439)_
Together with the includeModel directive this will ensure that the type will be written to the file as a FQN if required, otherwise as a simple name.
The PR allows extending templates like this:
```java
<@includeModel name=findType("LocalDate")/>
```
or
```java
<@includeModel name=findType("org.joda.time.LocalDate")/>
```
The given fully-qualified/simple name must be available in the `importTypes` of the builtin method. Unlike it was proposed in #1439 I have not extended `BuiltinMethod` and `HelperMethod` to provide a `Map` with possible `Types` as the included `Types` must be returned in the `importTypes` property, otherwise the import statement will maybe not be added. So it should fail-fast in case someone tries to include a `Type` that might not …
=> #1425 Added findType to VirtualMappingMethod and use it in all builtin templates

processor/src/main/java/org/mapstruct/ap/internal/model/LifecycleCallbackFactory.java, processor/src/main/resources/org/mapstruct/ap/internal/model/BeanMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/builder/lifecycle/BuilderLifecycleCallbacksTest.java, processor/src/test/java/org/mapstruct/ap/test/builder/lifecycle/Item.java, processor/src/test/java/org/mapstruct/ap/test/builder/lifecycle/ItemDto.java, processor/src/test/java/org/mapstruct/ap/test/builder/lifecycle/MappingContext.java, processor/src/test/java/org/mapstruct/ap/test/builder/lifecycle/Order.java, processor/src/test/java/org/mapstruct/ap/test/builder/lifecycle/OrderDto.java, processor/src/test/java/org/mapstruct/ap/test/builder/lifecycle/OrderMapper.java
When doing mappings with builder the effective type should be considered for lifecycle callback methods. The actual target type won't be considered in the lifecycle callbacks
Fixes #1433
=> #1433 Support for lifecycle methods for builders

core-jdk8/src/main/java/org/mapstruct/ValueMapping.java, core/src/main/java/org/mapstruct/ValueMapping.java
I noticed that the String values were used in `@ValueMapping` javadoc and as there are constants available I think it is always better to just use those.
=> Use constants instead of strings in ValueMapping javadoc

processor/src/test/java/org/mapstruct/ap/test/builder/lifecycle/BuilderLifecycleCallbacksTest.java, processor/src/test/java/org/mapstruct/ap/test/builder/lifecycle/MappingContext.java
Added tests for following lifecycle methods mentioned in #1454
* `@BeforeMapping` with no parameters
* `@AfterMapping` with no parameters
* `@AfterMapping` with `@MappingTarget` `PersonBuilder` and returning `Person`
Last entry is not yet checked in #1454, but works
Generated code:
```java
Order target = context.afterWithBuilderTargetReturningTarget( order );
if ( target != null ) {
return target;
}
```
=> #1454 add more tests for builder lifecycle methods

core-common/src/main/java/org/mapstruct/Context.java, core-common/src/main/java/org/mapstruct/ObjectFactory.java, documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/CollectionAssignmentBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/ContainerMappingMethodBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/EnumMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/LifecycleMethodResolver.java, processor/src/main/java/org/mapstruct/ap/internal/model/MapMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/MapperReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/MappingBuilderContext.java, processor/src/main/java/org/mapstruct/ap/internal/model/ObjectFactoryMethodResolver.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/ValueMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MethodRetrievalProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java, processor/src/test/java/org/mapstruct/ap/test/context/objectfactory/ContextObjectFactory.java, processor/src/test/java/org/mapstruct/ap/test/context/objectfactory/ContextWithObjectFactoryMapper.java, processor/src/test/java/org/mapstruct/ap/test/context/objectfactory/ContextWithObjectFactoryTest.java, processor/src/test/java/org/mapstruct/ap/test/context/objectfactory/Valve.java, processor/src/test/java/org/mapstruct/ap/test/context/objectfactory/ValveDto.java
Whereas its possible to have non `@ObjectFactory` annotated methods as object factory in the `uses` method of the mapper, this is not possible on the `Context` annotated parameter objects.
Reason is backwards compatibility: we cannot predict if a user has already parameterless methods on the context object. 
Non `@ObjectFactory` annotated methods are most likely generated factories, like `Jaxb object factories`. It makes sense to include those in the uses part. The context is most likely a user implemented object.
=> #1398 allowing `@ObjectFactory` annotated methods on the context

core-common/src/main/java/org/mapstruct/BeanMapping.java, core-common/src/main/java/org/mapstruct/Builder.java, core-common/src/main/java/org/mapstruct/Mapper.java, core-common/src/main/java/org/mapstruct/MapperConfig.java, documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/BuilderFinisherMethodResolver.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/BuilderType.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/BeanMapping.java, processor/src/main/java/org/mapstruct/ap/internal/prism/PrismGenerator.java, processor/src/main/java/org/mapstruct/ap/internal/processor/DefaultModelElementProcessorContext.java, processor/src/main/java/org/mapstruct/ap/internal/util/MapperConfiguration.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/main/java/org/mapstruct/ap/spi/BuilderInfo.java, processor/src/main/java/org/mapstruct/ap/spi/BuilderProvider.java, processor/src/main/java/org/mapstruct/ap/spi/DefaultBuilderProvider.java, processor/src/main/java/org/mapstruct/ap/spi/MoreThanOneBuilderCreationMethodException.java, processor/src/test/java/org/mapstruct/ap/test/builder/multiple/BuilderConfigDefinedMapper.java, processor/src/test/java/org/mapstruct/ap/test/builder/multiple/BuilderDefinedMapper.java, processor/src/test/java/org/mapstruct/ap/test/builder/multiple/BuilderMapperConfig.java, processor/src/test/java/org/mapstruct/ap/test/builder/multiple/DefaultBuildMethodMapper.java, processor/src/test/java/org/mapstruct/ap/test/builder/multiple/ErroneousMoreThanOneBuildMethodMapper.java, processor/src/test/java/org/mapstruct/ap/test/builder/multiple/ErroneousMoreThanOneBuildMethodWithMapperDefinedMappingMapper.java, processor/src/test/java/org/mapstruct/ap/test/builder/multiple/MultipleBuilderMapperTest.java, processor/src/test/java/org/mapstruct/ap/test/builder/multiple/Source.java, processor/src/test/java/org/mapstruct/ap/test/builder/multiple/Task.java, processor/src/test/java/org/mapstruct/ap/test/builder/multiple/TooManyBuilderCreationMethodsMapper.java, processor/src/test/java/org/mapstruct/ap/test/builder/multiple/build/Process.java, processor/src/test/java/org/mapstruct/ap/test/builder/multiple/builder/Case.java
* When there are multiple build methods look for a method named `build`, if such method exists use it
* When a builder has multiple methods throw an exception and don't use the builder during the mapping
* When a type has multiple builder creation methods throw an exception and don't use the builder
Defaulting to a method named `build` will make sure that a correct method is slected for:
* FreeBuilder - it has two methods: `build` and `buildPartial`
* Protobuf - it has three methods: `getDefaultInstanceForType`, `build` and `buildPartial`
Fixes #1479
=> #1479 Add support for Builders with multiple build methods

processor/src/main/java/org/mapstruct/ap/internal/conversion/JavaLocalDateToDateConversion.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1569/java8/Issue1569Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1569/java8/Issue1569Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1569/java8/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1569/java8/Target.java
* ZoneOffset instead of ZoneId needs to be imported when performing a conversion from LocalDate to Date
Fixed #1569
=> #1569 Make sure that converting Java 8 LocalDate to Date generates correct code

processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java, processor/src/main/java/org/mapstruct/ap/internal/util/NativeTypes.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1558/java8/Car.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1558/java8/Car2.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1558/java8/CarMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1558/java8/Issue1558Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1558/java8/NotNull.java
There's something strange ongoing in JDK (not in Eclipse) when there's an annotation on a method. The return type seems to be influenced by this annotation. A reproducer is added. The reproduce is a java 8 reproducer, but that's probably not necessary. I created a copy of the `@NotNull` locally. That works as well as far is reproducing is concerned.
Feel free to continue on this one and get to the bottom. 
Fixes #1558
=> #1558 Annotations `ElementType.TYPE_USE` not handled correctly 

core-common/src/main/java/org/mapstruct/BeanMapping.java, core-common/src/main/java/org/mapstruct/Mapper.java, core-common/src/main/java/org/mapstruct/MapperConfig.java, core-jdk8/src/main/java/org/mapstruct/Mapping.java, core/src/main/java/org/mapstruct/Mapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/CollectionAssignmentBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/BeanMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/Mapping.java, processor/src/main/java/org/mapstruct/ap/internal/prism/NullValueCheckStrategyPrism.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/util/MapperConfiguration.java, processor/src/test/java/org/mapstruct/ap/test/nullcheck/strategy/HouseDto.java, processor/src/test/java/org/mapstruct/ap/test/nullcheck/strategy/HouseEntity.java, processor/src/test/java/org/mapstruct/ap/test/nullcheck/strategy/HouseMapper.java, processor/src/test/java/org/mapstruct/ap/test/nullcheck/strategy/HouseMapperConfig.java, processor/src/test/java/org/mapstruct/ap/test/nullcheck/strategy/HouseMapperWithConfig.java, processor/src/test/java/org/mapstruct/ap/test/nullcheck/strategy/NullValueCheckTest.java
Some remarks:
The original request was to include it on bean level. However, I see a definite use for it on `@Mapping` level as well. I'm also looking at some more issues. 
One which bothers me as well is #1306. These are merge mappings and especially here its important that null checks work. However, we break some existing behaviour as well if we fixed this. By having fine-grained control, we at least give the user an option to fully specify where to apply this option.
When implementing this I realised that our builders are sometimes very verbose (giving each individual property from `BeanMapping` to the `BeanMappingMethod`. This is a pattern which is repeated. Look at the `ContainerMappingMethod`, `PropertyMappingMethod`. I think we should hand the 'Annotation abstraction, e.g. …
=> #1571 apply nullvaluecheck strategy on all relevant levels, cleanup

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/GeneratedType.java, processor/src/main/java/org/mapstruct/ap/internal/processor/DefaultVersionInformation.java, processor/src/main/java/org/mapstruct/ap/internal/version/VersionInformation.java
The annotation would be used only if the source version is at least RELEASE_9.
Fixes #1551.
There are no tests because we still don't have tests running on Java 9. Once #1309 is implemented we should add tests for this.
I tested this with the examples and it works properly. When Java 10 is used but the source version is lower than 9 then `javax.annotation.Generated` would be used. Otherwise `javax.annotation.processing.Generated` would be used
=> #1551 Use javax.annotation.processing.Generated if it is available

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/AdderWrapper.java, processor/src/test/java/org/mapstruct/ap/test/collection/adder/AdderTest.java, processor/src/test/java/org/mapstruct/ap/test/collection/adder/SourceTargetMapperWithDifferentProperties.java, processor/src/test/java/org/mapstruct/ap/test/collection/adder/_target/TargetWithAnimals.java, processor/src/test/java/org/mapstruct/ap/test/collection/adder/source/SourceWithPets.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/collection/adder/SourceTargetMapperWithDifferentPropertiesImpl.java
A WIP for using the source property name for the adder iteration.
One thing that I noticed is that we are doing a lot of copying around when we can just pass the `Mapping` to the appropriate builders and then use whatever we need in there.
Fixes #1478
=> #1478 Use source property name for the adder iteration

build-config/src/main/resources/build-config/checkstyle.xml, parent/pom.xml, processor/pom.xml, processor/src/test/java/org/mapstruct/ap/testutil/assertions/JavaFileAssert.java, readme.md
* Do not use maven-processor-plugin and use the maven-compiler-plugin annotationProcessors instead
* Update NoPackageCyclesRule and exclude tests
* Update checkstyle to 8.14 and remove FIleContentsHolder module and move SuppressionCommentFilter to the TreeWalker
* Update assertj to 3.11.1 and replace usage of RuntimeIOException (from AssertJ) with UncheckedIOException (from java 8)
* Add how to import MapStruct into IntelliJ and Eclipse into the readme
Needed for further support for Java 9+
=> #1301 Update build with latest dependencies and Java 8 baseline

parent/pom.xml, processor/src/main/java/org/mapstruct/ap/MappingProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/util/AnnotationProcessorContext.java, processor/src/main/java/org/mapstruct/ap/internal/util/FreeBuilderConstants.java, processor/src/main/java/org/mapstruct/ap/spi/AccessorNamingStrategy.java, processor/src/main/java/org/mapstruct/ap/spi/DefaultAccessorNamingStrategy.java, processor/src/main/java/org/mapstruct/ap/spi/FreeBuilderAccessorNamingStrategy.java, processor/src/main/java/org/mapstruct/ap/spi/MapStructProcessingEnvironment.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1566/AbstractBuilder.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1566/Issue1566Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1566/Issue1566Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1566/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1566/Target.java
This fix for this actually depends on #1253. However, I am afraid that we might need to do something more involved like the [`MethodMatcher`](https://github.com/mapstruct/mapstruct/blob/master/processor/src/main/java/org/mapstruct/ap/internal/model/source/MethodMatcher.java). I am not 100% certain whether the `isAssignable` hint added would be enough. Maybe @agudian and @sjaakd can chime in on this as well.
Fixes #1566 
Fixes #1253
=> Add support for initializing the AccessorNamingStrategy with Elements and Types and use Types for determining fluent setters

processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1665/Issue1665Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1665/Issue1665Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1665/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1665/Target.java
Possible fix for #1665 . Could be that this problem is more widespread than for the ADDER_PREFERRED  collection style.
=> Box any primitives before attempting type comparison

core/src/main/java/org/mapstruct/factory/Mappers.java, core/src/test/java/org/mapstruct/factory/MappersTest.java
Added `Mappers#getMapperClass(Class<?>)`
I am unsure if it's fine to try loading the class with the `ServiceLoader` also in this case
=> #1657: Add Mappers.getMapperClass for getting the class of a Mapper

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc
based on the fact that the command "compile" was deprecated in Gradle I was changing that and updating the version of the net.ltgt.apt by the latest
Fixes #1695
=> 1695 update gradle installation

processor/src/main/java/org/mapstruct/ap/spi/FreeBuilderAccessorNamingStrategy.java, processor/src/main/java/org/mapstruct/ap/spi/ImmutablesAccessorNamingStrategy.java, processor/src/main/java/org/mapstruct/ap/spi/ImmutablesBuilderProvider.java
Mark the Immutables BuilderProvider and AccessorNamingStrategy and the FreeBuilderAccessorNamingStrategy as Experimental.
Was not entirely sure whether we should do this or not.
=> Mark some Builder providers as Experimental

processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1698/Erroneous1698Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1698/Issue1698Test.java
When mapping A to C via B,  A -> B -> C the 2 step mechanism tries B. Some builtin methods have `java.lang.Object` as intermediate result (user methods might have the same). Most notably: `T map(JAXBElement<T> source)` in which the result `T` is in essence an `java.lang.Object`.
This results in the strange error messages.
=> #1698 Skip "java.lang.Object" as intermediate result in 2 step mappings

core/src/main/java/org/mapstruct/MapperConfig.java, processor/src/main/java/org/mapstruct/ap/internal/util/MapperConfiguration.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1435/Config.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1435/InObject.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1435/Issue1435Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1435/Issue1435Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1435/OutObject.java
It adds import field to @MapperConfig annotation.
Fixes #1435
=> #1435 add import to MapperConfig

processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1719/Issue1719Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1719/Issue1719Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1719/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1719/SourceElement.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1719/Target.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1719/TargetElement.java
Currently there's the strange error message as described in the PR..
For adder methods MapStuct cannot generate an update method. MapStruct would cannot know how to remove objects from the child-parent relation. It cannot even assume that the the collection can be cleared at forehand. Therefore the only sensible choice is for MapStruct to create a create method for the target elements.
=> #1719 strange error message for selecting collection update methods

processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java, processor/src/test/java/org/mapstruct/ap/test/builtin/BuiltInTest.java, processor/src/test/java/org/mapstruct/ap/test/builtin/bean/BigDecimalProperty.java, processor/src/test/java/org/mapstruct/ap/test/builtin/bean/SomeType.java, processor/src/test/java/org/mapstruct/ap/test/builtin/bean/SomeTypeProperty.java, processor/src/test/java/org/mapstruct/ap/test/builtin/mapper/JaxbMapper.java
I'll adapt the commit name later to an issue (to be written, or refer to the old issue for which I provided extra unit test)... But have a look..
There are things I forgot in the 2 step mapping which assure this goes right. It seems that rather than using conversion / built in directly, we only use the source-return types and than still resolve the method. That makes sure it works.. I probably need to add some additional comment to make this clear.
=> extra-test-jaxbelem

.travis.yml, integrationtest/pom.xml, processor/pom.xml, processor/src/main/java/org/mapstruct/ap/internal/conversion/StaticParseToStringConversion.java, processor/src/test/java/org/mapstruct/ap/test/abstractclass/AbstractClassTest.java, processor/src/test/java/org/mapstruct/ap/test/abstractclass/AbstractReferencedMapper.java, processor/src/test/java/org/mapstruct/ap/test/abstractclass/Holder.java, processor/src/test/java/org/mapstruct/ap/test/abstractclass/ReferencedMapper.java, processor/src/test/java/org/mapstruct/ap/test/abstractclass/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1170/AdderTest.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_775/IterableWithBoundedElementTypeTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/date/DateConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/jodatime/JodaConversionTest.java, processor/src/test/java/org/mapstruct/ap/testutil/assertions/JavaFileAssert.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/AnnotationProcessorTestRunner.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/Compiler.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/CompilingStatement.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/DisabledOnCompiler.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/EnabledOnCompiler.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/InnerAnnotationProcessorRunner.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/Jdk11CompilingStatement.java
@filiphr This makes _mapstruct-processor_ compile for me with OpenJDK 11. But tests fail as the test runner seems not to find any classes from the JDK (stuff like `Integer` etc.). Have you encountered this, too?
Fixes #1675
=> #1675 Making mapstruct-processor compileable with OpenJDK 11

parent/pom.xml
With this MapStruct processor compiles with Open JDK 13 (EA)
=> Update plugins to latest versions

processor/src/main/resources/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_1738/Issue1738Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1738/Issue1738Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1738/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1738/Target.java
=> #1738: Use typeBound for the return type of the nested property mapping method and for the definition of the properties within the method

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc
=> Typo in builder documentation

parent/pom.xml
According to https://maven.apache.org/pom.html#Prerequisites, prerequisites are only checked with Maven 2.
The maven-enforcer-plugin could be used for this check. However, Considering that Maven 2 is not really used I think that we don't really need such check in our build
=> Remove use of prerequisites from parent pom.xml

processor/pom.xml
Using optional because IntelliJ is picking up hickory as a transitive
dependency and runs the hickory processor in projects using mapstruct-processor.
This happens only when the processor is defined in the maven-compiler annotationProcessorPaths.
This is related to https://youtrack.jetbrains.com/issue/IDEA-200481.
=> Make hickory an optional dependency as well

documentation/src/main/asciidoc/mapping-streams.asciidoc, documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc
fix typo in documentation "Using builders"
fix generated code example in stream mapping
=> Fix typo and code error in documentation

readme.md
I just noticed that the readme in this repo says that java 1.6 is required.. I updated this and added information about the IntelliJ plugin to the file.
=> Update Readme / Java 1.8 required

processor/src/main/java/org/mapstruct/ap/internal/model/LifecycleMethodResolver.java, processor/src/main/java/org/mapstruct/ap/internal/model/ObjectFactoryMethodResolver.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/MethodSelectors.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/TypeSelector.java, processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1457/BookMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1457/DifferentOrderingBookMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1457/ErroneousBookMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1457/Issue1457Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1457/ObjectFactoryBookMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1457/SourceBook.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1457/TargetBook.java
In case a lifecycle method has multiple matching parameters (e. g. same type)
all parameter names must match exactly with the ones from the mapping method,
otherwise the lifecycle method will not be used and a warning will be shown.
As soon as the warning is displayed the lifecycle method will *not* be used, this might be a breaking change, but if the method will be used there is a high chance that it will be used in a wrong way (invalid parameter ordering, see #1457). The warning is not coming up for any of our tests.
I would prefer that only the names of the ambiguous parameters must match, but imho this would lead to bigger and really complex changes (see discussion in the ticket). As this here should already fix the issue and provide a possible solution (rename all parameters) it …
=> [#1457] Stricter matching for lifecycle methods / non-unique parameters

processor/src/main/java/org/mapstruct/ap/internal/model/IterableCreation.java, processor/src/main/resources/org/mapstruct/ap/internal/model/IterableCreation.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_1797/Customer.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1797/CustomerDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1797/Issue1797Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1797/Issue1797Test.java
=> #1797 Use EnumSet.noneOf when creating a new instance of EnumSet

processor/src/main/java/org/mapstruct/ap/spi/DefaultBuilderProvider.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1751/Holder.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1751/Issue1751Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1751/Issue1751Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1751/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1751/Target.java
When a method has a generic signature and the builder type is generic then the method return type does not match the builder type.
Therefore check only for raw types.
Add extra check for void method since a void method can't be a builder creation method
Fixes #1751 
Fixes #1716
=> #1751 Fix handling of possible builder creation methods with generic signature

documentation/src/main/asciidoc/mapstruct-reference-guide.asciidoc
This sentence is talking about `@Target`, not `@Retention`.
Also, let's use 'type' instead of 'class' to line up with `ElementType.TYPE`.
=> Improve terms in qualifier docs

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/AdderWrapper.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/ArrayCopyWrapper.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/ExistingInstanceSetterWrapperForCollectionsAndMaps.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/StreamAdderWrapper.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/UpdateWrapper.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java
Replace addAll in collections on constructor in org.mapstruct.ap.internal.model.assignment
Fix typo in org.mapstruct.ap.internal.model.common.Type
I'm sorry, but I have added "dist: trusty" in travis.yml . I can't pass checks without it. I'll remove it if you will help me to pass checks without it.
=> Fix warning addAll in org.mapstruct.ap.internal.model.assignment

processor/src/test/java/org/mapstruct/ap/test/java8stream/StreamMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/java8stream/StringHolder.java, processor/src/test/java/org/mapstruct/ap/test/java8stream/context/StreamWithContextTest.java, processor/src/test/java/org/mapstruct/ap/test/java8stream/defaultimplementation/DefaultStreamImplementationTest.java, processor/src/test/java/org/mapstruct/ap/test/java8stream/defaultimplementation/NoSetterStreamMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/java8stream/defaultimplementation/NoSetterTarget.java, processor/src/test/java/org/mapstruct/ap/test/java8stream/defaultimplementation/Target.java, processor/src/test/java/org/mapstruct/ap/test/java8stream/defaultimplementation/TargetFoo.java, processor/src/test/java/org/mapstruct/ap/test/java8stream/streamtononiterable/StreamToNonIterableMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/java8stream/streamtononiterable/StringListMapper.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/Car.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/CarDto.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/House.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/MultipleForgedMethodsTest.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/NestedSimpleBeansMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/RoofDto.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/User.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/UserDto.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/exceptions/EntityFactory.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/maps/AntonymsDictionary.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/maps/Word.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/maps/WordDto.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/multiplecollections/Garage.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/multiplecollections/GarageDto.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/other/RoofDto.java, processor/src/test/java/org/mapstruct/ap/test/nestedbeans/other/UserDto.java
Fix minor warnings in test packages java8stream and nestedbeans:
remove unnecessary generic types from collection,
remove unnecessary throws from test methods,
simplify equals in test dto
=> Fix minor warnings in test packages java8stream and nestedbeans

integrationtest/src/test/java/org/mapstruct/itest/testutil/runner/ProcessorSuiteRunner.java, processor/src/main/java/org/mapstruct/ap/internal/model/HelperMethod.java, processor/src/main/java/org/mapstruct/ap/internal/util/Strings.java, processor/src/main/java/org/mapstruct/ap/internal/writer/ModelWriter.java
Fix minor warnings:
remove unnecessary generic type for collections,
replace Charset.forName on StandartCharsets
=> Fix minor warnings

processor/src/main/java/org/mapstruct/ap/internal/util/MapperConfiguration.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1790/Issue1790Config.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1790/Issue1790Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1790/Issue1790Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1790/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1790/Target.java
Thanks to @saw303 for the good reproducal.
Fixes #1790
=> #1790 Use mapperPrism.values.nullValuePropertyMappingStrategy when retrieving NullValuePropertyMappingStrategy

documentation/src/main/asciidoc/chapter-5-data-type-conversions.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/source/builtin/BuiltInMappingMethods.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/builtin/BuiltInMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/builtin/LocalDateTimeToXmlGregorianCalendar.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/builtin/XmlGregorianCalendarToLocalDateTime.java, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/LocalDateTimeToXmlGregorianCalendar.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/source/builtin/XmlGregorianCalendarToLocalDateTime.ftl, processor/src/test/java/org/mapstruct/ap/test/conversion/java8time/LocalDateTimeToXMLGregorianCalendarConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/java8time/localdatetimetoxmlgregoriancalendarconversion/Source.java, processor/src/test/java/org/mapstruct/ap/test/conversion/java8time/localdatetimetoxmlgregoriancalendarconversion/SourceTargetMapper.java, processor/src/test/java/org/mapstruct/ap/test/conversion/java8time/localdatetimetoxmlgregoriancalendarconversion/Target.java
@filiphr @sjaakd I need your opinion about converting nanoseconds and miliseconds in this PR. I didn't convert it, because [XMLGregorianCalendar](https://docs.oracle.com/javase/7/docs/api/javax/xml/datatype/XMLGregorianCalendar.html) have milliseconds, but [java.time.LocalDateTime](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDateTime.html)  doesn't have milliseconds. 
I made some comments in code and  in documentation. How should it be? Convert or not?
Fixes #1791
=> #1791 Support for conversion between java.time.LocalDateTime and javax.xml.datatype.XMLGregorianCalendar

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1881/Issue1881Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1881/VehicleDtoMapper.java
This aligns with the way the ReportingPolicy is handled for unmappedTargetPolicy when mapping references are for forged methods
Fixes #1881
=> #1881 Use ReportingPolicy#IGNORE for unmappedSourcePolicy when mapping references are for forged methods

processor/src/main/java/org/mapstruct/ap/internal/processor/MethodRetrievalProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1788/Issue1788Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1788/Issue1788Test.java
We should try to reserve all enum-to-x mappings for the future. Perhaps have a `@NonValueMapping` annotation or something to allow to fallback on regular mapping always. 
Now I think of it.. Having some kind of marker is not a bad idea. We just introduced string-to-enum and enum-to-string which might break existing functionality.  Scanning for `@ValueMapping` only might not do the trick (not mandatory to have mappings)
Or we check if there's not an @BeanMapping before definitively establishing it's an enum mapping
=> #1788 allowing enum / not enum by removing checks

copyright.txt, integrationtest/pom.xml, integrationtest/src/test/java/org/mapstruct/itest/tests/GradleIncrementalCompilationTest.java, integrationtest/src/test/resources/gradleIncrementalCompilationTest/build.gradle, integrationtest/src/test/resources/gradleIncrementalCompilationTest/settings.gradle, integrationtest/src/test/resources/gradleIncrementalCompilationTest/src/main/java/org/mapstruct/itest/gradle/lib/TestMapper.java, integrationtest/src/test/resources/gradleIncrementalCompilationTest/src/main/java/org/mapstruct/itest/gradle/lib/UnrelatedComponent.java, integrationtest/src/test/resources/gradleIncrementalCompilationTest/src/main/java/org/mapstruct/itest/gradle/model/Source.java, integrationtest/src/test/resources/gradleIncrementalCompilationTest/src/main/java/org/mapstruct/itest/gradle/model/Target.java, processor/src/main/resources/META-INF/gradle/incremental.annotation.processors
As discussed in #1420, this PR makes Mapstruct compatible with Gradle's incremental annotation processing feature. The actual change is just one file with a single line of configuration; the bulk of this contribution is in the integration tests, written using the [Gradle TestKit](https://docs.gradle.org/current/userguide/test_kit.html).
=> 1420 gradle incremental

documentation/src/main/asciidoc/chapter-2-set-up.asciidoc
When configuring MapStruct compilerArgs *add* them, not *replace* them
=> Updated docs to add compilerArgs instead of replacing them.

processor/src/main/java/org/mapstruct/ap/internal/model/GeneratedType.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2001/Entity.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2001/EntityExtra.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2001/Form.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2001/FormExtra.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2001/Issue2001Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2001/Issue2001Test.java
When the typeToAdd is an array then TypeElement is null and ComponentType is the one that would be imported
Fixes #2001
=> #2001 Avoid NPE when checking whether import type element is nested

processor/src/main/java/org/mapstruct/ap/internal/model/Decorator.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2021/Issue2021Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2021/Issue2021Test.java
We need to treat the import of the decoratorType specially when it is nested.
Calling addIfImportRequired is not the most correct approach since it would
lead to checking if the type is to be imported and that would be false
since the Decorator is a nested class within the Mapper.
However, when generating the Decorator this is not needed, because the Decorator is a top level class itself
In a nutshell creating the Decorator should have its own ProcessorContext, but it doesn't
Fixes #2021 
This was a tricky one. It was affected by the fix for #1460 and #1576
=> #2021 Generate compilable code when Decorator is nested within the Mapper

integrationtest/src/test/java/org/mapstruct/itest/tests/MavenIntegrationTest.java, parent/pom.xml, processor/src/test/java/org/mapstruct/ap/test/abstractclass/generics/GenericsHierarchyTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/date/DateConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/jodatime/JodaConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/verbose/VerboseTest.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/AnnotationProcessorTestRunner.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/Compiler.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/DisabledOnCompiler.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/EclipseCompilingStatement.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/EnabledOnCompiler.java, processor/src/test/java/org/mapstruct/ap/testutil/runner/InnerAnnotationProcessorRunner.java
Add forced dependencies to force correct resolution.
The `GenericsHierarchyTest#determinesAnimalKeyGetter` fails with the Eclipse compiler. The problem is that for `AbstractAnimal` the `getKey` method is resolved to the one from `Identifiable<KeyOfAllBeings>`. However, in javac it is resolved to the one from `IAnimal<AnimalKey>`. Not sure if this is a bug in javac or ecj. Maybe @agudian can weigh on his experience 😄. 
The problem occurs due in:
https://github.com/mapstruct/mapstruct/blob/04576de1d1689aac439c092164c1fef7175e57c3/processor/src/main/java/org/mapstruct/ap/internal/util/Executables.java#L227-L244
On line 234 javac returns `true`, but ecj returns `false`
Fixes #1553
=> Update tycho-compiler-jdt to latest 1.2.0 version

integrationtest/src/test/java/org/mapstruct/itest/tests/MavenIntegrationTest.java, integrationtest/src/test/resources/usesTypeGenerationTest/generator/pom.xml, integrationtest/src/test/resources/usesTypeGenerationTest/generator/src/main/java/org/mapstruct/itest/usestypegeneration/UsesTypeGenerationProcessor.java, integrationtest/src/test/resources/usesTypeGenerationTest/generator/src/main/resources/META-INF/services/javax.annotation.processing.Processor, integrationtest/src/test/resources/usesTypeGenerationTest/pom.xml, integrationtest/src/test/resources/usesTypeGenerationTest/usage/pom.xml, integrationtest/src/test/resources/usesTypeGenerationTest/usage/src/main/java/org/mapstruct/itest/usestypegeneration/usage/Order.java, integrationtest/src/test/resources/usesTypeGenerationTest/usage/src/main/java/org/mapstruct/itest/usestypegeneration/usage/OrderDto.java, integrationtest/src/test/resources/usesTypeGenerationTest/usage/src/main/java/org/mapstruct/itest/usestypegeneration/usage/OrderMapper.java, integrationtest/src/test/resources/usesTypeGenerationTest/usage/src/test/java/org/mapstruct/itest/usestypegeneration/usage/GeneratedUsesTypeTest.java, parent/pom.xml, processor/src/main/java/org/mapstruct/ap/MappingProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/DelegatingOptions.java
Due to a bug in javac (JDK-8229535) for an annotation with Class values, instead of returning a TypeMirror with TypeKind#ERROR the compiler returns the string "<error>". Eclipse doesn't have this problem currently.
Fixes #2056 
This depends on https://github.com/mapstruct/tools-gem/pull/4. We would need a new release of tools-gem to handle this properly.
=> #2056: Handle null TypeMirror in uses and import gracefully

.gitignore, parent/pom.xml, processor/pom.xml
For some reason when using annotationProcessorPaths IntelliJ includes the provided and test scoped dependencies on the annotation processor paths.
With this change there would be no test dependencies that IntelliJ can add.
Fixes #1857
=> #1857 Use flatten-maven-plugin to remove test dependencies from released pom

documentation/src/main/asciidoc/chapter-13-using-mapstruct-spi.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/MappingBuilderContext.java, processor/src/main/java/org/mapstruct/ap/internal/model/ValueMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/processor/DefaultModelElementProcessorContext.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/processor/ModelElementProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/util/AnnotationProcessorContext.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/main/java/org/mapstruct/ap/spi/DefaultEnumNamingStrategy.java, processor/src/main/java/org/mapstruct/ap/spi/EnumNamingStrategy.java, processor/src/test/java/org/mapstruct/ap/test/value/spi/CheeseType.java, processor/src/test/java/org/mapstruct/ap/test/value/spi/CustomCheeseMapper.java, processor/src/test/java/org/mapstruct/ap/test/value/spi/CustomCheeseType.java, processor/src/test/java/org/mapstruct/ap/test/value/spi/CustomEnumMarker.java, processor/src/test/java/org/mapstruct/ap/test/value/spi/CustomEnumNamingStrategy.java, processor/src/test/java/org/mapstruct/ap/test/value/spi/CustomEnumNamingStrategyTest.java, processor/src/test/java/org/mapstruct/ap/test/value/spi/CustomErroneousEnumNamingStrategy.java, processor/src/test/java/org/mapstruct/ap/test/value/spi/CustomErroneousEnumNamingStrategyTest.java, processor/src/test/java/org/mapstruct/ap/test/value/spi/OverridesCustomCheeseMapper.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/value/spi/CustomCheeseMapperImpl.java
Add a new EnumNamingStrategy SPI which can be used for customizing the way enums are matched by name.
It is similar to the AccessorNamingStrategy such that it allows implementors to provide a custom way of defining a property.
Related to #796, #1220, #1789 and #1667
@seime this is the PR with the SPI allowing custom way of name based mapping enums. I took the interface you did in #2045 and iterated with my ideas on top of it. Can you please have a look and tell me how it looks to you.
=> Add EnumNamingStrategy SPI

processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java, processor/src/test/java/org/mapstruct/ap/test/mappingcontrol/CloningListMapper.java, processor/src/test/java/org/mapstruct/ap/test/mappingcontrol/CustomerDto.java, processor/src/test/java/org/mapstruct/ap/test/mappingcontrol/MappingControlTest.java, processor/src/test/java/org/mapstruct/ap/test/mappingcontrol/OrderItemDto.java, processor/src/test/java/org/mapstruct/ap/test/mappingcontrol/OrderItemKeyDto.java
Should be done on their type parameters instead of the types themselves.
I was updating our deep clone example to use the new functionality and realized that it is not working properly for collections.
=> #695 Check for direct assignment for iterable, stream or map types

documentation/src/main/asciidoc/chapter-3-defining-a-mapper.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/constructor/visibility/ConstructorVisibilityTest.java, processor/src/test/java/org/mapstruct/ap/test/constructor/visibility/SimpleWithPublicConstructorMapper.java, processor/src/test/java/org/mapstruct/ap/test/constructor/visibility/SimpleWithPublicParameterlessConstructorAndDefaultAnnotatedMapper.java, processor/src/test/java/org/mapstruct/ap/test/constructor/visibility/SimpleWithPublicParameterlessConstructorMapper.java
New rules:
1. Constructor annotated with @Default (from any package) has highest precedence
2. If there is a single public constructor then it would be used to construct the object
3. If a parameterless constructor exists then it would be used to construct the object, and the other constructors will be ignored
Fixes #2150
=> #2150 Change the rules for how a constructor for mapping is picked

processor/src/main/java/org/mapstruct/ap/internal/processor/MethodRetrievalProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2185/Issue2185Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2185/TodoMapper.java
=> #2185 Fix StackOverflow error when recursive use of mapper in Mapper#uses

processor/src/main/java/org/mapstruct/ap/internal/util/Strings.java, processor/src/test/java/org/mapstruct/ap/internal/util/StringsTest.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2197/Issue2197Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2197/Issue2197Test.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_2197/Issue2197MapperImpl.java
=> #2197 Strip leading underscores and digits when sanitizing identifier name

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2077/Issue2077ErroneousMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2077/Issue2077Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2125/Comment.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2125/Issue2125ErroneousMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2125/Issue2125Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2125/Issue2125Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2125/Repository.java
Fixes #2125 
This is a second iteration of a solution for #2125, in which we enforce the usage of `source` in `@Mapping` when there are multiple source parameters
=> #2125 Report an error when source parameter could not be determined from target mapping

processor/src/main/java/org/mapstruct/ap/internal/model/common/TypeFactory.java, processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2213/Car.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2213/Car2.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2213/CarMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2213/Issue2213Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2213/NotNull.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_2213/CarMapperImpl.java
(we are cloning them anyways)
Additionally fix problem when annotations `ElementType.TYPE_USE` not handled correctly for javac
Fixes #2213
=> #2213: primitive arrays should be directly mapped

processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/SourceReference.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2221/Issue2221Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2221/RestConfig.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2221/RestSiteDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2221/RestSiteMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2221/SiteDto.java
Fixes #2221
I also did some small refactoring as the `Collectors.reducing( (a, b) -> null )` was really confusing to me.
=> #2221: Fix configuration inheritance when there are multiple matching source parameters of the same type

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2125/Issue2125Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2125/Issue2125Test.java, processor/src/test/java/org/mapstruct/ap/test/defaultvalue/CountryMapperMultipleSources.java, processor/src/test/java/org/mapstruct/ap/test/defaultvalue/DefaultValueTest.java, processor/src/test/java/org/mapstruct/ap/test/defaultvalue/ErroneousMissingSourceMapper.java
When having multiple source properties and only target is defined then the same rules should be applied as if there was no mapping:
* First we check for a matching property in any of the source type
* Second we check if the parameter name matches
Fixes: #2206
Fixes: #2214
Fixes: #2220
=> #2206, #2214, #2220: Source property should be correctly determined when only target is defined

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/MappingReferences.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2236/Car.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2236/CarDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2236/CarMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2236/Issue2236Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2236/Owner.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2236/Vehicle.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedbeans/mixed/FishTankMapperImpl.java
Make sure that MappingReferences are taken into consideration when comparing whether 2 mapping methods are equal.
This makes sure that when using nested target mappings that have the same property mappings, but different mappings 2 distinct methods will be created
Fixes #2236 
In 1.3.1.Final this worked by accident because the property mappings in the `BeanMappingMethod` were in a different order. However, we should take the mapping references that were used to construct the method when comparing whether 2 methods are equals.
=> #2236 Different nested target mappings should generate different intermediate methods

processor/src/main/java/org/mapstruct/ap/internal/model/source/MethodMatcher.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2233/Issue2233Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2233/Program.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2233/ProgramAggregate.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2233/ProgramDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2233/ProgramMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2233/ProgramResponseDto.java
e.g. method signature such as
```
<T> T fromOptional(Optional<T> optional)
```
when `T` resolves to another generic class such as `Collection<String>`
Fixes #2233 
You are the generics master @sjaakd, what do you think?
=> #2233 Allow generic of generics in types when matching

processor/pom.xml
Doing this would make sure that starting from Spring Boot 2.4 the mapstruct-processor will not be included in the fat jar produced by the Spring Boot maven plugin if people have it as a maven provided dependency.
This is an alternative if people are not using the maven-compiler-plugin annotationProcessorPaths
Fixes #2244
=> #2244 Mark mapstruct-processor jar as Spring-Boot-Jar-Type: annotation-processor

documentation/src/main/asciidoc/chapter-14-third-party-api-integration.asciidoc, documentation/src/main/asciidoc/chapter-3-defining-a-mapper.asciidoc
This adds a new subsection describing the integration with Lombok based on a brief discussion (https://github.com/mapstruct/mapstruct/issues/2258). 
The pull requests includes:
- Maven and Gradle dependencies setup
- Maven and Gradle annotation processors setup
- Reference to the required `lombok-mapstruct-binding` dependency newly as of Lombok 1.18.16
- Simple usage of MapStruct + Lombok
=> Lombok subsection

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/SetterWrapper.java, processor/src/main/resources/org/mapstruct/ap/internal/model/BeanMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_2023/Issue2023Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2023/Issue2023Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2023/NewPersonRequest.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2023/PersonDto.java, processor/src/test/java/org/mapstruct/ap/test/constructor/manysourcearguments/ManySourceArgumentsConstructorMapper.java, processor/src/test/java/org/mapstruct/ap/test/constructor/manysourcearguments/ManySourceArgumentsConstructorMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/manysourcearguments/ExampleMapper.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/manysourcearguments/ExampleMember.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/manysourcearguments/ExampleSource.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/manysourcearguments/ExampleTarget.java, processor/src/test/java/org/mapstruct/ap/test/updatemethods/manysourcearguments/ManyArgumentsUpdateMappingTest.java
Fixes problems when property mapping is using source parameter and has default value / expression or is doing an update
Fixes #2274 
Fixes #2023
I am not entirely happy with the solution, but I don't see currently how we can avoid this. Our `PropertyMapping` know too much about the `BeanMappingMethod` and vice versa
=> #2274, #2023 Fix problems with property mapping using source parameters

documentation/src/main/asciidoc/chapter-2-set-up.asciidoc
See official maven doc on this: https://maven.apache.org/plugins/maven-compiler-plugin/examples/pass-compiler-arguments.html
Otherwise for example intellij doesn't recognize the compiler options on maven import
=> Example uses wrong maven plugin configuration

documentation/src/main/asciidoc/chapter-10-advanced-mapping-options.asciidoc, documentation/src/main/asciidoc/chapter-5-data-type-conversions.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/source/DefaultOptions.java
`MappingConfig` does not actually exists.
Fixes #2293
=> #2293 Use MapperConfig instead of MappingConfig in the documentation

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2301/Artifact.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2301/ArtifactDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2301/Issue2301Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2301/Issue2301Test.java
Fixes #2301
This is a regression from 1.3. In 1.3 it worked correctly because we were checking the `@Mapping` only once, i.e. when they were defined, but not during the creation of the bean mapping method.
=> #2301 Implicitly ignore forward inherited mappings from different method types

integrationtest/pom.xml, integrationtest/src/test/resources/lombokBuilderTest/pom.xml, parent/pom.xml, processor/src/test/java/org/mapstruct/ap/test/exceptions/ExceptionTestMapper.java
* Upgrade japicmp-maven-plugin to 0.15.2
* Do not use deprecated for removal Long constructor
* Update Spring to 5.3.3
* Upgrade Lombok to 1.18.16
=> Small fixes for Java 16

processor/src/main/java/org/mapstruct/ap/internal/model/ContainerMappingMethodBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java, processor/src/test/java/org/mapstruct/ap/test/selection/qualifier/errors/ErroneousMessageByNamedWithIterableMapper.java, processor/src/test/java/org/mapstruct/ap/test/selection/qualifier/errors/QualfierMessageTest.java, processor/src/test/java/org/mapstruct/ap/test/selection/qualifier/iterable/Cities.java, processor/src/test/java/org/mapstruct/ap/test/selection/qualifier/iterable/IterableAndQualifiersTest.java, processor/src/test/java/org/mapstruct/ap/test/selection/qualifier/iterable/Rivers.java, processor/src/test/java/org/mapstruct/ap/test/selection/qualifier/iterable/TopologyWithoutIterableMappingMapper.java
With this change we are relaxing the error handling when qualifiers are used in `@Mapping`
and we allow defining qualifiers for collections / array mapping to mean the same as if it was defined on `@IterableMapping`
i.e. apply the qualifier on the element mapping
Fixes #2250
Fixes #2324
=> #2250, #2324 Do not throw error when qualifier is missing on iterable mapping

documentation/src/main/asciidoc/chapter-2-set-up.asciidoc, readme.md
Remove obsolete net.ltgt.apt
Use com.diffplug.eclipse.apt for Eclipse
IntelliJ works transparently
Fixes #2346
=> #2346 Update documentation and readme about MapStruct and Gradle

processor/src/main/java/org/mapstruct/ap/internal/model/IterableMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2352/Issue2352Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2352/dto/TheDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2352/dto/TheModel.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2352/dto/TheModels.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2352/mapper/TheModelMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2352/mapper/TheModelsMapper.java
When the Iterable type we are mapping is not generic
(i.e. it is a custom type extending an Iterable) then the source element type
which is included in the loop was not imported.
Fixes #2352
=> #2352 Add source element type for Iterable mappings

processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2347/ErroneousClassWithPrivateMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2347/Issue2347Test.java
Provide a compiler error message instead of generating code that will not compile
Fixes #2347
=> #2347 Do not generate mapper implementation for private mappers

documentation/src/main/asciidoc/chapter-2-set-up.asciidoc
Removed Java 9 specific documentation as we are already in Java 15 and Java 11 LTS.
=> #2366 remove java 9 specific documentation

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2356/Issue2356Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2356/Issue2356Test.java
Fixes #2356
This worked on 1.3 because we always ignored invalid target references after reversing them.
=> #2356 Implicitly ignore reverse inherited mappings that do not have read and write methods

processor/src/main/java/org/mapstruct/ap/internal/model/Decorator.java, processor/src/main/java/org/mapstruct/ap/internal/model/GeneratedType.java, processor/src/main/java/org/mapstruct/ap/internal/model/Mapper.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MapperServiceProcessor.java, processor/src/main/resources/org/mapstruct/ap/internal/model/GeneratedType.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_2393/Address.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2393/AddressDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2393/Country.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2393/CountryDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2393/Issue2393Test.java
With this we make sure that the implementation type will have a correct import in case of a clash with another mapper named the same
Fixes #2393
=> #2393 Use includeModel when generating GeneratedType

processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/SourceReference.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2042/Issue2402Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2042/Issue2402Test.java
=> #2402 Always add source parameter name when constructing the source references for target this

processor/src/main/java/org/mapstruct/ap/internal/model/CollectionAssignmentBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/PropertyMapping.java, processor/src/test/java/org/mapstruct/ap/test/source/presencecheck/spi/CollectionPresenceMapper.java, processor/src/test/java/org/mapstruct/ap/test/source/presencecheck/spi/CollectionWithNonDirectMapper.java, processor/src/test/java/org/mapstruct/ap/test/source/presencecheck/spi/CollectionWithNullValueCheckMapper.java, processor/src/test/java/org/mapstruct/ap/test/source/presencecheck/spi/NonDirectMapper.java, processor/src/test/java/org/mapstruct/ap/test/source/presencecheck/spi/PresenceCheckMappingTest.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_913/DomainDtoWithPresenceCheckMapperImpl.java
=> #2423 Use SetterWrapperForCollectionsAndMapsWithNullCheck if the source has a presence check method

processor/src/main/java/org/mapstruct/ap/internal/util/AbstractElementUtilsDecorator.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2437/Issue2437Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2437/Phone.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2437/PhoneDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2437/PhoneMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2437/PhoneParent1Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2437/PhoneParent2Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2437/PhoneSuperMapper.java
When using the diamond inheritance a TypeElement might be visited twice.
This is however, incorrect. We need to visit a TypeElement exactly once.
Fixes #2437
=> #2437 Do not visit the same type element twice when retrieving methods

.github/workflows/java-ea.yml, .github/workflows/main.yml, integrationtest/src/test/java/org/mapstruct/itest/tests/MavenIntegrationTest.java, integrationtest/src/test/resources/jaxbTest/pom.xml, parent/pom.xml
Update GitHub Actions for tests to run on Java 11, 13, 16 and 17-ea.
Update Lombok so tests can run on 16+
Add jaxb-runtime dependency to the maven-jaxb2-plugin see https://github.com/highsource/maven-jaxb2-plugin/issues/148
Disable cdi integration test on Java 16+ until we find a solution for them
Fixes #2466
=> #2466 Update dependencies so tests run on Java 16+

parent/pom.xml, processor/pom.xml, processor/src/test/java/org/mapstruct/ap/internal/util/StringsTest.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_1523/java8/Issue1523Test.java, processor/src/test/java/org/mapstruct/ap/test/builtin/BuiltInTest.java, processor/src/test/java/org/mapstruct/ap/test/builtin/DatatypeFactoryTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/date/DateConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/java8time/Java8TimeConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/jodatime/JodaConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/numbers/NumberFormatConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/spring/compileoptionconstructor/SpringCompileOptionConstructorMapperTest.java, processor/src/test/java/org/mapstruct/ap/test/injectionstrategy/spring/constructor/SpringConstructorMapperTest.java, processor/src/test/java/org/mapstruct/ap/test/nestedmethodcall/NestedMappingMethodInvocationTest.java, processor/src/test/resources/junit-platform.properties
Configure the JUnit Platform to run the processor tests in parallel by running different test classes in concurrent threads
Fixes #2446
=> #2446 Use DefaultLocale and DefaultTimeZone from JUnit Pioneer

core/src/main/java/org/mapstruct/DecoratedWith.java, core/src/main/java/org/mapstruct/InheritInverseConfiguration.java, core/src/main/java/org/mapstruct/Mapping.java, core/src/main/java/org/mapstruct/ValueMapping.java, core/src/main/java/org/mapstruct/control/MappingControl.java, distribution/pom.xml, processor/src/main/java/org/mapstruct/ap/internal/model/Mapper.java, processor/src/main/java/org/mapstruct/ap/internal/model/ObjectFactoryMethodResolver.java, processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/AbstractReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/TargetReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/BeanMappingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SelectionParameters.java, processor/src/main/java/org/mapstruct/ap/internal/util/accessor/Accessor.java, processor/src/main/java/org/mapstruct/ap/spi/BuilderInfo.java
Remove the org.jboss.apiviz.APIviz doclet since it is no longer compatible with Java 11.
Add new group in the Javadoc for the MapStruct Processor SPI
Fix Javadoc warnings
Fixes #2108
=> #2108 Make sure Javadoc can be generated with Java 11

processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/SourceReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2439/ErroneousIssue2439Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2439/Issuer2439Test.java
Provide better error message if most similar word is null, i.e. type has no properties
Fixes #2439
=> #2439 Do not throw NPE getting accessors for null typeElement

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MapperOptions.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/missingignoredsource/ErroneousSourceTargetMapper.java, processor/src/test/java/org/mapstruct/ap/test/missingignoredsource/MissingIgnoredSourceTest.java
PR for #2481 - WIP
Optionally get warned / error if ignored source properties are missing (this way you can ensure an exact 1:1 correspondence between the declarations and generated code)
=> #2481 Report ignored source properties which are missing

integrationtest/pom.xml
original url is 404 replace with new url
because https://repo.gradle.org/artifactory/libs-releases/ is 404 now
reference to https://repo.gradle.org/ui/repos/tree/General/libs-releases
```
[ERROR] Failed to execute goal on project mapstruct-integrationtest: Could not resolve dependencies for project org.mapstruct:mapstruct-integrationtest:jar:1.5.0-SNAPSHOT: Failed to collect dependencies at org.gradle:gradle-test-kit:jar:5.6.4: Failed to read artifact descriptor for org.gradle:gradle-test-kit:jar:5.6.4: Could not transfer artifact org.gradle:gradle-test-kit:pom:5.6.4 from/to gradle (https://repo.gradle.org/gradle/libs-releases): Transfer failed for https://repo.gradle.org/gradle/libs-releases/org/gradle/gradle-test-kit/5.6.4/gradle-test-kit-5.6.4.pom 503 Service Temporarily Unavailable -> …
```
=> fix(pom): fix gradle repo url 404

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2537/ImplicitSourceTest.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2537/UnmappedSourcePolicyWithImplicitSourceMapper.java
Fixes #2537.
Using the situation as reported in the issue as test.
=> implicit source properties now get removed from unprocessedSourceProperties

documentation/src/main/asciidoc/chapter-5-data-type-conversions.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/conversion/ConversionUtils.java, processor/src/main/java/org/mapstruct/ap/internal/conversion/Conversions.java, processor/src/main/java/org/mapstruct/ap/internal/conversion/URLToStringConversion.java, processor/src/test/java/org/mapstruct/ap/test/conversion/url/Source.java, processor/src/test/java/org/mapstruct/ap/test/conversion/url/Target.java, processor/src/test/java/org/mapstruct/ap/test/conversion/url/URLConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/url/URLMapper.java
In our projects at my job is a frequent use case to convert URL to String. Now we copy the same methods from project to other project to do this conversion.
This built-in conversion would be useful for us and I thought it could be useful for others as well.
Fixes #2552
=> Add URL to String built-in conversions

core/src/main/java/org/mapstruct/Mapper.java, core/src/main/java/org/mapstruct/MapperConfig.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/DefaultOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/DelegatingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/IterableMappingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MapMappingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MapperConfigOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MapperOptions.java, processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/CarMapper.java, processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/CarMapperIterableSettingOnConfig.java, processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/CarMapperIterableSettingOnMapper.java, processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/CarMapperMapSettingOnConfig.java, processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/CarMapperMapSettingOnMapper.java, processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/CarMapperSettingOnConfig.java, processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/CentralIterableMappingConfig.java, processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/CentralMapMappingConfig.java, processor/src/test/java/org/mapstruct/ap/test/nullvaluemapping/NullValueMappingTest.java
With two new parameters for Mapper and MapperConfig, it is now possible to override the nullValueMappingStrategy specifically for MapMapping and IterableMapping.
Fixes #2351
=> #2351 NullValueMappingStrategy for Maps and Iterables

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/NestedTargetPropertyMappingHolder.java, processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/SourceReference.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/test/java/org/mapstruct/ap/test/frommap/FromMapMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/frommap/MapToBeanFromMapAndNestedMapWithDefinedMapping.java
Fixes #2553 
This PR does some small changes in the way we acquire read accessors. The refactorings in the PR, especially the new methods in the `Type` can open the door for better support for things like Jackson `JsonNode`,  `ResultSet`, etc.
=> #2553 Support source property paths for maps

documentation/src/main/asciidoc/chapter-3-defining-a-mapper.asciidoc
The documentation for the new feature for mapping Maps to Beans contains a wrong variable reference in the generated example code.
=> [DOCS] Fixed reference variable

processor/src/main/java/org/mapstruct/ap/internal/model/CollectionAssignmentBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/NewInstanceSetterWrapperForCollectionsAndMaps.java, processor/src/main/java/org/mapstruct/ap/internal/model/assignment/SetterWrapperForCollectionsAndMapsWithNullCheck.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/main/resources/org/mapstruct/ap/internal/model/assignment/NewInstanceSetterWrapperForCollectionsAndMaps.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_2668/Erroneous2668ListMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2668/Erroneous2668MapMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2668/Issue2668Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2668/Issue2668Test.java
Added support for collections and maps with a no-args constructor
Added a compiler error in case of a collection or map without either a no-arg constructor or a copy constructor.
Fixes #2668
=> #2668: Added support for collections and maps with a no-args constructor

core/src/main/java/org/mapstruct/DecoratedWith.java
In some circumstances (used with other types of aggregating processors, e.g. Spring)
the Gradle incremental compilation works correctly only for classes annotated with the `CLASS` or `RUNTIME`
retention policy.
The `@DecoratedWith` is the only annotation from MapStruct that was `SOURCE` retention.
With this commit we are changing its retention policy in order for better compatibility with the Gradle Incremental compilation
Fixes #2682
=> #2682 Change RetentionPolicy of `@DecoratedWith` to `CLASS`

processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/SourceReference.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2677/Issue2677Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2677/Issue2677Test.java
=> #2677 Use type without bounds when looking for read /  presence accessor in a SourceReference

.github/workflows/main.yml, integrationtest/src/test/java/org/mapstruct/itest/tests/MavenIntegrationTest.java, integrationtest/src/test/resources/lombokModuleTest/pom.xml, integrationtest/src/test/resources/lombokModuleTest/src/main/java/module-info.java, integrationtest/src/test/resources/lombokModuleTest/src/main/java/org/mapstruct/itest/lombok/Address.java, integrationtest/src/test/resources/lombokModuleTest/src/main/java/org/mapstruct/itest/lombok/AddressDto.java, integrationtest/src/test/resources/lombokModuleTest/src/main/java/org/mapstruct/itest/lombok/Person.java, integrationtest/src/test/resources/lombokModuleTest/src/main/java/org/mapstruct/itest/lombok/PersonDto.java, integrationtest/src/test/resources/lombokModuleTest/src/main/java/org/mapstruct/itest/lombok/PersonMapper.java, integrationtest/src/test/resources/lombokModuleTest/src/test/java/org/mapstruct/itest/lombok/LombokMapperTest.java, parent/pom.xml, processor/pom.xml, processor/src/main/java/org/mapstruct/ap/MappingProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/processor/DefaultModelElementProcessorContext.java, processor/src/main/java/org/mapstruct/ap/internal/util/AbstractElementUtilsDecorator.java, processor/src/main/java/org/mapstruct/ap/internal/util/EclipseElementUtilsDecorator.java, processor/src/main/java/org/mapstruct/ap/internal/util/ElementUtils.java, processor/src/main/java/org/mapstruct/ap/internal/util/IgnoreJRERequirement.java, processor/src/main/java/org/mapstruct/ap/internal/util/JavacElementUtilsDecorator.java
Prior to this MapStruct would only use `Elements#getTypeElement`.
With this PR if the mapper being generated is within a module MapStruct will use that module
for the methods that are needed (getTypeElement and getPackageElement)
Fixes #2629.
I have to say that I am not the proudest of this piece of code. However, it does it's job. Everything works fine now when running with the module system.
=> #2629 Use ModuleElement when getting type element

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingMethodOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SubclassMappingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SubclassValidator.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MapperCreationProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/processor/MethodRetrievalProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/ErroneousInverseSubclassMapper.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/InverseOrderSubclassMapper.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/SubclassMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/fixture/SubSourceOverride.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/fixture/SubSourceSeparate.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/fixture/SubTargetSeparate.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/fixture/SubclassAbstractMapper.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/fixture/SubclassFixtureTest.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/subclassmapping/fixture/SubclassAbstractMapperImpl.java
`@InheritConfiguration` still not possible with `@SubclassMapping`'s, but `@InheritInverseConfiguration` is possible with `@SubclassMapping`'s.
Added a new error in case of identical source classes in the `@SubclassMapping`'s.
For normal `@SubclassMapping`'s this was easy to spot, but with the `@InheritInverseConfiguration` it was suddenly possible, and you would end up with unreachable code.
```java
if ( A instanceof B ) {
// do mapping
} else if ( A instanceof B ) { // <--- will never be true
// do different mapping //  <--- unreachable code
}
```
Fixes #2696
=> 2696: Invert `@SubclassMappings` with `@InheritInverseConfiguration`.

processor/src/main/resources/org/mapstruct/ap/internal/model/MethodReference.ftl, processor/src/test/java/org/mapstruct/ap/test/conditional/basic/ConditionalMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/conditional/basic/ConditionalMethodWithMappingTargetInUpdateMapper.java
fallback to param.variableName if ext.targetBeanName is not present in MethodReference handling.
fixes #2758
=> #2758: fix crash with MappingTarget in Condition

processor/src/main/java/org/mapstruct/ap/internal/util/Strings.java, processor/src/test/java/org/mapstruct/ap/internal/util/StringsTest.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2748/Issue2748Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2748/Issue2748Test.java
This is an attempt to try and allow mapping of maps that have keys that contain invalid characters for Java method names.  Fixes #2748
=> Mapping map keys with invalid chars for methods

processor/src/main/java/org/mapstruct/ap/internal/model/GeneratedType.java, processor/src/main/java/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2797/ExampleDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2797/ExampleMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2797/Issue2797Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2797/model/BasePerson.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2797/model/Example.java
Type's own imports consist of itself and top levels. Sometimes top level imports are used instead of the Type itself. In this case the top level type needs to be added to the import listing.
fixes #2797
=> #2797: When adding imports for types also check if the types own imports are needed.

processor/src/test/java/org/mapstruct/ap/test/conversion/date/DateConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/naming/VariableNamingTest.java, processor/src/test/java/org/mapstruct/ap/test/nestedmethodcall/NestedMappingMethodInvocationTest.java
Related to #2806. 
We try to stabilise some date conversion tests by read locking the default time zone.
=> Try to stabilise some date conversion tests 

integrationtest/src/test/java/org/mapstruct/itest/tests/MavenIntegrationTest.java, integrationtest/src/test/resources/expressionTextBlocksTest/pom.xml, integrationtest/src/test/resources/expressionTextBlocksTest/src/main/java/org/mapstruct/itest/textBlocks/Car.java, integrationtest/src/test/resources/expressionTextBlocksTest/src/main/java/org/mapstruct/itest/textBlocks/CarAndWheelMapper.java, integrationtest/src/test/resources/expressionTextBlocksTest/src/main/java/org/mapstruct/itest/textBlocks/CarDto.java, integrationtest/src/test/resources/expressionTextBlocksTest/src/main/java/org/mapstruct/itest/textBlocks/WheelPosition.java, integrationtest/src/test/resources/expressionTextBlocksTest/src/test/java/org/mapstruct/itest/textBlocks/TextBlocksTest.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java, processor/src/test/java/org/mapstruct/ap/test/source/defaultExpressions/java/JavaDefaultExpressionTest.java, processor/src/test/java/org/mapstruct/ap/test/source/defaultExpressions/java/MultiLineDefaultExpressionMapper.java, processor/src/test/java/org/mapstruct/ap/test/source/expressions/java/JavaExpressionTest.java, processor/src/test/java/org/mapstruct/ap/test/source/expressions/java/MultiLineExpressionMapper.java
This PR adds support for Java Text Blocks by changing the pattern we use to match an expression to use the `DOTALL` flag (dot matches new lines) and also adding extra whitespaces before `java` and after the closing of the expression. The extra whitespaces are there because a user might make a mistake when typing the expression and have leading whitespace in the string. We don't want to be too strict there.
Fixes #2837
=> #2837 Add support for text blocks in expressions

processor/src/main/resources/org/mapstruct/ap/internal/model/MethodReferencePresenceCheck.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/macro/CommonMacros.ftl, processor/src/test/java/org/mapstruct/ap/test/conditional/basic/ConditionalMappingTest.java, processor/src/test/java/org/mapstruct/ap/test/conditional/basic/ConditionalMethodWithTargetType.java
`targetType` is now correctly passed on through the `MethodReferencePresenceCheck.ftl` to the `MethodReference.ftl`
closes #2882
=> #2882: target type is now correctly passed on

processor/src/test/java/org/mapstruct/ap/testutil/runner/JdkCompilingExtension.java
The test infrastructure that we are using should use UTF-8 for generating the StandardJavaFileManager
This fixes the output " error: unmappable character (0xC3) for encoding US-ASCII" that some people might get when running the MapStruct tests via the command line
=> Use UTF-8 when compiling the tests

processor/src/main/java/org/mapstruct/ap/internal/model/source/MethodMatcher.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2925/Issue2925Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2925/Issue2925Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2925/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_2925/Target.java
When resolving the parameter for a method like:
```
<T> Optional<T> from(T value)
```
There was an exception in javac because getting a DeclaredType from an Optional
with a primitive type argument throws an exception.
Therefore, when assigning the type arguments we get the boxed equivalent.
This problem does not happen in the Eclipse compiler
Fixes #2925
=> #2925 Fix IllegalArgumentException when resolving generic parameters

processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java
Some more stabilisation because it seems like the combination of
* https://github.com/mapstruct/mapstruct/pull/2973
* https://github.com/mapstruct/mapstruct/pull/2972
Are not compatible with each other, and it lead to some test failures on main
Fixes #2990
=> Stabilise top level imports

integrationtest/src/test/java/org/mapstruct/itest/tests/FullFeatureCompilationExclusionCliEnhancer.java
Fixes problems on Java 8 when running the full feature tests with CDI (the new tests were added for #2950). It depends on #2984 for the processor tests to pass
=> #2950 Disable CDI in the full features tests on Java 8

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, ISSUE_TEMPLATE.md
Fixes #3008
This adds new issue templates to our repo.
With this templates when a user clicks on "New Issue" they will see:
Creating a bug report looks like:
Creating a feature request looks like:
Note: The work in this PR has been inspired by what jOOQ offers with their own issue templates https://github.com/jOOQ/jOOQ/issues/new/choose
=> Replace old issue template with new GitHub issue form templates

core/src/main/java/org/mapstruct/Qualifier.java, core/src/main/java/org/mapstruct/SubclassMapping.java, documentation/src/main/asciidoc/chapter-10-advanced-mapping-options.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SubclassMappingOptions.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/qualifier/Composer.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/qualifier/ComposerDto.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/qualifier/ErroneousSubclassQualifiedByMapper.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/qualifier/ErroneousSubclassQualifiedByNameMapper.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/qualifier/Light.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/qualifier/NonExistent.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/qualifier/Rossini.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/qualifier/RossiniDto.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/qualifier/RossiniMapper.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/qualifier/SubclassQualifiedByMapper.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/qualifier/SubclassQualifiedByNameMapper.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/qualifier/SubclassQualifierMapperTest.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/qualifier/Unused.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/qualifier/Vivaldi.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/qualifier/VivaldiDto.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/qualifier/VivaldiMapper.java
Close #3119 
It's a simple fix that just passes along the qualifiers present on the BeanMapping annotation to aid the resolution of the subclass specific method.
I don't know if this is the right approach or you would prefer two specific new attributes on the SubclassMapping annotation. For my needs it is enough.
=> #3119 Add qualifiedBy and qualifiedByName to SubclassMapping annotation

documentation/src/main/asciidoc/chapter-8-mapping-values.asciidoc
Document `<THROW_EXCEPTION>` in the reference guide when describing how to map values, especially enum to enum ones.
Fixes #3112.
=> Document <THROW_EXCEPTION> in the reference guide

core/src/main/java/org/mapstruct/SubclassMappings.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/CompositeSubclassMappingAnnotation.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/SubclassCompositeMapper.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/SubclassMappingTest.java
=> #3174 Also allow multiple SubclassMapping annotations on an annotation `@interface`.

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SubclassMappingOptions.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/qualifier/ErroneousSubclassQualifiedByMapper.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/qualifier/SubclassQualifierMapperTest.java
Fix #3202 
I had to remove one of the `@SubclassMapping` annotations from the erroneous mappers because otherwise the tests would fail.
It seems that if more than one annotations of the same type as `AnnotationMirror` are present on the mapping method the compiler will fallback to emit the error on the method itself. Eclipse compiler seems to work fine regardless of the number of annotations. Is this an already known issue?
=> Improve line location report for invalid qualifier for SubclassMapping

processor/src/main/java/org/mapstruct/ap/internal/model/source/BeanMappingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingMethodOptions.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3248/Issue3248Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3248/Issue3248Test.java
=> #3248 BeanMapping#ignoreUnmappedSourceProperties should be inherited for `@InheritConfiguration`

processor/src/main/resources/org/mapstruct/ap/internal/model/ValueMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_3153/Issue3153Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3153/Issue3153Test.java
When using the compress directive it is going to strip whitespaces from the templates as well (i.e. what the user defined in `ValueMapping#source` and / or `ValueMapping#target`
fixes #3153
=> #3153 Do not use compress directive to strip whitespaces for value mapping switch method

processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingMethodOptions.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/SubclassMappingOptions.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/InheritedSubclassMapper.java, processor/src/test/java/org/mapstruct/ap/test/subclassmapping/SubclassMappingTest.java
=> #3125: Allow subclassmapping inheritance for methods with identical signature.

documentation/src/main/asciidoc/chapter-5-data-type-conversions.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/conversion/ConversionUtils.java, processor/src/main/java/org/mapstruct/ap/internal/conversion/Conversions.java, processor/src/main/java/org/mapstruct/ap/internal/conversion/JavaLocalDateTimeToLocalDateConversion.java, processor/src/test/java/org/mapstruct/ap/test/conversion/java8time/Java8TimeConversionTest.java, processor/src/test/java/org/mapstruct/ap/test/conversion/java8time/Source.java, processor/src/test/java/org/mapstruct/ap/test/conversion/java8time/Target.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/conversion/java8time/SourceTargetMapperImpl.java
Fixes #3199 
Took the liberty of creating a PR.
First time contributing to the project, so do tell if I've missed something!
=> #3199 Add support for implicit conversion between java.time.LocalDate and java.time.LocalDateTime

integrationtest/src/test/java/org/mapstruct/itest/tests/MavenIntegrationTest.java, integrationtest/src/test/resources/sealedSubclassTest/pom.xml, integrationtest/src/test/resources/sealedSubclassTest/src/main/java/org/mapstruct/itest/sealedsubclass/Bike.java, integrationtest/src/test/resources/sealedSubclassTest/src/main/java/org/mapstruct/itest/sealedsubclass/BikeDto.java, integrationtest/src/test/resources/sealedSubclassTest/src/main/java/org/mapstruct/itest/sealedsubclass/Car.java, integrationtest/src/test/resources/sealedSubclassTest/src/main/java/org/mapstruct/itest/sealedsubclass/CarDto.java, integrationtest/src/test/resources/sealedSubclassTest/src/main/java/org/mapstruct/itest/sealedsubclass/Davidson.java, integrationtest/src/test/resources/sealedSubclassTest/src/main/java/org/mapstruct/itest/sealedsubclass/DavidsonDto.java, integrationtest/src/test/resources/sealedSubclassTest/src/main/java/org/mapstruct/itest/sealedsubclass/Harley.java, integrationtest/src/test/resources/sealedSubclassTest/src/main/java/org/mapstruct/itest/sealedsubclass/HarleyDto.java, integrationtest/src/test/resources/sealedSubclassTest/src/main/java/org/mapstruct/itest/sealedsubclass/Motor.java, integrationtest/src/test/resources/sealedSubclassTest/src/main/java/org/mapstruct/itest/sealedsubclass/MotorDto.java, integrationtest/src/test/resources/sealedSubclassTest/src/main/java/org/mapstruct/itest/sealedsubclass/SealedSubclassMapper.java, integrationtest/src/test/resources/sealedSubclassTest/src/main/java/org/mapstruct/itest/sealedsubclass/Vehicle.java, integrationtest/src/test/resources/sealedSubclassTest/src/main/java/org/mapstruct/itest/sealedsubclass/VehicleCollection.java, integrationtest/src/test/resources/sealedSubclassTest/src/main/java/org/mapstruct/itest/sealedsubclass/VehicleCollectionDto.java, integrationtest/src/test/resources/sealedSubclassTest/src/main/java/org/mapstruct/itest/sealedsubclass/VehicleDto.java, integrationtest/src/test/resources/sealedSubclassTest/src/test/java/org/mapstruct/itest/sealedsubclass/SealedSubclassTest.java, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/Type.java
@filiphr do you know how to add a failure test for java 17+ situations?
Currently I've only added the happy flow situation to the integration test.
Fixes #3054
=> #3054: Allow abstract return type when all directly sealed subtypes are covered by subclass mappings.

processor/src/main/java/org/mapstruct/ap/internal/model/CollectionAssignmentBuilder.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3104/Issue3104Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3104/Issue3104Test.java
=> #3104 Update methods with NullValuePropertyMappingStrategy.IGNORE should use SetterWrapperForCollectionsAndMapsWithNullCheck

processor/src/main/java/org/mapstruct/ap/internal/processor/MethodRetrievalProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/conditional/targetpropertyname/ErroneousNonStringTargetPropertyNameParameter.java, processor/src/test/java/org/mapstruct/ap/test/conditional/targetpropertyname/TargetPropertyNameTest.java
Check that a parameter annotated with @TargetPropertyName is String and report an error.
With the following mapper:
```java
@Mapper
public interface ErroneousNonStringTargetPropertyNameParameter {
Employee map(EmployeeDto employee);
@Condition
default boolean isNotBlank(String value, @TargetPropertyName int propName) { // propName is int
return value != null && !value.trim().isEmpty();
}
}
```
Compilation will fail with this error message:
> error: @TargetPropertyName can only by applied to a String parameter.
Fixes #2863
=> #2863 Add validation of String type to @TargetPropertyName

build-config/src/main/resources/build-config/checkstyle.xml, documentation/src/main/asciidoc/chapter-12-customizing-mapping.asciidoc, documentation/src/main/asciidoc/chapter-13-using-mapstruct-spi.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/MappingMethod.java, processor/src/main/resources/org/mapstruct/ap/internal/model/BeanMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/builder/lifecycle/BuilderLifecycleCallbacksTest.java, processor/src/test/java/org/mapstruct/ap/test/builder/lifecycle/MappingContext.java
Hi,
this is my first PR for mapstruct. Disclaimer: Because of the IntelliJ Community Edition I do not have any highlighting or formatting for `.ftl` files, so bear with me. 😅 
I tried to be as consistent as possible with the naming of the lifecycle method reference collections (`beforeMappingReferencesWithFinalizedReturnType` & `afterMappingReferencesWithFinalizedReturnType`) but if you have better suggestions, please tell me.
There is one edge-case i stumbled accross. With supporting `@AfterMapping` on the targets builder and finalized object, the following combination can be done by using methods **both returning** the result:
```java
// snippet of processor/src/test/java/org/mapstruct/ap/test/builder/lifecycle/MappingContext.java
@AfterMapping
public Order …
```
=> #1454 Support for lifecycle methods on type being built with builders

processor/src/main/resources/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.ftl, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_1561/Issue1561MapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_1685/UserMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/bugs/_2245/TestMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/constructor/nestedsource/ArtistToChartEntryImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/constructor/nestedtarget/ChartEntryToArtistImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedbeans/mixed/FishTankMapperImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedsourceproperties/ArtistToChartEntryImpl.java, processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedtargetproperties/ChartEntryToArtistImpl.java
The code changes provided try removing redundant null checks for nested properties.
Fixes #3245.
=> Remove redundant null checks in nested properties

processor/src/main/java/org/mapstruct/ap/internal/model/LifecycleMethodResolver.java, processor/src/main/java/org/mapstruct/ap/internal/model/ObjectFactoryMethodResolver.java, processor/src/main/java/org/mapstruct/ap/internal/model/PresenceCheckMethodResolver.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/CreateOrUpdateSelector.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/FactoryParameterSelector.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/InheritanceSelector.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/MethodFamilySelector.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/MethodSelector.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/MethodSelectors.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/MostSpecificResultTypeSelector.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/QualifierSelector.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/SelectionContext.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/SourceRhsSelector.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/TargetTypeSelector.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/TypeSelector.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/XmlElementDeclSelector.java, processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java
Doing this will make it more easy to fix #3209, #1610 and #2610. 
Mostly for #2610 the parameter bindings will need to be slightly different, so it makes it easier if we can provide them from the context itself
=> Refactor method selection and use a context to be able to more easily access information

processor/src/main/resources/org/mapstruct/ap/internal/model/BeanMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_3317/Issue3317Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3317/Issue3317Test.java
=> #3317 Do not generate source parameter if check for only primitives

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/ContainerMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/MapMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/model/MethodReferencePresenceCheck.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/NegatePresenceCheck.java, processor/src/main/java/org/mapstruct/ap/internal/model/common/PresenceCheck.java, processor/src/main/java/org/mapstruct/ap/internal/model/presence/AllPresenceChecksPresenceCheck.java, processor/src/main/java/org/mapstruct/ap/internal/model/presence/JavaExpressionPresenceCheck.java, processor/src/main/java/org/mapstruct/ap/internal/model/presence/NullPresenceCheck.java, processor/src/main/java/org/mapstruct/ap/internal/model/presence/SuffixPresenceCheck.java, processor/src/main/resources/org/mapstruct/ap/internal/model/BeanMappingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/IterableMappingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/MapMappingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/MethodReferencePresenceCheck.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/StreamMappingMethod.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/common/NegatePresenceCheck.ftl, processor/src/main/resources/org/mapstruct/ap/internal/model/presence/NullPresenceCheck.ftl
Instead of explicitly doing a null check use a PresenceCheck mechanism for
* BeanMappingMethod
* ContainerMappingMethod
* MapMappingMethod
Fixes #3347
=> #3347 Use presence checks for checking source parameter presence

processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingMethodOptions.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3361/Issue3361Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3361/Issue3361Test.java
Fixes #3361.
The issue was caused by the fixes done for ##2101 in PR ##2103.
@sjaakd can you please have a look at this PR?
=> #3361 Inheriting mappings should only be applied if the target has been redefined

copyright.txt, core/src/main/java/org/mapstruct/SubclassMapping.java
Just a small fix for a typo in the JavaDoc I recognized during use of the lib.
=> Fix Typo Mappper in SubclassMapping Doc

processor/src/test/java/org/mapstruct/ap/testutil/runner/CompilingExtension.java
Skip checkstyle ifthe system property `checkstyle.skip[=true]` is set (except in the rare case that someone sets it to `checkstyle.skip=false`).
This reducces my build time from 7min 34sec to 6min 49sec. An improvement about 11%. 👍 
Fixes #1064
=> #1064 Provide a switch to turn off CheckStyle on generated sources

documentation/src/main/asciidoc/chapter-10-advanced-mapping-options.asciidoc
=> Fix typo chapter-10-advanced-mapping-options.asciidoc

processor/src/main/java/org/mapstruct/ap/internal/util/NativeTypes.java
`Double.parseDouble` returns a primitive `double` and `Float.parseFloat` returns a primitive`float`. By using the primitive types directly instead of the wrapper types unnecessary boxing can be avoided.
=> use primitive types in NativeTypes

processor/src/main/java/org/mapstruct/ap/internal/model/Javadoc.java
Currently there the type of `authors` is missing. I added it as `List<String>`
=> add missing generic type to Javadoc Builder

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3360/Issue3360Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3360/Issue3360Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3360/Vehicle.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3360/VehicleDto.java
=> #3360 Do not report unmapped source and target properties when result type is  abstract due to runtime exception subclass exhaustive strategy

processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3485/ErroneousIssue3485Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3485/Issue3485Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3485/Issue3485Test.java
Currently using this `.` as a target results in a NPE see #3485.
I added a MappingOptions validation to check if source is present when this target is used. If not a error is reported to use user instead of an crash with NPE.
=> #3485 Exception for Mapping to target = "." without source

.github/scripts/update-website.sh, .github/workflows/release.yml, NEXT_RELEASE_CHANGELOG.md, parent/pom.xml, pom.xml
Add JReleaser for automating the release and add a step for automating the publishing of the website
This has been heavily inspired by the [Moditect](https://github.com/moditect/moditect/blob/main/.github/workflows/release.yml) and [JReleaser](https://github.com/jreleaser/jreleaser/blob/main/.github/workflows/release.yml) release procedures.
Not sure if @aalmiray, the creator of JReleaser, might be able to chime in and let us know if I'm doing something incorrectly here.  Not sure what the best approach would be to test this with an actual Maven release. 
I think doing the 1.6.0.Beta2 release would be a good first try for this.
Closes #3602
=> Automate release with JReleaser

NEXT_RELEASE_CHANGELOG.md, documentation/src/main/asciidoc/chapter-10-advanced-mapping-options.asciidoc, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/ignorebydefaultsource/ErroneousSourceTargetMapperWithIgnoreByDefault.java, processor/src/test/java/org/mapstruct/ap/test/ignorebydefaultsource/IgnoreByDefaultSourcesTest.java
This reverts #2560, because we've decided that `@BeanMapping(ignoreByDefault = true)` should only be applied to target properties and not to source properties. Source properties are anyway ignored, the `BeanMapping#unmappedSourcePolicy` should be used to control what should happen with unmapped source policy
Fixes #3574
=> #3574 Respect only explicit mappings but fail on unmapped source fields

NEXT_RELEASE_CHANGELOG.md, processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3652/Bar.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3652/Foo.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3652/FooBarConfig.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3652/FooBarMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3652/Issue3652Test.java
Fixes #3652
I have added a test case where the target has a property that does not exist on the source type.
The inverse inheritation still works, because this property is then simply ignored in `BeanMappingMethod#handleDefinedMapping` (line 1240):
```java
else if ( inheritContext.isReversed() ) {
// When a configuration is reverse inherited and there are no read or write accessor
// then we should ignore this mapping.
// This most likely means that we were mapping the source parameter to the target.
// If the error is due to something else it will be reported on the original mapping
return false;
}
```
I have another question:
The javadoc of `MappingOptions#canInverse` says:
>mapping can only be inversed if the source was not a constant nor an expression **nor a nested property**
But …
=> #3652 Inverse Inheritance possible for ignore-mappings without source

NEXT_RELEASE_CHANGELOG.md, processor/src/main/java/org/mapstruct/ap/internal/model/NestedTargetPropertyMappingHolder.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3670/Issue3670Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3670/Issue3670Test.java
=> #3670 Fix regression when using `InheritInverseConfiguration` with nested target properties and reversing `target = "."`

processor/src/main/java/org/mapstruct/ap/internal/model/beanmapping/MappingReference.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3667/Issue3667Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3667/Issue3667Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3667/Source.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3667/Target.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3673/Animal.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3673/Cat.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3673/Details.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3673/Dog.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3673/Issue3673ConstantMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3673/Issue3673ExpressionMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3673/Issue3673Test.java
Fixes #3667
Fixes #3673 
The main culprit for this was due to the fact that the `MappingReference` was using `MappingOption` equality and the `MappingOption` is based only on the `targetName`, but we need to take `sourceName`, `constant` and `expression` into consideration.
All the tests should be green, and I hope that this isn't causing another regression.
=> #3667, #3673 MappingReference should custom MappingOption equality instead of the default only target name based one

NEXT_RELEASE_CHANGELOG.md, processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3668/Child.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3668/ChildDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3668/ChildMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3668/Issue3668Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3668/Parent.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3668/ParentDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3668/ParentMapper.java
Fixes #3668
This fixes the issue. However, the cause is not in the way this was fixed. The main issue why this happens is due to the fact that in 1.6 we treat generics a bit better and we determine that we can use something when mapping the abstract target type.
If the `Parent` and `ParentDto` targets are not abstract we would still have the MapStruct compile error. However, this is not a regression as in 1.5 we would generate code that does not compile. I'll create a separate issue to look into this.
=> #3668 Do not apply implicit mappings when using `SubclassExhaustiveStrategy#RUNTIME_EXCEPTION` and return type is abstract

readme.md
Currently the `target` tag for the `maven-compiler-plugin` is not closed correctly.
=> Fix typo in readme Maven plugin config

processor/src/main/resources/org/mapstruct/ap/internal/model/BeanMappingMethod.ftl, processor/src/test/java/org/mapstruct/ap/test/bugs/_3703/Issue3703Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3703/Issue3703Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3703/dto/Contact.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3703/entity/Contact.java
=> #3703 Use include model instead of manually writing the type name for  return type for afterMappingReferencesWithFinalizedReturnType

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3678/Issue3678Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3678/Issue3678Test.java
Fixes #3678 
I am not too happy with the fix. There are alternative ways to avoid going through the lifecycle methods twice. However, this is the least invasive way to fix this for 1.6.
What do you think @thunderhook?
=> #3678 before / after mapping for type using builder should only be kept if they are using the actual type in `@TargetType` or `@MappingTarget`

processor/src/main/java/org/mapstruct/ap/internal/model/AbstractBaseBuilder.java, processor/src/main/java/org/mapstruct/ap/internal/model/AnnotatedConstructor.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/InheritanceSelector.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/SourceRhsSelector.java
This PR addresses typo corrections and readability improvements across several classes.
- AnnotatedConstructor: Fixed a variable name typo (noArgConstructorToInBecluded → noArgConstructorToBeIncluded) to enhance code clarity.
- AbstractBaseBuilder: Improved Javadoc by fixing typos and clarifying wording for better documentation quality.
- SourceRhsSelector: Corrected a typo in the class-level Javadoc.
- InheritanceSelector: Enhanced readability by fixing typos in variable names and refining comments.
This PR aims to improve code and documentation readability and clarity without altering functionality.
=> Fix typos and improve readability in multiple classes

documentation/src/main/asciidoc/chapter-10-advanced-mapping-options.asciidoc
The repeated "it is" and the comma makes the meaning slightly wrong IMO.
=> chore(docs): Improved wording about @Condition usage

processor/src/main/java/org/mapstruct/ap/MappingProcessor.java, processor/src/main/java/org/mapstruct/ap/internal/model/LifecycleMethodResolver.java, processor/src/main/java/org/mapstruct/ap/internal/model/ObjectFactoryMethodResolver.java, processor/src/main/java/org/mapstruct/ap/internal/model/PresenceCheckMethodResolver.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/LifecycleOverloadDeduplicateSelector.java, processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/MethodSelectors.java, processor/src/main/java/org/mapstruct/ap/internal/option/Options.java, processor/src/main/java/org/mapstruct/ap/internal/processor/creation/MappingResolverImpl.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3849/Child.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3849/ChildDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3849/DeduplicateBySourceMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3849/DeduplicateByTargetMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3849/DeduplicateForCompileArgsMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3849/DeduplicateGenericMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3849/Issue3849Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3849/Parent.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3849/ParentDto.java
fix: [3849](https://github.com/mapstruct/mapstruct/issues/3849)
Newly added `LifecycleOverloadDeduplicateSelector`, which uses multiple features such as **class name** and **method name** as keys to group methods.
And then selects the best method within the group by comparing the inheritance distance of parameters, 
to achieve deduplication between similar overloaded methods. 
The parameters involved in the inheritance distance calculation are not limited to `@MappingTarget`, but all input parameters of a group of candidate methods are traversed and calculated in sequence until a parameter is found with the shortest distance, then the traversal is terminated. (Avoid the situation where the **@MappingTarget** parameter type is the same but other parameters are different).
=> fix: resolve duplicate invocation of overloaded lifecycle methods with inheritance

processor/src/main/java/org/mapstruct/ap/internal/processor/MethodRetrievalProcessor.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3711/BaseMapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3711/Issue3711Test.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3711/JpaContext.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3711/ParentDto.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3711/ParentEntity.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3711/SourceTargetMapper.java
fix: https://github.com/mapstruct/mapstruct/issues/3711
The bug is caused by not handling generics properly when generating context methods
=> fix: methods contained in @Context classes don't support generics

processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java, processor/src/main/java/org/mapstruct/ap/internal/util/Message.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3902/ErroneousIssue3902Mapper.java, processor/src/test/java/org/mapstruct/ap/test/bugs/_3902/Issue3902Test.java
fix #3908 (follow up#3902) add `mostSimilarProperty` message 
Ex) No property named "foo" exists in @Ignored for target type "ErroneousIssue3902Mapper.ZooDto" Did you mean "name"?
The implementation refactors the `handleDefinedMapping` method to reuse the existing `getMostSimilarWord` logic for the `@Ignored` case.
Test cases have been updated and expanded to verify that the suggestions are working correctly, especially for typos.
=> #3908: Add similar suggestion for unknown property in @Ignored
